### ISSUE TITLE
Allow alphanum call numbers to be browsed

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/SearchWorks#1011]
We can just add `ALPHANUM` to the `BROWSABLE_CALLNUMBERS` array: https://github.com/sul-dlss/SearchWorks/blob/master/lib/constants.rb#L1090

We need to check with the indexing team (cc: @lmcglohon/@ndushay) to validate that shelfkeys are still generated for ALPHANUM call numbers before we :shipit:

**Comment by jkeck** [comment]
@mejackreed:
![@mejackreed](http://i.imgur.com/owS2I.gif)

**Comment by mejackreed** [comment]
![](http://media.giphy.com/media/iFts0nvt3XDH2/giphy.gif)

**Comment by ahafele** [comment]
sw-1339
