### ISSUE TITLE
Remove shelving range from the StackMap display.

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/SearchWorks#1019]
SW-1470

**Comment by jvine** [comment]
https://jirasul.stanford.edu/jira/browse/SW-1396

**Comment by jvine** [comment]
also https://jirasul.stanford.edu/jira/browse/SW-1530

**Comment by jvine** [comment]
Call number PS1303 .R37 2001 is located in Green Library, 3rd floor of the East Wing.
