### ISSUE TITLE
Implement WebAuth Login

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/SearchWorks#1032]
cc: @jvine Not sure if you have any mockups describing the login link in SW.

**Comment by jvine** [comment]
For now, use the same pattern as the Requests app:

Login   My Account   Feedback
jvine: Logout   My Account   Feedback

This will cause the top nav area to wrap to 2 lines on mobile, and I don't have a good solution to this yet, so just let it wrap. Some element(s) will have to drop out at xs size.

**Comment by jvine** [comment]
Done w Requests
