### ISSUE TITLE
Virtual objects: link from child to parent

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1051]
Individually-discoverable child objects will have a special "related item" link to their parent record.

example child
http://searchworks-test.stanford.edu/preview/view/yr145dc7638
and parent
http://searchworks-test.stanford.edu/preview/view/10449093

Create a sidebar block in the child record that links to the parent. Appears above the "Collection" block (if there is one).

Block title is "Appears in"
Body shows the material-type icon, title, and date of the parent. Title is linked directly to the parent record.

![screen shot 2015-08-25 at 2 51 56 pm](https://cloud.githubusercontent.com/assets/6945691/9480601/dea5ad0e-4b38-11e5-8262-5a4dda4586f2.png)

![screen shot 2015-08-25 at 2 54 55 pm](https://cloud.githubusercontent.com/assets/6945691/9480692/595df34e-4b39-11e5-97c2-cc79b088721a.png)

**Comment by ndushay** [comment]
This is currently blocked by https://github.com/sul-dlss/dor-services/pull/128   as we can't index data unless it is in public xml

**Comment by ndushay** [comment]
for items that are part of virtual objects:

indexing:
- [ ] set of the thing, and title of the thing it is a constituent of  (in addition to coll info)

UI:
- [ ] utilize constituent set and info  in display block
- [ ] treat it like an individual item with link to coll, link to constituent info
- [ ] need to know thumbnail (e.g. first image)
- [ ] from (set):  need to display items

**Comment by blalbrit** [comment]
Child object with link from child to parent implemented in purl-test: https://purl-test.stanford.edu/bv599bt4452
