### ISSUE TITLE
Viewer index: one ckey with multiple druids

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1052]
Single ckey with multiple druids in managed 856 tags. 
http://searchworks-test.stanford.edu/preview/view/9050672
http://searchworks-test.stanford.edu/preview/view/9958647

- Create a "parts list" to the left of the embed; one item per managed 856.
- List is labeled with the total number of "parts".
- Each item has a 100x100 thumbnail (same logic as collection filmstrip) OR a resource type icon.
- "Part #" label is generated unless there is an explicit label (to start with, no objects will have explicit labels).
- Image count (or file count) for the object is shown below the label.
- List should have the same max-height as the viewer, with overflow: hidden; overflow-y: auto.
- Move the floating metadata section from the upper metadata row down to the right column of the lower metadata row.
- When the user clicks an item in the parts list, the embed viewer is switched out with the appropriate one for that image.
- Currently-selected part is visibly highlighted.
- When user clicks a part in the list, the viewer is updated to show that part.
- Viewer header reflects the selected part.
- Would be nice to be able to link directly to a part - for example, if a defunct /view/druid URL (which exist in pre-stanford-sync SW) could forward to /view/ckey?part=druid (or something).

![multi-part-druids](https://cloud.githubusercontent.com/assets/6945691/9481329/1bf993c8-4b3e-11e5-8176-9a8e826cd3f3.png)

**Comment by mejackreed** [comment]
@lmcglohon Are there any examples you know of that have many managed purls?

**Comment by lmcglohon** [comment]
Here are a few:

http://searchworks-test.stanford.edu/preview/view/8923338
http://searchworks-test.stanford.edu/preview/view/9335033

**Comment by mejackreed** [comment]
Thanks @lmcglohon ... Do you know how the file_id's in the marc_xml file_id's are being created? For this example: http://searchworks.stanford.edu/?utf8=%E2%9C%93&search_field=search&q=jr660fb3654&format=json the file_id jr660fb3654_00_0001 seems to be incorrect. Though, jr660fb3654_05_0001 seems to work

**Comment by jkeck** [comment]
Question of @jvine:

What, if any, links should be displayed in the `Online` block for digital objects?  Currently we do not display any links in the `Online` block for digital objects.  Should we retain this behavior or should we display any fulltext 856s that are **NOT** managed purls?

**Comment by lmcglohon** [comment]
@mejackreed the file_id is coming from the file_ids or image_ids in the purl xml file contentMetadata/resource.

**Comment by mejackreed** [comment]
Thanks @lmcglohon ... in the case of http://purl.stanford.edu/jr660fb3654.xml it seems to be a different file_id ? no?

**Comment by lmcglohon** [comment]
@mejackreed yes, the data is bad.  Sorry about that.  Do you need more examples?

**Comment by mejackreed** [comment]
Not necessarily, but wondering if we can count on the data being correct?

**Comment by lmcglohon** [comment]
Hopefully.  But we haven't been allowed to use "real" data yet.

**Comment by mejackreed** [comment]
e2f5685de494d97b232e73a8662f4676484162f0 adds the UI component to the many managed purls view experience. There are however a couple of loose ends:

 - from what I can tell there is currently no way to parse out a label from the 856 field. Is this correct?
 - chevron arrows on selected purl still needs to be added. This gets kind of weird and before proceeding, I would really like to have some more test objects. Specifically I need ones with many purls (>6) and ones that are not images
 - pretty sure that viewer header is not going to be able to update unless we start doing some `postMessage` stuff. Not sure how hard that is going to be
 - I'm not sure that we are able to put the resource type icon in there. Where does this come from for each purl? Do we have some examples?

Note: some data is incorrect (see below)

### 9335033

![screen shot 2015-09-17 at 11 58 23 am](https://cloud.githubusercontent.com/assets/1656824/9943012/8038dbda-5d33-11e5-8cc9-6c65d6b9a9d6.png)

**Comment by jvine** [comment]
> What, if any, links should be displayed in the Online block for digital objects? Currently we do not display any links in the Online block for digital objects. Should we retain this behavior or should we display any fulltext 856s that are NOT managed purls?

It would be helpful to see IRL examples to know what kind of content might be represented by additional URLs, but my guess is that we will need to list non-managed-purl URLs in an Online block.

**Comment by jvine** [comment]
> from what I can tell there is currently no way to parse out a label from the 856 field. Is this correct?

As far as I recall, there is no label currently added to the 856 field, because there is no PURL-level label other than the title, which would be the same for all. So this is a "future".

> chevron arrows on selected purl still needs to be added. This gets kind of weird and before proceeding, I would really like to have some more test objects. Specifically I need ones with many purls (>6) and ones that are not images

If the current image is clearly visibly selected (and the visual design above, though pretty, is not strong enough to communicate selectedness) then the arrow is redundant/not essential.

> pretty sure that viewer header is not going to be able to update unless we start doing some postMessage stuff. Not sure how hard that is going to be

You mean with number of files/images? Don't understand.

> I'm not sure that we are able to put the resource type icon in there. Where does this come from for each purl? Do we have some examples?

I was basing it on this display:
http://searchworks.stanford.edu/view/yk804rq1656
but maybe we don't have the same info available to us...? 
@laney, could we add something to the 856 to indicate resource type?

**Comment by lmcglohon** [comment]
@jvine We could add resource type to the 856.  But that needs to be prioritized by someone other than me.

**Comment by mejackreed** [comment]
@jvine 

> If the current image is clearly visibly selected (and the visual design above, though pretty, is not strong enough to communicate selectedness) then the arrow is redundant/not essential.

Happy to add the arrows, I just need some more test objects (many purls >6) and other types of objects (non image)

> You mean with number of files/images? Don't understand.

In the design, the embed image number display has additional text `part 1 (1 image)` which is not coming from embed. I'm trying to understand the full scope of the requirement and how this should happen. Unfortunately it starts to get complex because we don't have direct access to the iframe here.

**Comment by lmcglohon** [comment]
@jvine we have the display_type in the 3rd subfield x in the 856.  Doesn't that give you the information you need for the icon?

**Comment by jvine** [comment]
@lmcglohon oh that might work! Do we have any examples yet that aren't maps or images?

**Comment by lmcglohon** [comment]
@jvine I don't think so

**Comment by mejackreed** [comment]
Thanks @lmcglohon , I think @jkeck mentioned that there might be an issue with using that. Jessie can you comment on that?
