### ISSUE TITLE
Parse MODS Geo Extension for Index and Display

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1069]
MODS Geo records indexed into SW will have:
- primary Resource type of Maps based on `<typeOfResource>cartographic</typeOfResource>`
  - "primary" means the Maps icon should be the one that displays for these records.
- optional second Resource type based on `<typeOfResource>[value]</typeOfResource>` 
  - the second value will generally be either Dataset or Software/Multimedia
  - we will probably need to map the actual values in MODS to the facet values we use in SW.

We'd like to change the Resource type value of "Map" to "Map/Geospatial" - if we can do this without breaking existing searches.

The MODS includes the Geo extension, which looks something like this:
```
<extension displayLabel="geo">
  <rdf:RDF xmlns:gml="http://www.opengis.net/gml/3.2/" xmlns:dc="http://purl.org/dc/elements/1.1/">
    <rdf:Description rdf:about="http://purl.stanford.edu/tp721xt8125">
      <dc:format>application/x-esri-shapefile; format=Shapefile</dc:format>
      <dc:type>Dataset#Polygon</dc:type>
      <gml:boundedBy>
        <gml:Envelope gml:srsName="EPSG:4326">
          <gml:lowerCorner>73.44696 6.318641</gml:lowerCorner>
          <gml:upperCorner>135.085831 53.557926</gml:upperCorner>
        </gml:Envelope>
      </gml:boundedBy>
      <dc:coverage rdf:resource="http://sws.geonames.org/1814991/about.rdf" dc:language="eng" dc:title="China"/>
    </rdf:Description>
  </rdf:RDF>
</extension>
```
(example: https://sul-purl-prod-b.stanford.edu/tp721xt8125)

We want to use this bit:
```
      <dc:format>application/x-esri-shapefile; format=Shapefile</dc:format>
      <dc:type>Dataset#Polygon</dc:type>
```
to display the values after "format=" and "Dataset#" in the search results.

![gis results w preview](https://cloud.githubusercontent.com/assets/6945691/10703669/78616aca-7986-11e5-8101-03f23772e330.png)

In all other respects, the MODS display gem should just do its thing; the embedded viewer should do its thing; etc.

**Comment by jkeck** [comment]
@jvine should `Shapefile; Polygon` not show up on the record view at all?

**Comment by jvine** [comment]
Oh yeah, they should. In the upper metadata section. Not sure of label - I think "Format".

**Comment by jkeck** [comment]
Hrmm, okay.

Presumably this should show up in purl.stanford.edu as well (which means we should have this logic in ModsDisplay)?

I'm wondering if this is something that we should *also* do in the indexing code given its existence in the results display. (I have concerns about the performance implications of parsing MODS in the search results)

**Comment by jkeck** [comment]
Stashing for potential later use:

```ruby
require 'faraday'
require 'mods'

url = 'https://purl.stanford.edu/tp721xt8125.mods'
xml = Faraday.get(url).body

mods = Mods::Record.new.from_str(xml)

def geo_extensions(mods)
  mods.extension.select do |extension|
    extension.attributes['displayLabel'].try(:value) == 'geo'
  end
end

geo_extensions(mods).map do |extension|
  rdf = Nokogiri::XML(extension.children.to_s)
  {
    format: rdf.xpath('//dc:format').text[/format=(.*)$/, 1],
    type: rdf.xpath('//dc:type').text[/#(.*)$/, 1]
  }
end
```

**Comment by ndushay** [comment]
Not sure if this is right place;  Laney asked me to profile some mods with geo stuff.  Her two examples were (I think from Jack originally):

https://purl.stanford.edu/tg926kp6619
https://purl.stanford.edu/cz128vq0535

I tracked back to which collections and did mods profiling for those 2 colls:

human-impact-marine:  https://sul-solr.stanford.edu/solr/mods_profiler/select?fq=collection:uganda&facet.limit=-1&rows=0&facet.sort=index

uganda: https://sul-solr.stanford.edu/solr/mods_profiler/select?fq=collection:uganda&facet.limit=-1&rows=0&facet.sort=index

**Comment by ndushay** [comment]
Indexing:
(not confident)
- [ ] after format= from ```<dc:format>application/x-esri-shapefile; format=Shapefile</dc:format>```
- [ ] after dataset# from ```<dc:type>Dataset#Polygon</dc:type>```

**Comment by ndushay** [comment]
UI work: 

- [ ] mods-display:   can be displayed in record view 
- [ ] SearchWorks UI code to utilize mods-display 

without indexing:
- [ ] would not appear in search results
- [ ] searchable only via catch-all field

**Comment by jkeck** [comment]
See sul-dlss/mods_display#24
