### ISSUE TITLE
Can Bookplate images be treated like Google Book covers rather than image resources?

### ISSUE THREAD

**Issue by snydman** [sul-dlss/SearchWorks#1076]
Due to the nature of the bookplate images, and the OSD zoom feature in embed, the Bookplate images are not displaying ideally.  We are still investigating this, but I wonder if it is feasible to treat the Bookplate images in SearchWorks record pages like Google Book Cover images.  Instead of displaying them in the embed viewer, making a call to the IIIF service and returning a static JPEG, appropriately sized. 

Thoughts? @jvine @jkeck

**Comment by mejackreed** [comment]
Ticket in embed?

**Comment by jkeck** [comment]
@snydman the intended design is not to use SUL-Embed for the Bookplates (see #1062).

There is a `Bookplates` section in the metadata where we pull in static images directly into the page.

Also, these items might have real book covers from Google which I don't think we want to obscure.

**Comment by snydman** [comment]
👍

**Comment by jvine** [comment]
@snydman this is a good question for the Spotlight exhibit, though.
