### ISSUE TITLE
Support call number browse for e-books

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/SearchWorks#1077]
Example: 7879037

**Comment by jkeck** [comment]
Question for @jvine:

Currently e-books will show up in the call number browse for items with legitimate call numbers (e.g. 3070858 the item immediately to the left in the call-number browse is e-book 7879037).  This is displayed with a (no call number).

<img width="1204" alt="browse" src="https://cloud.githubusercontent.com/assets/96776/10833700/2da92e8a-7e51-11e5-9f56-fda467d9da58.png">

Should we retain this behavior?  If so, when on the record view for the e-book should we still display (no call number)?

<img width="1217" alt="ebook-browse" src="https://cloud.githubusercontent.com/assets/96776/10833751/906094be-7e51-11e5-887b-d61df778e7e8.png">

**Comment by jvine** [comment]
@jkeck Can we change "(no call number)" to "eResource" for e-books, in all circumstances where it displays? And retain "(no call number)" for everything else (which I think is just on-order items)? The e-items have `999 a| INTERNET RESOURCE`.
