### ISSUE TITLE
Next/Previous buttons on show page shows wrong results

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/SearchWorks#1082]
See: https://github.com/projectblacklight/blacklight/issues/1278

**Comment by jkeck** [comment]
Is it particularly necessary to have this bug filed here if it'll be fixed upstream in Blacklight?

**Comment by mejackreed** [comment]
Maybe not... just did so to track where/when it gets merged. Feel free to close.

**Comment by jvine** [comment]
Linked issue is closed.
