### ISSUE TITLE
"Bound with" note should appear only if 590 has subfield c.

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1092]
SW-1478, SW-1416

https://searchworks.stanford.edu/view/351225
https://searchworks.stanford.edu/view/495733
https://searchworks.stanford.edu/view/10164799

The bound-with note in yellow should not appear if the 590 does not have a subfield c.

**Comment by jkeck** [comment]
3942974 has a 590 with a $c that represents a legitimate bound-with note.
