### ISSUE TITLE
Remove subfield h from uniform title linked search

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1093]
https://searchworks.stanford.edu/view/10695000
Clicking the uniform title link gets 0 results. Search string includes $h, but the title index does not (by design). 

Maybe related to #104 ?

SW-1402

**Comment by jkeck** [comment]
@shelleydoljack anyway you can drum up a new example ckey?  The ones in the relevant tickets don't seem to exist any longer.

Thanks.

**Comment by ahafele** [comment]
@jkeck  https://searchworks.stanford.edu/view/11534515
