### ISSUE TITLE
Display info in parens after ISBNs

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1094]
Example: https://searchworks.stanford.edu/view/10093362

MARC has 
```
020      a| 9783863351915 (Koenig Books)
020      a| 3863351916 (Koenig Books)
020      a| 9789186243371 (Moderna Museet)
020      a| 9186243373 (Moderna Museet)
```
but we display
```
ISBN
   9783863351915
   3863351916
   9789186243371
   9186243373
```

Not sure why we're suppressing the extra info (because it's not in the index, maybe?) but we should be displaying it.

SW-1389

**Comment by jkeck** [comment]
Closed by #1123
