### ISSUE TITLE
Add sidebar top/bottom nav buttons to search results

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1098]
Same as on the record view, but only top/bottom links. They should be in the DOM somewhere around the pagination.

![screen shot 2015-11-06 at 11 49 37 am](https://cloud.githubusercontent.com/assets/6945691/11007126/b10cf7bc-847c-11e5-8edb-142664053b0f.png)

**Comment by ahafele** [comment]
sw-1299
