### ISSUE TITLE
Web archives in SW

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1102]

**Comment by jvine** [comment]
## WARC seed in results:
![warc result](https://cloud.githubusercontent.com/assets/6945691/11009508/519cf63c-848c-11e5-9eb0-ca3a67c7c2f3.png)

- date should be first-captured date [not in the MODS yet, afaict]
- the "special" info for this resource type is the original website URL, in 
`<note type="system details" displayLabel="Original site">http://naca.central.cranfield.ac.uk/</note>` stripped to show only the domain, and not linked

## WARC seed on record view:
![warc record](https://cloud.githubusercontent.com/assets/6945691/11009688/d8b398aa-848d-11e5-8e4b-98f5b24cb6dc.png)

- add "Original website" to the upper metadata section, as a link

**Comment by ndushay** [comment]
this will require indexing, yes?

**Comment by aeschylus** [comment]
Example WARC seed https://purl.stanford.edu/gb089bd2251

**Comment by ndushay** [comment]
indexing:   
- [ ] resource type
- [ ] want url (in a new field)

**Comment by ndushay** [comment]
UI:
- [ ] use resource type
- [ ] use new url type
- [ ] deal w WARC note

**Comment by jvine** [comment]
We have web archives in SW
