### ISSUE TITLE
Add IIIF logo and link to manifest to record view of image resources

### ISSUE THREAD

**Issue by snydman** [sul-dlss/SearchWorks#1106]
Supporting drag and drop

http://sul-reader-test.stanford.edu/drag_source/

**Comment by snydman** [comment]
@jvine @mejackreed needs a little bit of design on text and maybe badge

**Comment by mejackreed** [comment]
Who is the intended audience for this feature? It's definitely cool, its just unclear how this will be used by someone who isn't a DLSS staffer.

**Comment by snydman** [comment]
The current and future users of IIIF-compliant clients that support this feature. Currently this is Mirador and the Universal Viewer, and we hope as IIIF grows will include more.  In many cases these are researchers with interest in comparing SUL's image resources to image resources hosted elsewhere.  This is already being well used in the manuscript space, and Salim has been advocating for it for our map collections.  Currently Digital Bodleian has this implemented; Harvard has Mirador ready to launch as their default viewer, and several others are nearly there (National Gallery of Art, Wellcome Library).  

In addition, as founders of IIIF, this demonstrates our commitment but putting it into production at Stanford and gives the initiative visibility from one of its founding institutions.

**Comment by jvine** [comment]
Implemented is in the embed viewer for now.

![screen shot 2016-01-20 at 3 42 30 pm](https://cloud.githubusercontent.com/assets/6945691/12466879/7e71062c-bf8c-11e5-9300-82232ee5f5bd.png)
