### ISSUE TITLE
Add / remove stuff in hamburger menu

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1119]
- [x] add Course guides http://library.stanford.edu/guides/course 
- [x] add Suggest a purchase http://library.stanford.edu/ask/email/request_purchase
- [x] remove Print copy scan

![screen shot 2015-11-11 at 5 04 26 pm](https://cloud.githubusercontent.com/assets/6945691/11107849/53b53fd4-8896-11e5-90b3-bcfdc4565768.png)

**Comment by jkeck** [comment]
Closed by #1147
