### ISSUE TITLE
Users are not noticing the Find it link

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1132]
Solution
- make the link a button (because it opens a popup, doesn't go to a new page; and is more visible)
- place the link in front of the location name (more visible; highlights locations that have vs. don't have maps; won't conflict with Request button)
- make the location name 'live' - clickable and visible on hover (because in the click test, people actually clicked on the loc name)
- modify the "info" button colour (because it's ugly)
- possibly change name from "Find it" to "Map to", depending on IC feedback

Default:
![find-it default](https://cloud.githubusercontent.com/assets/6945691/11881663/f3575ab2-a4bc-11e5-86f0-e269ffd32d8c.png)
```
    background-color: #0098db;   /* $color-pantone-2925 */
    border-color: #007eb6; 
```

On hover/active:
![find-it hover](https://cloud.githubusercontent.com/assets/6945691/11881671/f814d4ee-a4bc-11e5-9d20-875911790907.png)

Click test result:
![findit clickmap](https://cloud.githubusercontent.com/assets/6945691/11881777/c4e2b66c-a4bd-11e5-83cd-b7aa69c2079a.png)

**Comment by aeschylus** [comment]
To me this looks more like a tag than a button. The click test seems to require we make the text clickable, but might we also make the button a bit larger and more conspicuously a button?

Also, in the spirit of "buttons being verbs", what about "Open Map".

**Comment by jvine** [comment]
It is an xs button with standard button hover behaviour. Larger button looks overwhelming in context. (The click test version looked even more like a tag.) There's some inertia around "Find it" in the sense that there are both public service staff and documents that refer to it. But I will circle back once more with the IC because why not.

**Comment by jvine** [comment]
IC confirms that they want to keep "Find it".

**Comment by aeschylus** [comment]
:+1:

**Comment by peetucket** [comment]
Note that the code currently has the location text within a library (e.g. "Stacks") going to a different spot than the "Find it" link.  It is often not linked at all because the logic is:

a. if its not an "external location" (currently only LANE-MED), the location text is not linked at all.  
 b. if it is an "external location" (== LANE-MED), link to a location at http://lmldb.stanford.edu appending the barcode and various other bits

Should this remain as is or we altering the logic of the location text link to match the find it link (e.g. for case (a) above perhaps?)

**Comment by jvine** [comment]
Nice catch, Peter. In real life, the Find it link only appears for items housed in Green; and the external link never applies to items housed in Green. That said, if it seems safer to just implement the first two bullets (make it a button, move it) that's fine too.

**Comment by peetucket** [comment]
Ahh, I see, if its an external location a different set of logic causes the link it button to vanish? (before the find it link is rendered, there is a check for a call number that is "stackable", whatever that means, which may be false for LANE-MED).  So...this means it should be perfectly safe to make both links the same when not LANE-MED (as written in this ticket), and leave things the way they were when LANE-MED.

**Comment by peetucket** [comment]
is there a specific color for the rollover-state that i should use (i.e. the darker version of #0098db)

**Comment by jvine** [comment]
Ugh. I just double-checked #0098db, and it does not have sufficient contrast at its size. So the base colour needs to be #007cbc, which has a contrast ratio of 4.56:1. From there, we should be using variables to generate the border and hover colours - I think it's +5% for the border, +15% for the hover/focus state. When I try that it comes out to this:

```
 {
  color: #ffffff;
  background-color: #007cbc;
  border-color: #006ba3;
}
:focus, :hover {
  color: #ffffff;
  background-color: #005a89;
  border-color: #001723;
}
```
