### ISSUE TITLE
index MODS into govdoc genre facet

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/SearchWorks#1143]
Specification to index MODS into govdoc genre facet:
\<mods:genre authority="marcgt"\>government publication\</mods:genre\>

For test records, Nicholas added this element to the Fugitive U.S. Agencies seed records (web archive records).

SW-1570

**Comment by ndushay** [comment]
This is certainly not in the genre field for any of the Fugitive U.S. agencies records I profiled.  A bunch of them did error out, tho ...

**Comment by ndushay** [comment]
@shelleydoljack  why am I not seeing the MODS genre element per above at the purl pages for this collection?

**Comment by ndushay** [comment]
compare  https://argo.stanford.edu/catalog/druid:dj477wk1667  with 
https://purl.stanford.edu/dj477wk1667.mods

**Comment by lmcglohon** [comment]
@shelleydoljack @ndushay I republished the collection and the data is now in the mods.

**Comment by ndushay** [comment]
well, phooey.   I can see that the purl MODS now has it, but profiler is now giving:

```
/opt/app/harvestdor/mods-profiling-indexer/shared/bundle/ruby/2.2.0/gems/harvestdor-indexer-2.3.1/lib/harvestdor/indexer.rb:148:in `solr': undefined method `to_hash' for nil:NilClass (NoMethodError)
	from /opt/app/harvestdor/mods-profiling-indexer/releases/20151203190115/lib/indexer.rb:46:in `solr_client'
	from /opt/app/harvestdor/mods-profiling-indexer/releases/20151203190115/lib/indexer.rb:75:in `harvest_and_index'
	from ./bin/indexer:71:in `block (2 levels) in <main>'
	from ./bin/indexer:50:in `time'
	from ./bin/indexer:70:in `block in <main>'
	from ./bin/indexer:65:in `each'
	from ./bin/indexer:65:in `<main>'
{:collection=>["fuller_us_agencies"], :nocommit=>false, :version=>false, :help=>false, :collection_given=>true}
```

ah well.

**Comment by ndushay** [comment]
Got the profiler going  (I had a typo).  See  https://sul-solr.stanford.edu/solr/mods_profiler/select?rows=0&facet.field=collection&facet.field=typeOfResource_sim&facet.limit=-1&facet.sort=index&q=%22government%20publication%22&facet.field=genre_sim&facet.field=genre_authority_sim
