### ISSUE TITLE
Broken display of 382

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1144]
This work was originally done in #268.

Example:  https://searchworks.stanford.edu/view/7620108

We show:
![screen shot 2016-01-15 at 10 15 01 am](https://cloud.githubusercontent.com/assets/6945691/12361087/def6f814-bb70-11e5-805e-2ff9d68faf7e.png)

382 has:

```
a| organ n| 2 v| 4 hands p| piano n| 2 v| 4 hands s| 2 2| lcmpt
```

Should display:  organ (2) (4 hands) or piano (2) (4 hands) (total=2)

**Comment by ndushay** [comment]
@jkeck  I think you completed this work?

**Comment by jkeck** [comment]
Ah yes, not sure why this didn't get closed.
