### ISSUE TITLE
Disentangle display type

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/SearchWorks#1146]
We need to remove the distinction between image and file in rendering items.

Collections will still need to know if they should render a filmstrip or a file list somehow.

**Comment by ndushay** [comment]
Collections (NEW):  displays filmstrip if majority of its children returned should behave like images  (so, of first 20 items, if 11 have images, we'll get a filmstrip;  if 9 have images, we'll get a file list)

Collections need to know
- collection type: digital collection
- druid
- marcxml or modsxml

Items need to know:
- item druid
- collection
- collection title
- thumbnail id (? - punt on this for now?)
- file ids (used for thumbnail, used for num images in filmstrip (has been problematic))
  * for image, manuscript or map, you get file ids 
  * for files, you also get file ids

Indexing changes:
- [ ] non-image-like files will NO LONGER GO into file ids.
- [ ] display_type field no longer needed by colls or items

Update to item release workflow (adding mods info to marc recs?):
- [ ] display type and file id are used here as well ...
