### ISSUE TITLE
Display XX call numbers for Hoover Archives collections

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1148]
In general, we replace call numbers with the pattern XX(1234.5) with "no call number". These are typically on-order items.

However, Hoover Archives has legit collection call numbers that begin with XX - e.g. XX066. 
https://searchworks.stanford.edu/view/4086148

We need to display these collection call numbers in order for the items to be requestable. 

These numbers should also be searchable in the call number index. XX066 gets no results.

**Comment by jvine** [comment]
SW-1583

**Comment by ndushay** [comment]
closed in favor of sul-dlss/solrmarc-sw#121  which is the actual work
