### ISSUE TITLE
Move all authors to Authors/Contributors section

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1161]
For MARC and MODS
- [x] move authors from the top metadata block to the Contributors section; maintain their current labels and relators etc.
- [x] rename the Contributors section "Authors/Contributors" (see [comment](https://github.com/sul-dlss/SearchWorks/issues/1161#issuecomment-176956800) about "Creators/Contributors" below.
- [x] for MARC only, move Responsibility from the Bibliographic information section to the top metadata block, as the first item in the `<dl>`

[clarification - i think the Responsibility field only happens in MARC]

**Comment by jkeck** [comment]
For MARC records does authors include the metadata labeled `Corporate Author` and `Meeting`?

**Comment by jvine** [comment]
Yes.

Sent from my iPhone

On Jan 28, 2016, at 9:31 PM, Jessie Keck <notifications@github.com<mailto:notifications@github.com>> wrote:


For MARC records does authors include the metadata labeled Corporate Author and Meeting?

-

**Comment by jvine** [comment]
Request from gryphon-search to change Authors/Contributors to Creators/Contributors. After that we're good to go.
