### ISSUE TITLE
CSS bug in library panel heading

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/SearchWorks#1171]
<img width="380" alt="screen shot 2016-02-01 at 9 56 20 pm" src="https://cloud.githubusercontent.com/assets/96776/12741128/b483e77e-c92e-11e5-8a44-bc6625762dcb.png">

**Comment by jvine** [comment]
```
.access-panel-heading.library-location-heading h3 {
    border-bottom: 1px dotted white;
    max-width: 95%;
    display: inline-block;
}
```
