### ISSUE TITLE
Show Location facet when Art Library selected

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1174]
- [ ] Create a whitelist of libraries that will show the Location facet. "Art & Architecture (Bowes)" is currently the only library, but others may follow.
- [ ] When the whitelisted library is selected in the Building facet, display the Location facet:
  - at the top of the facets list
  - open (same behaviour as Databases facet)

**Comment by ndushay** [comment]
JK:  slight blocker:   indexing engineering work is done, but code isn't deployed to production -- need the configurations in production solr index so Solr doesn't throw an error in production.

 @lmcglohon   were there solr config changes for this?

**Comment by ndushay** [comment]
currently only in  "resource" Solr index, not in production Solr index.   Can't easily push app code changes to production before the index is there.

**Comment by ndushay** [comment]
blocked by #1197
