### ISSUE TITLE
Display "extent" on record view for Roman Coins

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1180]
Example:  http://searchworks-test.stanford.edu/gsearch/view/nr278nn0626

Roman coins have physical description metadata like this:

```
<physicalDescription>
<digitalOrigin>reformatted digital</digitalOrigin>
<internetMediaType>image/jpeg</internetMediaType>
<extent>1 coin (3.62 grams)</extent>
<form authority="gmgpc" valueURI="http://id.loc.gov/vocabulary/graphicMaterials/tgm009630">Silver</form>
</physicalDescription>
```

Currently PURL shows the extent and form grouped under the label Format.

![screen shot 2016-02-03 at 2 10 45 pm](https://cloud.githubusercontent.com/assets/6945691/12798764/0f558b1a-ca80-11e5-949a-1668553f4964.png)

It's not clear where "Other" is coming from. [Update: I think this may be PURL trying to represent the pre-3.0 Format facet value.]

On the RESULTS view, SW shows the Extent (labelled by the Resource type facet value) - this is correct:
![screen shot 2016-02-03 at 2 13 46 pm](https://cloud.githubusercontent.com/assets/6945691/12798819/6b9a3984-ca80-11e5-8062-47e5c50ae203.png)

On the RECORD view, SearchWorks does not display physicalDescription content at all.

## What should happen

SearchWorks and PURL should show:
![screen shot 2016-02-03 at 2 18 21 pm](https://cloud.githubusercontent.com/assets/6945691/12798942/09c90cb6-ca81-11e5-8eda-0f49c5ebf393.png)

**Comment by jvine** [comment]
SW-1455

**Comment by ndushay** [comment]
JV:  displaying but not labelled correctly in PURL
JK:  SearchWorks app code to get the right labels displaying

**Comment by jkeck** [comment]
I was wrong, @jvine was right.  There is in fact changes to make in ModsDisplay. She is following up before we take action.  This will require (very minor) changes to the app code once we have released a new version of ModsDisplay.

**Comment by jkeck** [comment]
See sul-dlss/mods_display#25
