### ISSUE TITLE
Display MARC tag 351 in Contents/Summary section

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1194]
SW-1595

Display tag 351, in Contents/Summary section
Subfields $3 $a $b $c in the order they appear in the MARC (which seems to be $3 $c $a $b)
Ignore $6 and $8

No special punctuation; just a space between each subfield. Label for dipslay is "Organization & arrangement"

example record https://searchworks.stanford.edu/view/10604415

**Comment by jkeck** [comment]
Do we want to whitelist $3, $a, $b, and $c for display or should we display all subfields except $6 and $8?  (FWIW, $6 and $8 are always blacklisted for display along with $w, $0, $5, $?, and $=)

**Comment by jvine** [comment]
Display all except $6 and $8.
