### ISSUE TITLE
Fix whitespace on RSS Feed icon

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss/SearchWorks#1206]
![screen shot 2016-02-16 at 16 39 08](https://cloud.githubusercontent.com/assets/145874/13096164/e7ce53e6-d4cb-11e5-83c0-4121cbca6b0a.png)

There is not enough bottom margin to line it up with the "1117 results" text. Probably setting the `vertical-align` and `display` properties (to `middle` and `inline` should do it. Though it depends on the other styling. I haven't looked into it yet.

**Comment by jvine** [comment]
fixed in 3.2
