### ISSUE TITLE
New Symphony Locations that need a new SearchWorks text translation

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#1246]
We have two new Symphony Home Locations that need to be translated in SearchWorks:

ATCIRCDESK
- should display to the user as  "Ask at circulation desk"
- is circulating, so we need the green checkmark with "Available"
- standard request link functionality (though most of the items will have an item type with "NH-" prefix.  so we probably won't see request links.

STUDY-AIDS
- should display to the user as "Study aids"
- is noncirculating, so we need the yellow checkmark with "In-library use"

**Comment by saseestone** [comment]
@jkeck - any timetable on when these two location translations will go into production?  I've got user's asking....

Also - my permissions for github seem to let me create an issue, but I can't assign it to anyone.  Is that part of the problem?

**Comment by jkeck** [comment]
@saseestone I have been at a conference all week and unable to field any requests.  I'll try to address this soon and try to get it out at the beginning of next week at the latest.

FWIW, it is intentional that only developers assign the tickets in our GitHub repository.

**Comment by saseestone** [comment]
@jkeck - thanks for the info!  save travels!

**Comment by jvine** [comment]
Translations ok. :+1:
