### ISSUE TITLE
Add these locations to NONCIRC_LOCS list

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1251]
Not specific to Rumsey but can be bundled with that work.

ARTVAULT
ENGDISPLAY
FACULTY
LOCK-CHN
LOCK-JPN
LOCK-KOR
MM-ARTCAB
MM-BUSCAB
MM-DIZOCAB
MM-MATHCAB
NEWS-STKS
NEWSPAPERS
RAUB-COLL
RAUB-NUM
SAFETY
SAL-TEMP
TERM-COLL

**Comment by jkeck** [comment]
FWIW `SAFETY` was already in the `NONCIRC_LOCS` list.
