### ISSUE TITLE
Rename 'Request' button for mediated, on-site access libraries

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1275]
For Spec, Rumsey, and Hoover Archives, rename 'Request' to 'Request on-site access'

![on-site-access-button](https://cloud.githubusercontent.com/assets/6945691/19056181/82ca385a-897c-11e6-9ee3-4ad630819d72.png)

**Comment by jkeck** [comment]
@jvine this may cause some space issues on the record view: 
<img width="324" alt="11588840" src="https://cloud.githubusercontent.com/assets/96776/19457187/0a142412-947a-11e6-947f-2fb8853bd0b1.png">

Any thoughts on how we should handle that?

**Comment by jvine** [comment]
@jkeck Yeah, I saw that. The place names can be really long, and it seems best to just let the layout do what it does. Tried the button as 2 lines; tried a 2-column display, etc. - they all break under some circumstances, and in the end, the current default is the least icky.
