### ISSUE TITLE
use HoneyBadger instead of squash

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/SearchWorks#1276]

**Comment by drh-stanford** [comment]
We're using honeybadger now, but there's still Squash configuration settings in our settings.yml

**Comment by drh-stanford** [comment]
See https://github.com/sul-dlss/shared_configs/pull/299 https://github.com/sul-dlss/shared_configs/pull/300 https://github.com/sul-dlss/shared_configs/pull/301 https://github.com/sul-dlss/shared_configs/pull/302 https://github.com/sul-dlss/shared_configs/pull/303 https://github.com/sul-dlss/shared_configs/pull/304
