### ISSUE TITLE
new PAGE-RM location

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/SearchWorks#1291]
Create PAGE-RM location in SearchWorks.

This location will be assigned to items in SAL3 that are for "in-library use only" and will be pageable only back to RUMSEYMAP library.

Description probably "Request for use in David Rumsey Map Center" (JV's discretion)
Orange truck with "In-library use"

Items WILL be circulating, just within the library.  I believe this PAGE-RM is similar to other PAGE-*\* locations.  Screen shot of PAGE-MU items for comparison, I think should look like this:

<img width="390" alt="screen shot 2016-10-26 at 9 11 52 am" src="https://cloud.githubusercontent.com/assets/14914677/19734523/b4750140-9b5c-11e6-8e09-a8c81a0fb9b7.png">

**Comment by jkeck** [comment]
@jvine are you 🆗 with the location translation provided?

**Comment by jvine** [comment]
Yes. 👍 

(In case I wonder why later: The convention for items listed under Rumsey is "Request for use at Map Center"; but since these will appear under SAL3, I think the full library name is helpful.)
