### ISSUE TITLE
Update logo to new design

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/SearchWorks#1320]
[SW-1801](https://jirasul.stanford.edu/jira/browse/SW-1801)

**Comment by jvine** [comment]
New logos are here:
https://consul.stanford.edu/display/Logos/Home

SearchWorks should use #1 for the top white bar, and #5 for the footer.

(The website has SVG versions, but uses a different header logo, and the footer logo was not converted correctly. If someone knows how to convert EPS to SVG and keep the fonts consistent in all contexts, that would be great.)

**Comment by jvine** [comment]
Oops, mobile behaviour: 

hidden-xs - use logo#1
visible-xs - use logo#5.

![screen shot 2017-05-26 at 9 45 28 am](https://cloud.githubusercontent.com/assets/6945691/26504110/19390288-41f8-11e7-89c1-85095d0e8af3.png)

![screen shot 2017-05-26 at 9 45 08 am](https://cloud.githubusercontent.com/assets/6945691/26504103/15267892-41f8-11e7-98c1-22fe2e837a8a.png)

**Comment by mejackreed** [comment]
Might be helpful: https://github.com/sul-dlss/earthworks/pull/338

**Comment by jvine** [comment]
Replace sul-logo-small with logo#5 from the consul page.
