### ISSUE TITLE
"Role" should not be part of name link: 110 $e, 111 $j, 711 $j not working correctly

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/SearchWorks#1321]
Basic rule:
- for 100, 110, 700, 710, subfield e should be displayed but should not be part of the linked search.
- for 111, 711 subfield j should be displayed but should not be part of the linked search.

This is working for most cases, but still incorrect for these tags:

## 110 $e
https://searchworks.stanford.edu/view/10159310
Correct link should be:
[Ecuador. Procuraduría General del Estado,] author, issuing body.
(exclude author, issuing body)

https://searchworks.stanford.edu/view/9197584
[Augustinians. Prior General (1570-1581 : Guidelli),] author.
(exclude author)

## 111 $j
https://searchworks.stanford.edu/view/10165011
[Technical Workshop on Organic Agriculture (1st : 2010 : Ogbomoso, Nigeria)] creator.
(exclude creator)
 
## 711 $j 
https://searchworks.stanford.edu/view/9952016
[Biennial Forum of Government Auditors (19th : 2012 : Alexandria, Va.).] author.
(exclude author)

Special case: For 711 that includes $t (title), we need to suppress the $j from the search, but include it in the link text, because it falls between two elements (name + title) that are in the same search. We did this previously with 700 and 710, examples here:
700 $e when $t is present: 10168859, 9615329 
710 $e when $t is present: 9197584, 9685915

Lots of prior discussion here:
[SW-993](https://jirasul.stanford.edu/jira/browse/SW-993)

**Comment by drh-stanford** [comment]
Some notes re: 110 $e

There's an `author_corp_display` field in the Solr document that has the "author, issuing body" text inside it. The code appears to exclude the $e field already -- see https://github.com/sul-dlss/SearchWorks/blob/master/app/helpers/marc_helper.rb#L463

**Comment by drh-stanford** [comment]
@ahafele do we have a catkey example for a 711 that includes $t (title). I didn't see one in the JIRA ticket or above...

**Comment by ahafele** [comment]
@drh-stanford sure thing - 
https://searchworks.stanford.edu/view/11546775
https://searchworks.stanford.edu/view/92688
https://searchworks.stanford.edu/view/12075472

**Comment by drh-stanford** [comment]
@ahafele do we have an example catkey for 711 that has $e $t and $j?

**Comment by drh-stanford** [comment]
@ahafele I have a question re: 110$e. Should we omit them from the search and link text but display them at the end, like so? Or is this problematic? (From 10159310):

![screen shot 2017-06-07 at 1 09 26 pm](https://user-images.githubusercontent.com/1861171/26898999-9f3cd81c-4b82-11e7-98d4-70da26a38d3f.png)

**Comment by ahafele** [comment]
@drh-stanford yes, re:110$e. Looks good. 
Still trying to find examples of 711 that has $e $t and $j

**Comment by drh-stanford** [comment]
Note that this behavior is also happening in the search results:

![screen shot 2017-06-08 at 10 38 44 am](https://user-images.githubusercontent.com/1861171/26942388-b58088a8-4c36-11e7-8298-7a8071254c24.png)

**Comment by ahafele** [comment]
@drh-stanford we are not able to find any - 711 that has $e $t and $j . I can fake one temporarily if needed.

**Comment by jkeck** [comment]
We could fake one in our fixture data if need be, I think.

**Comment by drh-stanford** [comment]
@ahafele that's fine i'll just put one in my test fixtures just in case :)
