### ISSUE TITLE
Make "bound-with" links clearer

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1339]
We currently repeat the "bound with" note from the metadata section in the Availability display. This ticket proposes:

- *no change* to the metadata display
- 4 changes to the availability display

1. Suppress the individual barcodes in this section. If 999 subfield l is SEE-OTHER, do not display the item availability. 
`999 a| 315.69 .I851 F NO.9 SUB 1950 w| DEWEYPER c| 1 i| 8838463-15001 l| SEE-OTHER m| SAL3 r| Y s| Y t| STKS-PERI u| 9/28/2010 x| BW-CHILD z| TAX=8.25`
![screen shot 2017-06-08 at 2 26 51 pm](https://user-images.githubusercontent.com/6945691/26951585-8e4d6646-4c56-11e7-8fab-334f4fcbf038.png)

2. Change the content of the link from the ckey in subfield c to the complete content of subfield a. Discard subfield c. 
`590 a| No. 112, copy 1 bound with no. 106. c| 9715044 (parent record's ckey).`
currently displays
![screen shot 2017-06-08 at 2 27 41 pm](https://user-images.githubusercontent.com/6945691/26951623-b3418360-4c56-11e7-8bb4-a5770c589ac9.png)
instead should display
![screen shot 2017-06-08 at 2 29 38 pm](https://user-images.githubusercontent.com/6945691/26951687-edbcf308-4c56-11e7-8d1b-0214b4765edb.png)

3. Put each "bound with" note on a separate line - best markup is `<ul>`

4. Change the wording of the bold text above the bound with section.

Example records
https://searchworks.stanford.edu/view/8838463
https://searchworks.stanford.edu/view/9350725

## Before
![screen shot 2017-06-08 at 2 43 30 pm](https://user-images.githubusercontent.com/6945691/26952119-e6e50fb4-4c58-11e7-888e-a90426fa80c5.png)

## After
![bound with after](https://user-images.githubusercontent.com/6945691/26952540-bcc0f2c8-4c5a-11e7-834d-3c8b1e841a78.png)

**Comment by jvine** [comment]
Revised spec after review by gryph-search:

1.  Do NOT suppress the barcodes on the record view; but do one of the following, in order of preference:
  1 show a new status of "? See related" for all bound-with children
  2 suppress availability icon and text altogether
  3 show the "? Unknown" status 

2.  Note change to wording for the bound-with location text.

3.  In the search results view, suppress all the barcodes; replace with a link to the full record.

![bound-with-revised-spec-v2](https://user-images.githubusercontent.com/6945691/27108708-8f845078-5053-11e7-8383-0383b900b9a3.png)

![bound-with-revised-spec](https://user-images.githubusercontent.com/6945691/27108368-a0915e62-5051-11e7-8df8-88653cc2dc13.png)

![bound-with-revised-search-results](https://user-images.githubusercontent.com/6945691/27108370-a3b655a2-5051-11e7-8f3b-5aef89c58c22.png)

**Comment by jkeck** [comment]
There is a [`[WIP]` pull request](https://github.com/sul-dlss/SearchWorks/pull/1345) for this issue that still needs to implement the search results behavior.

We will most likely need to capture for the bound_with location in the search results partial and add the custom link/labeling.

**Comment by jvine** [comment]
Typo in results view:  "Some records are bound together" should be "Some items are bound together"

**Comment by jkeck** [comment]
Un-assigning myself as to not block anybody from continuing w/ this work.  Happy to pair on it, or will pick it back up when it makes sense.

**Comment by mejackreed** [comment]
I've rebased and pushed up the branch to the PR. I'm a little confused on the final piece of the search results, so a quick pair may be helpful.
