### ISSUE TITLE
Include more subfields in 730 related work linked search

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1340]
SW-1640
Example records
https://searchworks.stanford.edu/view/9375544 
https://searchworks.stanford.edu/view/8447575

730 "Related work" link currently includes $i $a
Link should include:  a d f k l m n o p r s t
and display but not link:  h i x 0 3 5 6 8

**Comment by drh-stanford** [comment]
### Before (9375544)

![screen shot 2017-06-09 at 11 26 35 am](https://user-images.githubusercontent.com/1861171/26989084-9483ae48-4d06-11e7-9642-6f65db8b12f7.png)

### Before (8447575)

![screen shot 2017-06-09 at 11 27 25 am](https://user-images.githubusercontent.com/1861171/26989109-ac2fccac-4d06-11e7-9cbc-4514f12d2e51.png)

**Comment by drh-stanford** [comment]
@jvine are the subfields, which are to be displayed but not linked, always at the end of the 730 field, or might they be in between or at the beginning?

**Comment by jvine** [comment]
Subfield $i will typically be at the beginning (as in the example records); the numbered subfields will typically be at the end; don't know for $h but my guess is it will be in between.

We have dealt with this elsewhere by including subfields in the link text that are not included in the linked search - see https://searchworks.stanford.edu/view/10168859 - for the 700 tag - we show "Holzer, David, Rabbi, author. Va'yosef Dovid.<https://searchworks.stanford.edu/catalog?q=%22Holzer%2C+David%2C+Rabbi%2C+Va%27yosef+Dovid.%22&search_field=author_title> Contains (work):" for the link text,  but "$e author" is not included in the search. (Also happens to be an example of $i appearing at the end of the tag.)

BTW, it turns out that tag 130 has the same problem as 730. If it can be rolled into this issue, great; if not, I'll create a new issue.



On Jun 9, 2017, at 11:33 AM, Darren Hardy <notifications@github.com<mailto:notifications@github.com>> wrote:


@jvine<https://github.com/jvine> are the subfields, which are to be displayed but not linked, always at the end of the 730 field, or might they be in between or at the beginning?

**Comment by drh-stanford** [comment]
For $0, $5, $8, we exclude those in general (in our `MarcField` class). Are they needed for 730 specifically?

**Comment by jvine** [comment]
Oh good catch. No, keep them excluded.


On Jun 9, 2017, at 3:41 PM, Darren Hardy <notifications@github.com<mailto:notifications@github.com>> wrote:


For $0, $5, $8, we exclude those in general (in our MarcField class). Are they needed for 730 specifically?

**Comment by drh-stanford** [comment]
I just want to verify my understanding of the Related Work content in the bibliographic information section. We put in fields as a related work, only when a field meets the following criteria:

1. 730, or
1. 700, 710, 711, and 720 fields that:
    1.  have a `$t` title, and 
    1. it's indicator2 is not "2"

Is that correct?

**Comment by jvine** [comment]
Yes, correct, confirmed by kteel in Metadata.

**Comment by drh-stanford** [comment]
Re: the 130 data, I think we should create a different ticket for that. The implementation is different than the 730 related work stuff.
