### ISSUE TITLE
Change label of MARC tag 555 

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1341]
https://searchworks.stanford.edu/view/352662

Currently: "Finding aid"

Change to:  "Cumulative index or finding aid"

**Comment by drh-stanford** [comment]
Is this ticket for only the "Bibliographic information" section of the metadata page? Or are there other places we want to change the label? For example, the "Collection details" box has that label (catkey 10157407):

![screen shot 2017-06-08 at 4 08 13 pm](https://user-images.githubusercontent.com/1861171/26954420-c2420250-4c64-11e7-9ef4-96daf77ffeb8.png)

**Comment by jvine** [comment]
Only in the Bibliographic info section, and only for the content of the 555 tag.
