### ISSUE TITLE
Hook up Shibboleth authentication

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/SearchWorks#1348]
The EDS gem will (most likely) require that we identify when a user can access article data.  This is most likely more than just "Has a SUNet ID" as the ability to access Stanford restricted content is a bit more restrictive than the ability to have a SUNet ID.

We need to determine:
1. What that level of access is for article search (apparently this is the same level of access that we require for accessing e-resources)?
1. Do we have the info available to us in our current SearchWorks webauth setup?
1. If we do not have the appropriate data available to us, what do we need to do?
    1. It's possible that we'll need to migrate to shibboleth instead of getting LDAP access as UIT may not be granting that any longer.

**Comment by jkeck** [comment]
https://docs.google.com/document/d/1HE89VyhQ_yOUv73c8WxLT6Am4vujLyyhChlG9zN4-tY/edit?usp=sharing

**Comment by jkeck** [comment]
I have a question out to systems/operations to answer #1.  Unfortunately nobody who knows the answer is working right now, so will have to wait until at least tomorrow.

**Comment by ssklar** [comment]
If I correctly understand what you're asking, there are two parts here:
1. Is this user affiliated with Stanford University?
2. Does this user's affiliation entitle them to access a thing?

The first question is handled by the ezproxy application itself; its configuration file contains a list of IP address ranges that are considered part of Stanford University.  (The journals almost exclusively use IP address as the deciding datapoint.)

The second question is handled by Shib.  We (well, "they", serving as the Shib IDP) have a list of workgroups that are entitled to access licensed content; those workgroups are returned to ezproxy in the "suAffiliation" attribute.

Did I understand what you were asking for?

**Comment by jkeck** [comment]
@ssklar yeah, I think that's what I need.  Eventually knowing what those workgroups/affiliation criteria is will be great as I believe we'll need it.

I'm hoping that we can avoid needing the IP check and can get away w/ login + workgroup/affiliation, but will have to follow up w/ stakeholders so that we all know the implications of either approach.

**Comment by ssklar** [comment]
@jkeck the list currently contains:

lane:proxy-access
sulair:proxy-access
stanford:faculty
stanford:faculty-affiliate
stanford:faculty-emeritus
stanford:faculty-onleave
stanford:faculty-otherteaching
stanford:faculty-retired
stanford:faculty-slac
stanford:staff
stanford:staff-academic
stanford:staff-casual
stanford:staff-emeritus
stanford:staff-onleave
stanford:staff-otherteaching
stanford:staff-student
stanford:staff-temporary
stanford:student
stanford:student-incoming
stanford:student-ndo
stanford:student-onleave
stanford:student-postdoc
stanford:affiliate-fellow
stanford:affiliate-sponsored
stanford:affiliate-visitscholarvs
stanford:affiliate-visitscholarvt
organization:sumc
gsb-apps:library-proxy-access

**Comment by drh-stanford** [comment]
See https://uit.stanford.edu/service/shibboleth and https://github.com/omniauth/omniauth

**Comment by drh-stanford** [comment]
Blocked by some pending devops work right now.

**Comment by drh-stanford** [comment]
Need to investigate whether we can implement WebAuth/Shibb ONLY if user is outside the blessed IP range

**Comment by jkeck** [comment]
I feel like this is complete.  I'll wait until the production rollout on 9/8 to close this issue.

**Comment by jkeck** [comment]
Shibboleth is in production as of Sept. 8 2017 and affiliation attribute integration is being handled in the article-search feature branch.
