### ISSUE TITLE
Select-by-letter for Databases is not working

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/SearchWorks#1359]
![screen shot 2017-06-15 at 9 50 41 am](https://user-images.githubusercontent.com/1861171/27192879-c91b22e4-51b1-11e7-8a81-c759d143f12f.png)

the select-by-letter thing for Databases isn't working for me -- see https://searchworks-stage.stanford.edu/?f%5Bformat_main_ssim%5D%5B%5D=Database&prefix=g&sort=title

**Comment by cbeer** [comment]
I hope #1360 will fix this.
