### ISSUE TITLE
use OkComputer for nagios monitoring

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/SearchWorks#1369]
It looks like the current prod puppet configuration does not use the OkComputer endpoints for status.

See https://github.com/sul-dlss/puppet/blob/production/hieradata/project/sw-webapp-prod.eyaml#L91-L94

Related to #1277

**Comment by cbeer** [comment]
Fixed in https://github.com/sul-dlss/puppet/commit/c6fbd0c3e26275d2be468b6977d39019f6add49c
