### ISSUE TITLE
Implement Aeon link for Hoover Library & Archives

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1372]
**Please record time spent working on this issue.** 

Both Hoover Library and Hoover Archives materials need location-level Request buttons for all materials. Allow for the possibility of renaming these Request buttons independently of each other. 

![screen shot 2017-06-16 at 4 17 00 pm](https://user-images.githubusercontent.com/6945691/27247631-43554820-52af-11e7-82a5-905774b309b4.png)

![screen shot 2017-06-16 at 4 15 43 pm](https://user-images.githubusercontent.com/6945691/27247616-28dec89a-52af-11e7-9179-fa99367a1fd3.png)

The buttons will link to Aeon via OpenURL. Structure is as follows:

- LIBRARY=HOOVER
  - https://hoover.aeon.atlas-sys.com/aeon.dll?Action=10&Form=20&Value=GenericRequestMonograph
- LIBRARY=HV-ARCHIVE
  - https://hoover.aeon.atlas-sys.com/aeon.dll?Action=10&Form=20&Value=GenericRequestManuscript

The following information should be appended to the URLs:

![hoover-aeon field mappings](https://user-images.githubusercontent.com/6945691/27247705-f565b8c4-52af-11e7-8845-9e7d522398b1.png)

Same info in text form:

**LIBRARY = HOOVER**
- ItemInfo5
  - record URL
- ReferenceNumber
  - catkey
- ItemTitle
  - 245 $a, $b, $n, $p
- ItemAuthor
  - 100 $a, $b, $c, $d, $q
  - 110 $a, $b, $c, $d
  - 111 $a, $c, $d
  - 130 $a, $d, $f, $n, $p
- ItemDate
  - 260 $c
  - 264 $c
- ItemPublisher
  - 260 $a, $b, 264$a, $b
- ItemPlace
  - 300 $a, $b, $c
- ItemEdition
  - 250 $a

**LIBRARY = HV-ARCHIVE**
- ItemInfo5
  - record URL
- ReferenceNumber
  - catkey
- ItemTitle
  - 245 $a, $p
- ItemAuthor
  - 100 $a, $b, $c, $d, $q
  - 110 $a, $b, $c, $d
  - 111 $a, $c, $d
- ItemInfo2
  - 506 $3, $a [Access restrictions]
- ItemInfo3
  - 540 $3, $a [Conditions]
- ItemDate
  - 245 $f
- ItemPlace
  - 300 $a, $f

**Comment by jkeck** [comment]
I am super concerned about the performance implications of having to do this much raw MARC parsing in search results for every single on of these links.

**Comment by jvine** [comment]
Agree. I think we have two alternative options:

1. We include the relevant info that is already in the results - title, author, date, place - in the same form they already exist. No additional parsing. This would be sufficient for the Library, but not the Archives (the access restrictions are important).

2. We only put the request button on the item detail page, and not in the results. In the results we could put a link to "See full record to request", similar to bound-with. This is acceptable to Hoover and would be a consistent experience for Library and Archives.

And even with #2, I wonder if it would be simpler to use the existing display text.

**Comment by jvine** [comment]
MVP:
- In the results view, add a link "See full record to request"
- In the record view, add a Request button for each location
- Request button creates an openURL request with the info listed above, using the closest-match existing display fields. 

![screen shot 2017-07-12 at 5 07 38 pm](https://user-images.githubusercontent.com/6945691/28145487-81438c46-6727-11e7-9555-528190680e98.png)

![screen shot 2017-07-12 at 5 11 23 pm](https://user-images.githubusercontent.com/6945691/28145488-868b66ce-6727-11e7-95ec-f64882a60a10.png)
