### ISSUE TITLE
Configure NewRelic for SW

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/SearchWorks#1377]
This has been setup in the past, we just need to investigate why we stopped reporting.

**Comment by drh-stanford** [comment]
The shared version of newrelic.yml is not being used and the current newrelic.yml in the config directory on sw-webapp-a does not have the API key (but shared does). Note that it's not checked into the `shared_configs` repo.

```
[blacklight@sw-webapp-a SearchWorks]$ ls -l current/config/newrelic.yml shared/config/newrelic.yml 
-rw-r--r-- 1 blacklight blacklight 9240 Jun 14 12:35 current/config/newrelic.yml
-rw-r--r-- 1 blacklight blacklight 1676 Oct 21  2015 shared/config/newrelic.yml
[blacklight@sw-webapp-a SearchWorks]$ fgrep NEW_RELIC_LICENSE_KEY current/config/newrelic.yml current/config/settings.yml current/config/settings/production.*
current/config/newrelic.yml:  license_key: <%= Settings.NEW_RELIC_LICENSE_KEY %>
current/config/settings.yml:NEW_RELIC_LICENSE_KEY: 'NEW_RELIC_KEY'
```

So, all we need to do is use the shared version of `newrelic.yml` and restart the server. The other thing we need to decide is whether to run it on just sw-webapp-a or all the nodes.

**Comment by drh-stanford** [comment]
I dug further and looked at our New Relic account and I'll put in a PR here and in shared_configs to enable New Relic in production. We have a `newrelic.yml` file checked into the codebase so we don't need a seperate one in shared/

**Comment by drh-stanford** [comment]
Here are the tasks needed to close this issue:

- [ ] Review #1382 for the `Settings`-based New Relic configuration
- [ ] Review https://github.com/sul-dlss/shared_configs/pull/306 to enable New Relic in production (non-bot machines)
- [ ] Stop puppet from using the unused `shared/config/newrelic.yml` https://github.com/sul-dlss/puppet/pull/2020
- [ ] Deploy to production
- [ ] Go to newrelic.com dashboard to see performance analytics
