### ISSUE TITLE
Add drop-down to switch between search endpoints

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/SearchWorks#1378]
Acceptance Criteria
- [x] Dropdown has 2 links: Catalog and Articles
- [x] Catalog link goes to home page
- [x] Articles link goes to new article landing page
- [x] Link in banner needs to reflect current context (i.e. articles when in article search)
- [x] Search box needs to search current context (i.e. articles when in article search)

Out of scope
* All link (will go to bento eventually)
* Links pass on current search context (in search form)

![screen shot 2017-06-20 at 11 22 25 am](https://user-images.githubusercontent.com/96776/27349015-cbbc3266-55aa-11e7-909c-ea8feec88170.png)

**Comment by jvine** [comment]
Markup:

```
<div id="search-dropdown">
    <button type="button" aria-expanded="false" [etc...]>
       <span class="sr-only">search</span> all
    </button>
   <ul class="dropdown-menu" role="menu">
        <li class="active">
           <a href="[searchurl]">
            all <span class="help-block">catalog, articles, website, and more in one search</span>
            </a></li>
        <li>
           <a href="[searchurl]">
            catalog <span class="help-block">books & media in the Stanford Libraries'collections</span>
            </a></li>
        <li>
           <a href="[searchurl]">
            articles <span class="help-block">journal articles, e-books, and other licensed e-resources</span>
            </a></li>
    </ul>
</div>
```
