### ISSUE TITLE
Create article search landing page

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/SearchWorks#1379]
Acceptance Criteria
* Has a 3 column layout with headers

Out of scope
* Facet in the first column

![screen shot 2017-06-20 at 11 29 41 am](https://user-images.githubusercontent.com/96776/27349357-c9c4d426-55ab-11e7-83be-1ef9eddc5ba9.png)

**Comment by drh-stanford** [comment]
@jvine should the "Help with SearchWorks" link read "Help with SearchWorks articles"? Or do you want it to link to the existing SearchWorks help page on library.stanford.edu?

**Comment by drh-stanford** [comment]
@jvine I have a PR with a screenshot ready for your review -- https://github.com/sul-dlss/SearchWorks/pull/1384
