### ISSUE TITLE
Start migrating code from the EDS example app

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/SearchWorks#1380]
This may be better off in a gem/engine, but for now, we will migrate the code into the SearchWorks codebase to be accessed by the article search code/functionality.

- [ebsco/eds_blacklight_search_app](https://github.com/ebsco/eds_blacklight_search_app)
- https://github.com/ebsco/edsapi-ruby

- [x] Migrate `Eds::Repository` and `Eds::SearchService`
- [x] Add blacklight configuration to ArticleController
- [x] Migrate `index` action
- [x] Migrate `show` action
- [x] Fix broken interaction between /catalog and /article re: `url_for_document` helper method
- [x] Finish pending specs
- [ ] Migrate paging support (or maybe put in a different ticket?)

**Comment by jkeck** [comment]
If we can get a query executed and returning results, that'll meet our stretch goal for this sprint! 🌈 🦄 🎊

**Comment by drh-stanford** [comment]
I created a small very simple example in the `1380-eds-code` branch that uses a bit of the EDS code to execute an article search and renders the title/author in a hardcoded view. To run it you need to set the EDS_* parameters in your settings/development.local.yml -- I'll put the details in slack.

**Comment by drh-stanford** [comment]
I've updated the branch to use the Blacklight partials. So, I have a simple, first-page-only, search and show working ok. I think the next step is to flesh out the specs at the EDS integration points.

<img width="877" alt="screen shot 2017-06-22 at 1 49 39 pm" src="https://user-images.githubusercontent.com/1861171/27455315-c19e2f66-5751-11e7-8bf8-6683a7fcef53.png">
<img width="1050" alt="screen shot 2017-06-22 at 1 49 53 pm" src="https://user-images.githubusercontent.com/1861171/27455314-c19d62ca-5751-11e7-8ec1-9d16a5937fc0.png">

**Comment by drh-stanford** [comment]
I've added several specs but still need to debug why `ArticleHelper.url_for_document` is being used by `CatalogController`

**Comment by jkeck** [comment]
@drh-stanford I believe those helpers are global.  All helpers are loaded in all contexts. 

What you may want to do is add a `url_for_document` method to the `ArticlesController` (may need to use `helper_method :url_for_document` too) if you want it only to affect under the controller context.

**Comment by drh-stanford** [comment]
@jkeck it looks like you can configure the route within the blacklight_config -- I'll try to work with that -- see https://github.com/projectblacklight/blacklight/blob/master/lib/blacklight/search_state.rb#L44-L58

**Comment by drh-stanford** [comment]
I put in PR #1395 for this. I suggest we break out some new tickets, including:

- Search results pagination
- Search results faceting
- Mocking EDS API results for our specs
- Investigating whether we want this EDS integration code put into a gem/engine
