### ISSUE TITLE
Banner modifications 

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1396]
Note that this affects all of SearchWorks, not just Article search.

Before
![screen shot 2017-06-23 at 4 59 42 pm](https://user-images.githubusercontent.com/6945691/27503854-6b9fb320-5835-11e7-9222-4eb92b38860a.png)

After
![screen shot 2017-06-23 at 4 56 05 pm](https://user-images.githubusercontent.com/6945691/27503913-7348624c-5836-11e7-9c27-264a80ce386b.png)

### make the red banner 100px high
- [x] vertically center the SearchWorks logo, catalog/article selector, and search box
- [x] change the catalog/article font to the default (open sans, light)

### add grey navbar below the red banner
- [x] navbar is 35px high
- [x] background color is #857e74
- [x] move `box-shadow: 0 4px 8px -2px rgba(0,0,0,0.2)` from `#search-navbar-container` to the grey navbar

### move the #searchbar-topnav-menu menu from the white topnav to the left side of the grey navbar
- [x] label the menu "Library services"
- [x] remove the sr-only text

### move the advanced/browse/selections options from the red banner to the right side of the grey navbar
- [x] their collapse behaviour moves down here as well
- [x] remove their icons
- [x] menu text is:
```
color: #fff;
font-size: 22px;
font-size: 1.375rem;
font-weight: 100;
line-height: 35px;
padding: 0 24px;
```

[pulled mobile stuff into another ticket]

**Comment by drh-stanford** [comment]
re: the pulldown for catalog/article. is the placement of the pulldown ok here? what about the colors?

![screen shot 2017-06-27 at 9 59 12 am](https://user-images.githubusercontent.com/1861171/27600011-654cc2f0-5b1f-11e7-80b3-a2fcec823f69.png)

**Comment by drh-stanford** [comment]
re: the gray bar. what color should the nav highlight be? the default is a lighter gray, like so:

![screen shot 2017-06-27 at 10 10 27 am](https://user-images.githubusercontent.com/1861171/27600480-e69feaa2-5b20-11e7-8969-642742b23f59.png)

**Comment by jvine** [comment]
grey nav:
- focus = outline
<img width="172" alt="screen shot 2017-06-27 at 10 31 05 am" src="https://user-images.githubusercontent.com/6945691/27601367-f91234c6-5b23-11e7-91ac-6ac0ba671425.png">

- hover = underline (background & text colours don't change)
<img width="165" alt="screen shot 2017-06-27 at 10 30 26 am" src="https://user-images.githubusercontent.com/6945691/27601392-0e87549e-5b24-11e7-98e7-16a9951f7922.png">

**Comment by jvine** [comment]
pulldown:
- the top of the pulldown should be flush with the underline below "articles"
- the background highlight colour should be #faf8d2
- font colour of the selected item should be the default body text colour (which I think is black)
- font size of the words "article" and "catalog" shd be 22px

**Comment by drh-stanford** [comment]
@jvine Should we remove "Course reserves" from the catalog home page, or leave it there?

![screen shot 2017-06-27 at 12 20 40 pm](https://user-images.githubusercontent.com/1861171/27605943-13f03932-5b33-11e7-804e-b988e8879032.png)

**Comment by jvine** [comment]
Leave it.

**Comment by drh-stanford** [comment]
@jvine the current bg color for the Library Services menu is cardinal red with 0.9 alpha. is that correct?

![screen shot 2017-06-27 at 1 38 35 pm](https://user-images.githubusercontent.com/1861171/27608902-f92e9bec-5b3d-11e7-8ea7-b1f8bad87f2a.png)

**Comment by drh-stanford** [comment]
@jvine can you please take a look at this screencast to review? i think i have most everything in there, except the responsiveness doesn't work yet. The branch is called `1396-banner` if you want to run it locally.

![banner mov](https://user-images.githubusercontent.com/1861171/27613808-9217a5a6-5b52-11e7-9748-73fc2988d65f.gif)

**Comment by jvine** [comment]
Looks really close, @drh-stanford. Details:

- "Advanced"  ->  "Advanced search"
- font size of the words "article" and "catalog" (in the dropdown) shd be 22px; font-weight: 100;
- there's some kind of white background flash on Library services one of the times you click to close it - can't tell if it's really there or an anomaly
- can't evaluate the tab order (and therefore the focus state) and am not set up to run locally

**Comment by drh-stanford** [comment]
Ok, I fixed the first two, but the second two aren't working so I'll need to work on those. The tab order works but the focus isn't working on the two pulldowns (Library services and Selections).
