### ISSUE TITLE
Add Options facet to results view

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1413]
- add as first facet in the results view
- the default setting for these options should be "on" (I believe this is set by the admin) - so they should also show in the search breadcrumb by default
- it may not be possible to show counts for these facets (default UI does not)

![screen shot 2017-06-30 at 11 48 03 am](https://user-images.githubusercontent.com/6945691/27749828-0f8d6b40-5d8a-11e7-80ae-ff0b3f219a3e.png)

**Comment by jkeck** [comment]
I believe this starts the conversation around options that are settable via the admin UI and how the affect SearchWorks behaviors.

I don't believe that the API is intended to honor the admin option by default (at least that's what I gather from poking at the data w/ this facet enabled).  They instead surface those admin options from their API for the implementing library to decide to take action on or not.

There was some conversation on our call this week about having the gem (which already fetches and caches this information) act on this information.  This would allow the filters to be applied for us, however we would still need a way to know that these facets were set in-order to provide the correct breadcrumbs in the UI.  Either way, the implementation of this will probably need some more thought.

@jvine: Would it be worth pushing up just the facet (as shown below) and breaking out the part about acting on the admin options to a separate ticket (allowing us to enumerate more things we'll want to act on so we don't paint ourselves in a corner)?

![options-facet](https://user-images.githubusercontent.com/96776/27755643-ca1e7254-5da5-11e7-8d2b-c815e6ca3545.gif)

**Comment by jvine** [comment]
@jkeck Yes, we can push up the facet as shown, but we also need clarity on what those 3 options mean (because it clearly doesn't match my understanding) and whether we can re-word them once we know what they mean. I can make a separate ticket for that as well.
