### ISSUE TITLE
Break metadata into sections on the record view page

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1414]
Goal is to break metadata into predictable sections that can be easily navigated to. (Will make separate ticket for jump menu.)

- [x] remove the duplicate title from the metadata list
- [x] break multiple values into separate lines (multiple `<dd>`s per `<dt>`)
- [x] with the exception of the top section (authors first) the order of the information in each section is not super important
- [x] headings are `<h2>`

Top section (no visible heading)
- [x] authors
- [x] source info (journal title, publisher etc.)
- [x] date
- [x] language

Abstract/Summary
- [x] abstract
- [ ] summary
- [ ] description

Subjects
- [x] subjects
- [x] geographic subjects
- [x] author keywords (no data as yet)
- [ ] descriptors (here's an example record: https://stanford.idm.oclc.org/login?url=http://search.ebscohost.com/login.aspx?direct=true&db=agr&AN=IND605263032&site=eds-live)
- [ ] categories (eample: https://stanford.idm.oclc.org/login?url=http://search.ebscohost.com/login.aspx?direct=true&db=nlebk&AN=1491977&site=eds-live)

Details
- [x] everything else
- [x] note that Database and Format have been moved down to this section from the top

### Before
![screen shot 2017-06-29 at 10 34 44 am](https://user-images.githubusercontent.com/6945691/27703303-c0301d8c-5cbb-11e7-873b-f088c7266067.png)

### After
![screen shot 2017-06-29 at 11 03 04 am](https://user-images.githubusercontent.com/6945691/27703310-c66787b2-5cbb-11e7-89f1-6fed85a7e561.png)

**Comment by drh-stanford** [comment]
@jvine a few questions:

- should the title have the year at the end like it does in the search results?
- do we need to singularize the multivalued field labels (i.e., "Subject" vs. "Subjects") if there's only 1 value?
- do you have an example record for the "Author Keywords"?

**Comment by jvine** [comment]
@drh-stanford 
- no
- heh, in catalog we have the opposite problem (singular labels regardless of number of values). not a priority for this task.
- it appears we're not getting author-provided keywords yet - see slack discussion - here's a sample record that contains them:

https://sw-webapp-sandbox-f.stanford.edu/article/bah__123730534

https://stanford.idm.oclc.org/login?url=http://search.ebscohost.com/login.aspx?direct=true&db=bth&AN=123730534&site=eds-live

**Comment by drh-stanford** [comment]
@jvine Here's what I have currently configured for each section:

```ruby
      'Summary' => {
        eds_authors: 'Authors',
        eds_author_affiliations: 'Author Affiliations',
        eds_source_title: 'Journal',
        eds_publication_date: 'Publication Date',
        eds_languages: 'Language'
      },
      'Abstract' => {
        eds_abstract: 'Abstract',
        eds_notes: 'Notes'
      },
      'Subjects' => {
        eds_subjects: 'Subjects',
        eds_subjects_geographic: 'Geography',
        eds_subjects_person: 'Person Subjects',
        eds_author_supplied_keywords: 'Author Supplied Keywords'
      },
      'Details' => {
        eds_publication_type: 'Format',
        eds_document_doi: 'DOI',
        eds_database_name: 'Database',
        eds_composed_title: 'Composed Title',
        eds_volume: 'Volume',
        eds_series: 'Series',
        eds_issue: 'Issue',
        eds_page_start: 'Page Start',
        eds_page_count: 'Page Count',
        eds_isbns: 'ISBN',
        eds_issns: 'ISSN',
        eds_publication_info: 'Published',
        eds_document_oclc: 'OCLC',
        eds_document_type: 'Document Type',
        eds_other_titles: 'Other Titles',
        eds_physical_description: 'Physical Description'
      }
    }
```

and an example rendering -- note records do not have all the metadata fields -- in fact, I'm having a hard time finding examples in the wild that have some of these fields...

![screen shot 2017-07-06 at 11 46 06 am](https://user-images.githubusercontent.com/1861171/27927574-1571263a-6241-11e7-81ad-9fa8a6a18687.png)
