### ISSUE TITLE
Add record navigation and tools to the top of the record view

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1417]
All behaviour on this toolbar should be the same as SW catalog. Any behaviour and styling changes here are intended to affect catalog as well.

- if there is an active search result, show the left-side nav controls
![screen shot 2017-06-29 at 12 36 10 pm](https://user-images.githubusercontent.com/6945691/27706915-4321c9aa-5cc8-11e7-8ff0-a4a43ea935c4.png)

- if no search result, show only the right-side tools
![screen shot 2017-06-29 at 12 38 31 pm](https://user-images.githubusercontent.com/6945691/27706954-713e5092-5cc8-11e7-9628-3198ecf72eca.png)

- if it's the first record in the result, hide the "previous" control (same for "next" on last record)
![screen shot 2017-06-29 at 12 40 43 pm](https://user-images.githubusercontent.com/6945691/27706994-980d95d4-5cc8-11e7-8e03-b65cba8e6d4b.png)

- "Cite" should be present only if EDS can provide a formatted citation

## Styling
Heads-up: This is going to be tweaky, as there is some inconsistency and hacked styling in the existing controls. Note that the results nav/toolbar is intended to have the same styling, as there are some shared settings. 

- background color:  #797268
- drop shadow: same as grey navbar
- border: 0
- text color: white
- font size: 15px

- hover same as grey navbar
![screen shot 2017-06-29 at 12 52 22 pm](https://user-images.githubusercontent.com/6945691/27707617-cb23392c-5cca-11e7-97e6-3547cefaf4d9.png)

- focus same as grey navbar
![screen shot 2017-06-29 at 12 58 28 pm](https://user-images.githubusercontent.com/6945691/27707638-ded75d54-5cca-11e7-9b70-86aba5400ef3.png)

**Comment by drh-stanford** [comment]
@jvine I suggest that we break out the bookmarks (Select tool) from this into another ticket as it's complicated by the fact that we have both Catalog and Article bookmarks to manage. Also, the cite tool is unlikely as the EDS API does not provide formatted citations at this time (though they say it's a desired feature in the future). So that would leave this ticket focused on the record navigation and the styling. How does that sound?

**Comment by jvine** [comment]
Agree on splitting Select into another ticket. Agree on suppressing Cite. But:

- the styling changes are meant to affect both catalog and articles, so there needs to be styling around the catalog versions of these tools, and
- are we ready to do anything with Send to yet? If not, that can also be another ticket.

**Comment by jkeck** [comment]
I think we can be ready to work on various `Sent to` options (as separate tickets).

**Comment by drh-stanford** [comment]
@jvine how does this look for the styling? i haven't found what's causing that light grey line under the bar, nor why the hover line is so thin.

![screen shot 2017-07-07 at 11 01 41 am](https://user-images.githubusercontent.com/1861171/27970600-4d267576-6304-11e7-83eb-9ab9c4bb4221.png)

**Comment by jvine** [comment]
@drh-stanford Sorry for insufficient spec here, I didn't think this ticket was looking at the dropdowns at all. Formatting for the dropdown menu should be as it was originally - see #1449 for image.

The light grey line is a 3px border attached to .record-toolbar.sul-toolbar with !important. 

The hover line is thin because it's using text-decoration: underline - if you replace that with a 3px white bottom border, it will give the right thickness. Spacing from the text may need to be adjusted, but we may want to look at that more globally as a later task.

**Comment by drh-stanford** [comment]
@jvine is the 35px 40px 35px in the red font in the screenshots supposed to be used -- i.e., set the margins to 35px and the height of the bar to 40px?

**Comment by jvine** [comment]
@drh-stanford yes - wherever the margin is set, the resulting space above and below should be 35px and the height of the bar 40px.

**Comment by drh-stanford** [comment]
@jvine Here's the styling update for search results page and show page for SW catalog:

![screen shot 2017-07-07 at 1 39 11 pm](https://user-images.githubusercontent.com/1861171/27976047-b59b0706-6319-11e7-8dc8-6590dde546de.png)
![screen shot 2017-07-07 at 1 38 45 pm](https://user-images.githubusercontent.com/1861171/27976046-b59a406e-6319-11e7-9cf5-55f6ccf3db4c.png)

The vertical alignment of the elements is all from padding AFAIK so I'm still working on cleaning that up.

**Comment by jvine** [comment]
@drh-stanford looks close, dropdown is good. If it's not too late, you might want to set aside the vertical alignment, as there may be a global font-size change in the future that will mess with it; and I will be doing a detailed review at that point. Up to you.

**Comment by drh-stanford** [comment]
@jvine ok, thanks! i'm going to move onto the blacklight next/prev implementation -- it executes a search to find the prev/next documents so i need to map that into the EDS API as `previous_and_next_document_params` is Solr specific -- at least that's what it looks like from digging around a bit.

**Comment by drh-stanford** [comment]
@jvine i have the margins set to 35px for the show page:

![screen shot 2017-07-10 at 10 13 07 am](https://user-images.githubusercontent.com/1861171/28030387-73924c48-6558-11e7-92a9-c89ab4872415.png)

but should I have the same margins on the index page? 

![screen shot 2017-07-10 at 10 13 27 am](https://user-images.githubusercontent.com/1861171/28030389-751b5668-6558-11e7-9327-db2f3b609ad9.png)

**Comment by jvine** [comment]
@drh-stanford - no, on the index page the space between the header and toolbar should match the left column. I think if you set the toolbar top margin to 0, the div above it (that contains the h2) should provide the correct spacing.
