### ISSUE TITLE
Add field targets (title, author, subject, etc.) to search box 

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1419]
Add all available field targets to the dropdown for the article search box. "All fields" remains the default.

![screen shot 2017-06-29 at 1 59 48 pm](https://user-images.githubusercontent.com/6945691/27710071-404e87da-5cd3-11e7-9270-d03e76f1bbe2.png)

The fields listed correspond to these fields in EDS advanced search (the codes are what need to be included in the search):
![screen shot 2017-06-29 at 1 50 21 pm](https://user-images.githubusercontent.com/6945691/27710107-64c6eac6-5cd3-11e7-8ea2-4d08f65ac6bf.png)

**Comment by drh-stanford** [comment]
TX, AU, TI, and SU are working, but the rest are blocked pending https://github.com/ebsco/edsapi-ruby/issues/40

**Comment by drh-stanford** [comment]
The latest release of the EDA API handles all the fielded searches we want. The PR is updated to include that.
