### ISSUE TITLE
Style results nav/toolbar

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1423]
For the results view:

![screen shot 2017-06-29 at 2 48 00 pm](https://user-images.githubusercontent.com/6945691/27712060-251a4f6a-5cda-11e7-8640-22ce3cf2c726.png)

**Comment by drh-stanford** [comment]
Blocked by PR #1457 which has some styling modifications already.

**Comment by drh-stanford** [comment]
The Previous button is implemented differently than the show page, so I'll need to dig into that a bit to hide on the first page of results.
