### ISSUE TITLE
EBSCO::EDS::BadRequest: Max Record Retrieval Exceeded

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/SearchWorks#1426]
We're still seeing problems with paging. If you go beyond the 250th hit, you'll get this exception. You have to go to a page that _starts_ with the 251 or later hit to see the exception. For example, if you have per-page set to 100, visit page 1, then 2,  then 3, and then on page 4 you'll get an exception.

**Comment by drh-stanford** [comment]
Eric is checking on this as a known problem with the EDS API.

**Comment by efrierson** [comment]
EBSCO Service Issue #161161.  

Update (8/18): This was diagnosed as a defect July 5th.  Triaged.  Problem identified as a issue with how sessions are passed between different data centers.  Fix underway.  Will update as progress is made.

**Comment by drh-stanford** [comment]
Also see https://github.com/ebsco/edsapi-ruby/issues/47 and https://github.com/ebsco/edsapi-ruby/issues/10

**Comment by bmckinney** [comment]
Just pushed a new gem (0.3.7.pre) to address this.

In addition, please add the following:

export EDS_HOSTS=eds-api-a.ebscohost.com,eds-api-b.ebscohost.com,eds-api.ebscohost.com

**Comment by drh-stanford** [comment]
is it possible to get put the `EDS_HOSTS` as a parameter to the session call? We pass all of our configuration information in via that method -- see https://github.com/sul-dlss/SearchWorks/blob/article-search/app/models/eds/repository.rb#L38-L52

I'm worried that when Rails boots to load the classes that your classes will read the ENV variables for class variables before we can initialize them (we use Rails initializers).

**Comment by drh-stanford** [comment]
it looks like we can use `:api_hosts_list` -- see https://github.com/ebsco/edsapi-ruby/blob/9a9b03506d7b71c9259802647904fe08348a2b78/lib/ebsco/eds/session.rb#L134

**Comment by drh-stanford** [comment]
The 0.3.7.pre version seems to address the problem but note that the query takes longer as it executes a "jump to page" fallback on error.

```
CALLER OPTIONS: {:guest=>false, :session_token=>"b611448d-117b-4270-81a2-e2ff31e3f8b9.heTdHOziLYqlvs05YkHPmw4XcuoAs9gQnSYvE8Hz4bQ=", :caller=>"bl-search", :user=>"stanford", :pass=>"trial", :profile=>"edsapi", :use_cache=>true, :eds_cache_dir=>"/tmp", :timeout=>15, :open_timeout=>5, :api_hosts_list=>["eds-api-a.ebscohost.com", "eds-api-b.ebscohost.com", "eds-api.ebscohost.com"], :debug=>true, :log=>"/Users/drh/workspace/SearchWorks/log/faraday.log"}
AUTH TOKEN: "ACU5u06l1hssZ0C-dOcMhsAYB3xj4lmoUVh7IkN1c3RvbWVySWQiOiJzNDM5Mjc5OCIsIkdyb3VwSWQiOiJ0cmlhbCJ9"
SESSION TOKEN: "b611448d-117b-4270-81a2-e2ff31e3f8b9.heTdHOziLYqlvs05YkHPmw4XcuoAs9gQnSYvE8Hz4bQ="
138 ERROR =====================================================================
JUMP PAGES: [2, 4, 6, 8]
JUMP ACTION: ["GoToPage(2)"]
JUMP ATTEMPT: 2
JUMP ACTION: ["GoToPage(4)"]
JUMP ATTEMPT: 2
JUMP ACTION: ["GoToPage(6)"]
JUMP ATTEMPT: 2
JUMP ACTION: ["GoToPage(8)"]
JUMP ATTEMPT: 2
EDS search (8299.5ms)
```
