### ISSUE TITLE
Broken PDF Full Text links in article search

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/SearchWorks#1427]
Some "PDF Full Text" links are broken -- their href is just "`detail`". We're in guest mode so it might be related to restriction, but if so, we shouldn't show the link, right?

Example: http://localhost:3000/article/aph__118425842

**Comment by drh-stanford** [comment]
From Eric: The direct link to the PDF will be in the RETRIEVE method in that same spot.  We only provide it in the DETAIL record because it is a time bombed, direct access link.  You should only show it 1) when the user has been authenticated and 2) the moment they request it (so the link doesn't sit and get stale on the browser).

**Comment by bmckinney** [comment]
Patrons will need to login to view: https://github.com/ebsco/eds_blacklight_search_app/blob/656774cc2f3ba6b4a4a0273bcd1438609c000ac7/app/helpers/application_helper.rb#L14

![screen shot 2017-07-05 at 4 10 55 pm](https://user-images.githubusercontent.com/509381/27883231-d6d1d30a-619d-11e7-9a97-78d7f4611d56.png)

**Comment by jvine** [comment]
Resolved. PDF link gives a message to login.
