### ISSUE TITLE
Add abstract to full/default results view

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1436]
Add Abstract text after the Subjects in the results view - full/default view only. This will explode the results size until we get the accordion collapse behaviour in place. 

![screen shot 2017-06-30 at 12 55 34 pm](https://user-images.githubusercontent.com/6945691/27751913-8b1201a0-5d93-11e7-849b-4d8794c526ec.png)

**Comment by drh-stanford** [comment]
Duplicate of #1483.
