### ISSUE TITLE
Add date facet to results view

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1437]
- add Date as the second facet in the facets column, below Options. Default facet behaviour.

**Comment by drh-stanford** [comment]
The default facet behavior from EDS on the Date facet looks like this:

![screen shot 2017-07-14 at 2 05 02 pm](https://user-images.githubusercontent.com/1861171/28230888-7aaaba9a-689d-11e7-9f45-e84344e4f5f1.png)

**Comment by jvine** [comment]
@drh-stanford Yup. We will need to change it but just making it present is enough for now.

**Comment by jkeck** [comment]
@drh-stanford is there any indication that they've added an additional facet that could be used?

**Comment by drh-stanford** [comment]
I didn't see any. The new search limiter stuff doesn't look like it'll handle a date query (it just does `FieldCode:y`) -- see https://github.com/ebsco/edsapi-ruby/blob/master/lib/ebsco/eds/options.rb#L121-L132
