### ISSUE TITLE
Add show/hide (accordion) behaviour to search result

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1445]
Nice outlier search result: https://sw-webapp-sandbox-f.stanford.edu/article?utf8=%E2%9C%93&search_field=search&q=Spring+2006+trade+paperbacks

**Comment by jvine** [comment]
Apply to both Subjects and Abstract.  Use the same more/less technique as in the catalog masthead:  https://searchworks.stanford.edu/catalog?f%5Bcollection%5D%5B%5D=11838748

with these changes:

- the `<a>` would be better as a `<button>` styled as a link
- the default-visible div should be 2 lines of text instead of 3. You should be able size it to 2x the default line height (so about 2.85em).

![screen shot 2017-07-24 at 6 17 41 pm](https://user-images.githubusercontent.com/6945691/28551398-9cc5f62e-709c-11e7-8031-8672f9eaa324.png)

**Comment by jkeck** [comment]
@jvine a few questions:

Can we split the `button` vs `a` issue into a separate ticket?  This comes from an external library (that I happened to write), and this kind of change would need to take place there, and then we would need to update to that.

Also, should we use `more...`/`less...` (w/ the ellipsis) in other places where we're using the same truncation library?  Currently it's using the default w/o the ellipses.

If you would like, take a look at the screenshot on the PR and let me know if it looks okay.

**Comment by jvine** [comment]
> Can we split the button vs a issue into a separate ticket? 

Yes. 

> Also, should we use more.../less... (w/ the ellipsis)

I think not - it might not suit every case. I only use it because it makes the mouse target a bit bigger, but we could do that with css as well (later).

> screenshot on the PR

This is fine. 👍
