### ISSUE TITLE
Selecting `Full Text` from Options facet throws an error

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/SearchWorks#1463]
See ebsco/edsapi-ruby#38

**Comment by jvine** [comment]
From a previous email conversation with Eric where I asked about the meaning of the three option values...

> Eric:
> Stanford Has It = Available in Library Collection (just relabeled during our trial for a demonstration of native UI’s customization options)
Without any print holdings in EDS, Available in Library Collection == Full Text.  I can disable one or the other so you don’t double up in SearchWorks (which is what I did for the native UI demo).  This is done in EBSCOadmin, in the Searching tab, in Limiters.  Let me know if it’s okay to kill one.  You can also re-label it from EBSCOadmin.  Do you have a preference for the label for the one that remains?
> 
> JV: Ooh, yes please -
> kill "Full Text"
rename "Available in Library Collection" to "Stanford has it"
change "Peer Reviewed" to sentence case
> 
> Eric:
> Alright, changed – **should reflect next time the app refreshes its INFO method, I believe.**  That may be daily, so it might be tomorrow before you see it.


(But this was 7/6, so.)

**Comment by jkeck** [comment]
Looking over the gem code, it appears that this is [currently hard-coded](https://github.com/ebsco/edsapi-ruby/blob/a809c897f7799a90a4069a433f14b335f9c6546c/lib/ebsco/eds/results.rb#L236-L249).  The [`available_limiters`](https://github.com/ebsco/edsapi-ruby/blob/a809c897f7799a90a4069a433f14b335f9c6546c/lib/ebsco/eds/info.rb#L82-L88) are injected, however they are not yet acted on.

There is already an issue (ebsco/edsapi-ruby#38) for this already.

**Comment by bmckinney** [comment]
The 0.2.2.pre gem should now fix this specific bug: https://github.com/ebsco/edsapi-ruby/commit/b4228189578be03a6ff1c6f2b4823b86da870849

However, it doesn't fully address how to automagically turn on default search limiters on for users in blacklight. That deserves a conversation.

**Comment by drh-stanford** [comment]
This is working now
