### ISSUE TITLE
Record with two languages has messy encoding characters

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1466]
EN&lt;br /&gt;ES

https://sw-webapp-sandbox-f.stanford.edu/article/edsbas__edsbas_ftdoajjournals_oai_doaj_org_journal_aeeb3413b3c44bd5b05141020c0ba1b6

**Comment by drh-stanford** [comment]
I've noticed this in the Composed Title too -- see example at https://sw-webapp-sandbox-f.stanford.edu/article/edsgao__edsgcl_196008231

"Surface &amp;amp; Coatings Technology. Dec 20, 2006, Vol. 201 Issue 7, p3852, 5 p."

**Comment by drh-stanford** [comment]
Also, see UTF-8 problems here: https://github.com/ebsco/edsapi-ruby/issues/52
