### ISSUE TITLE
Previous / Next buttons not working with EDS gem

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/SearchWorks#1471]
The Blacklight way of defining the Previous/Next buttons isn't working with the EDS gem. See slack for a screencast and behavior. Blocked on EDS gem debugging.

**Comment by drh-stanford** [comment]
Narrowed this down to a problem with us not passing `start` and `rows` along to the EDS API in some cases.

**Comment by drh-stanford** [comment]
Created a ticket on the EDS API to clarify the `start`/`rows` parameters: https://github.com/ebsco/edsapi-ruby/issues/48

**Comment by bmckinney** [comment]
I think we're bumping up against situations where the EDS API cannot act exactly like a solr instance. 

I this particular case, this method was added to address Previous/Next: https://github.com/ebsco/edsapi-ruby/blob/master/lib/ebsco/eds/session.rb#L260

**Comment by drh-stanford** [comment]
I'll put a discussion of this on the agenda for Tuesday

**Comment by drh-stanford** [comment]
Even with #1488 I'm still seeing problems with paging -- if you look closely at the hits, they do not behave as expected. For example, hit 52 on a per page of 100 becomes hit 51 on a per page of 50 (page 2).

**Comment by drh-stanford** [comment]
Also see https://github.com/ebsco/edsapi-ruby/issues/53 for performance tracking.

**Comment by drh-stanford** [comment]
EDS Release 0.2.9.pre has search and retrieve caching

**Comment by drh-stanford** [comment]
Blocked by https://github.com/ebsco/edsapi-ruby/issues/60

**Comment by drh-stanford** [comment]
The PR #1549 is now ready for review.
