### ISSUE TITLE
40px high toolbar is rendering at 50px...

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1475]
.navbar class has min-height: 50px, which is overriding the sul-toolbar height.

.sul-toolbar has padding: 5px 0px, which falls outside the 40px height - should just be padding: 0px.

**Comment by camillevilla** [comment]
hi @jvine! Can I get some clarification around desired behavior? I'm currently seeing that `.sul-toolbar` height is 40px including padding.

![screen shot 2017-07-18 at 4 11 02 pm](https://user-images.githubusercontent.com/5402927/28343805-13814fc0-6bd4-11e7-814a-d9c709279cde.png)

![screen shot 2017-07-18 at 4 10 58 pm](https://user-images.githubusercontent.com/5402927/28343804-0f642930-6bd4-11e7-8817-1601ac8fbe5c.png)

**Comment by jvine** [comment]
Oops, more specificity would be good. The problem is only on the record view:
https://sw-webapp-sandbox-f.stanford.edu/article/edsgao__edsgcl_333447974

You can see there's padding above and below the 40px bar:
![screen shot 2017-07-18 at 4 25 09 pm](https://user-images.githubusercontent.com/6945691/28344008-b9949d94-6bd5-11e7-9677-0ea1eb04f0e6.png)
