### ISSUE TITLE
Pass current search to alternate target (catalog / articles)

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1489]

**Comment by drh-stanford** [comment]
Is the idea here to issue the same search on catalog if I select the pulldown to go from article to catalog (and vice versa)?

**Comment by jvine** [comment]
The idea is to issue an equivalent search in catalog, and vice versa.

If it's a general keyword search, then that's straightforward. If it's a fielded search, then we need to map articles to catalog and vice versa.

Article search -> Catalog search
- Author -> Author
- Article title -> Title
- Subject -> Subject
- Journal title -> Title
- Abstract -> All fields
- ISSN -> isbn_search (screenshot 1)
- ISBN -> isbn_search (screenshot1)

Catalog search -> Article search
- Title -> Article title 
- Author -> Author
- Subject -> Subject
- Call number -> All fields
- Series -> Keyword + SE (screenshot 2)

Screenshots

1 in catalog this will show in the breadcrumb but doesn't correspond to anything in the dropdown
![screen shot 2017-07-20 at 11 19 05 am](https://user-images.githubusercontent.com/6945691/28433424-5fc0ccae-6d40-11e7-85ce-72be186e9e12.png)

2
![screen shot 2017-07-20 at 11 44 04 am](https://user-images.githubusercontent.com/6945691/28433503-c5dffbfe-6d40-11e7-95ca-9c06c7840f44.png)

**Comment by jvine** [comment]
Note: Intentionally leaving out the pagination issue for now. That use case is: Patron is searching in articles, is on page 3 of results, decides to switch to catalog, then returns to articles - do they return to page 3, or to the top of the search result? Need to understand further when/whether this (leave and return) will actually happen.

**Comment by drh-stanford** [comment]
@jvine when the user is in midst of a search and wants to go back to the article/catalog home page, how do they do that? My understanding is that they have to click "<- Start Over". If they click on "SearchWorks" right now they always go to the catalog home page.

**Comment by jvine** [comment]
For now they'll have to click Start over - I'm going to have to think about the SearchWorks link and whether that should continue to go to catalog home. A lot of users don't know it's a link, and needed the explicit Start over button for catalog.


On Jul 21, 2017, at 4:26 PM, Darren Hardy <notifications@github.com<mailto:notifications@github.com>> wrote:


@jvine<https://github.com/jvine> when the user is in midst of a search and wants to go back to the article/catalog home page, how do they do that? My understanding is that they have to click "<- Start Over". If they click on "SearchWorks" right now they always go to the catalog home page.

**Comment by drh-stanford** [comment]
@jvine A few clarification questions:

1. What about mapping Catalog's Advanced Search?
  a. Catalog has a "Series title" search
  b. Catalog has a "Place, publisher, year" search
  c. Catalog has an "Author + TItle" search
2. What about facets? Do we simply drop them?
3. What about the sort by selection? Do we revert to the default (relevance)?

**Comment by jvine** [comment]
@drh-stanford Great questions. Some answers, and some questions back:

> What about mapping Catalog's Advanced Search?
> a. Catalog has a "Series title" search

Same as Series, see below.

> b. Catalog has a "Place, publisher, year" search

Ugh. If we pass this, it will likely not get a good result. Can we drop?

> c. Catalog has an "Author + TItle" search

Hm. My bet is if we pass this as a simple keyword search in EDS we'll get relevant results. I'm having trouble finding good examples to test whether the quotes make a difference. Let's keep the quotes and see what happens. 

> What about facets? Do we simply drop them?

- Can we retain Date as a facet?
- I think we need to drop Language. The facet values won't work in each other's index because they're normalized differently, and I don't think they'll work as keywords. 
- Resource type / Source type = can of worms. 
- Can we convert the rest to Keywords? 

> What about the sort by selection? Do we revert to the default (relevance)?

Yes.

> Also shouldn't "Series" (Catalog) map to "Journal title (source)"?

No. I don't think this would ever get a relevant result. The MARC Series title field is not going to contain journal titles; and EDS has eBook series that will match in SE.

These are equivalent searches:
- https://sw-webapp-sandbox-f.stanford.edu/catalog?utf8=%E2%9C%93&op=AND&search=&search_title=&search_author=&subject_terms=&series_search=SpringerBriefs+in+Environmental+Science&pub_search=&isbn_search=&range%5Bpub_year_tisim%5D%5Bbegin%5D=&range%5Bpub_year_tisim%5D%5Bend%5D=&sort=relevance&search_field=advanced&button=
- https://sw-webapp-sandbox-f.stanford.edu/article?utf8=%E2%9C%93&search_field=search&q=SE+%22SpringerBriefs+in+Environmental+Science%22

**Comment by jvine** [comment]
will create separate ticket(s) for outstanding issue(s)
