### ISSUE TITLE
Change <ul> to <dl> for subject in search results and add <dt> label

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1511]
Before:
```
<ul class="document-metadata dl-horizontal dl-invert">
    <li>Egypte, ...</li>
</ul>
```
![screen shot 2017-07-24 at 9 33 56 am](https://user-images.githubusercontent.com/6945691/28533904-a5c90da4-7053-11e7-8991-8ca56ccbc370.png)

After:
```
<dl class="document-metadata dl-horizontal dl-invert">
    <dt>Subjects</dt> <dd>Egypte, ...</dd>
</dl>
```
![screen shot 2017-07-24 at 9 38 27 am](https://user-images.githubusercontent.com/6945691/28533988-e2520e92-7053-11e7-8d3d-73d309be6c4e.png)

**Comment by drh-stanford** [comment]
@jvine the default styling has a hanging indent, like so. should we remove that?

![screen shot 2017-07-24 at 11 44 15 am](https://user-images.githubusercontent.com/1861171/28539113-71ea260a-7065-11e7-8420-18edfb7c6f7d.png)

**Comment by jvine** [comment]
Weird, it doesn't have that in SW catalog. It's okay for now; there's another ticket coming that might have affect it, so don't sweat it.
