### ISSUE TITLE
Bento Application Evaluation

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/SearchWorks#1514]
Evaluate the NCSU Quick Search app for use as a bento platform.

**Comment by drh-stanford** [comment]
See also https://github.com/jrochkind/bento_search

**Comment by drh-stanford** [comment]
So, I've been able to get an instance of the `bento_search` thing working. It doesn't appear to have much of a UI AFAIK. It's primarily an engine for implementing the backend plugins to search services. It has a lot of examples for that and it's reasonably organized. Most require API keys but I did find one that didn't -- `DoajArticlesEngine` and it works ok.

**Comment by drh-stanford** [comment]
At 7/31 meeting, we wanted to look at Cornell's implementation (based on quick_search reportedly)

**Comment by jkeck** [comment]
Closing this as it seems like NCSU's QuickSearch will give us a more robust starting point for building out an entire app.
