### ISSUE TITLE
Research Starter show page

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1518]
Basic layout is the same as HTML full text, with these modifications:

1. "Research starter" label and composed title below the article title
2. additional sidebar panel below the "Available online" panel, with links to related research starters
3. if there are images in the full text, display them where they occur, at their default size (?) with their captions, styled in a box (like the media node on the library website, example http://library.stanford.edu/areas)
   ```
    padding: 12px;
    background-color: #fff;
    border: 1px solid #e3dfd5;
   ```
4. render the embedded composed links as actual links (to other research starters)

![screen shot 2017-07-25 at 3 21 03 pm](https://user-images.githubusercontent.com/6945691/28596494-a66c3b0a-714d-11e7-8426-42ec7844c54b.png)

**Comment by drh-stanford** [comment]
@jvine Are there paging/selection controls for this? The research starter isn't really a document as we implement them in Blacklight and the EDS gem, so it's a little tricky.

Also do you have authentication for the pointer to the EBSCO hosted research starter, so I can see what they have?

  https://stanford.idm.oclc.org/login?url=http://search.ebscohost.com/login.aspx?direct=true&site=eds-live&db=ers&AN=88952994

**Comment by drh-stanford** [comment]
Also, just an implementation note is that the research starters have a dbid and accession id, like so:  https://sw-webapp-sandbox-f.stanford.edu/article/ers__88952994

**Comment by jvine** [comment]
> Are there paging/selection controls for this?

Not sure? The highlighted Research Starter is kind of out of the normal sequence of results - but at the same time, Research Starters is a value in the Database facet, and you can find them in any search result:
https://sw-webapp-sandbox-f.stanford.edu/article?f%5Beds_content_provider_facet%5D%5B%5D=Research+Starters&q=climate+change&search_field=search

**Comment by drh-stanford** [comment]
@jvine the Research Starters content requires authentication. Right now, viewing the Research starter in guest mode only shows the abstract whereas being logged in shows the HTML full text. Do we need some kind of "login to see content" type link somehwere? Both here and on the results page?

**Comment by drh-stanford** [comment]
@jvine The current full text show page has a label "Full text". Is this what we want for all the show pages, including research starters? It's different than your screenshot above...

![screen shot 2017-07-27 at 11 50 12 am](https://user-images.githubusercontent.com/1861171/28686938-ca57f3cc-72c1-11e7-88b1-a41fa6f0ab04.png)

**Comment by jvine** [comment]
@drh-stanford I think the screenshot you included with the label is out of date - Camille fixed it to match the top screenshot. Or am I misunderstanding your question?

**Comment by drh-stanford** [comment]
@jvine EBSCO doesn't distinguish the section headers from just regular bold terms, so it looks like this:

Also, can you be more specific about where the "Related research starters" come from? I don't see them anywhere in what the EDS API is returning to us.

![screen shot 2017-07-27 at 1 56 25 pm](https://user-images.githubusercontent.com/1861171/28691922-6b54f624-72d3-11e7-86d1-ba8820079258.png)

**Comment by drh-stanford** [comment]
@jvine below is what I have currently in my feature branch (`1504-research-starters`) - the Full Text label will go away when the PR is approved.


![screen shot 2017-07-27 at 2 45 13 pm](https://user-images.githubusercontent.com/1861171/28693585-3c106464-72da-11e7-80f0-a839fdc30af1.png)

**Comment by drh-stanford** [comment]
@jvine can we break the related research starters into a different ticket? i found them but they come back only in a search, so we need to re-run the search or cache the data in the session which is a little more implementation effort.

here's an example for "climate":

```json
  {
    "id": "ers__88952993",
    "title": "Climate and Climatology."
  },
  {
    "id": "ers__89475565",
    "title": "Climate zones."
  },
  {
    "id": "ers__89475554",
    "title": "Climate and the climate system."
  },
  {
    "id": "ers__89475904",
    "title": "Weather vs. climate."
  },
  {
    "id": "ers__88952995",
    "title": "Climate Modeling."
  }
```
