### ISSUE TITLE
Implement IP-based authentication

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/SearchWorks#1529]
See sul-requests for example.

We still need the list of blessed IPs but it'll be configured in a YAML file.

See https://github.com/sul-dlss/SearchWorks/issues/1348 for the larger authentication ticket.

**Comment by jkeck** [comment]
See also [shared_configs](https://github.com/sul-dlss/shared_configs/blob/sul-requests-prod/config/settings/production.yml#L39)

**Comment by drh-stanford** [comment]
See https://consul.stanford.edu/display/ERU/IP+Addresses+-+Default

**Comment by drh-stanford** [comment]
@jvine we need to double-check that these are the complete set of IP addresses -- it's a fairly narrow set (see Consul link above) and different than sul-requests (see shared_configs link above)

**Comment by drh-stanford** [comment]
@jvine we need to talk with Tom to move this forward

**Comment by jkeck** [comment]
Closing this as any additional tasks are ticketed already.
