### ISSUE TITLE
Open-access links

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1532]
Related to #1476 

There's a 5th link type, that fits between 3 & 4 in the original list. 

1. HTML full text
2. PDF full text
3. Check SFX for full text
4. **Open access links**
    - **applies to things like Hathi Trust that have links out to the publisher's site, but we don't have them in SFX, so they won't be picked up by 1-3 above.**
    - **use the link text provided by the API** 
5. (was 4) View request options (print etc.)

AFAICT the "Access URL" and "Availability" links should still be excluded.

**Comment by drh-stanford** [comment]
@jvine do you have an example article that has one of these links?

**Comment by jvine** [comment]
@drh if you do a search and facet by Hathi Trust- can't remember if it's a database or publisher- that should get some.

Sent from my iPhone

On Jul 31, 2017, at 11:59 AM, Darren Hardy <notifications@github.com<mailto:notifications@github.com>> wrote:


@jvine<https://github.com/jvine> do you have an example article that has one of these links?

**Comment by drh-stanford** [comment]
Ok, I found the following -- should I just be matching when the label has "Open Access" in it?

```json
{
"url": "http://hdl.handle.net/2027/mdp.39015076022634?",
"label": "View in HathiTrust Open Access",
"icon": null,
"type": "customlink-fulltext"
},
```

**Comment by jvine** [comment]
I don't know much we can depend on that wording though. Can we just allow everything that isn't otherwise handled?

Sent from my iPhone

On Jul 31, 2017, at 1:44 PM, Darren Hardy <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, I found the following -- should I just be matching when the label has "Open Access" in it?

{
"url": "http://hdl.handle.net/2027/mdp.39015076022634?",
"label": "View in HathiTrust Open Access",
"icon": null,
"type": "customlink-fulltext"
},

**Comment by drh-stanford** [comment]
Ok, then I'll consider a link a (4) if it's not one of the others AND it's not "Access URL" or "Availability".
