### ISSUE TITLE
Italicize the title part of the composed title in results and record view

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1538]
Before
![screen shot 2017-08-01 at 2 04 43 pm](https://user-images.githubusercontent.com/6945691/28847031-951d03e6-76c2-11e7-9838-235038457f8d.png)

After
![screen shot 2017-08-01 at 2 05 11 pm](https://user-images.githubusercontent.com/6945691/28847030-95197cd0-76c2-11e7-9d0b-39768dae346b.png)

Note that this doesn't seem to be consistent in EDS metadata on either results or record view. Some titles are italicized, some are linked, some are neither. Not sure if we can depend on punctuation, either - some titles end with period, some with comma or other punctuation. And here's an example where a different part of the composed title is italicized and shouldn't be: https://sw-webapp-sandbox-f.stanford.edu/article/cmedm__28357797.

**Comment by jkeck** [comment]
I believe we just get this back as a string, not as structure data.  I'm not sure it'll be possible for us to reliably determine which part of the string is the title vs. the rest of the citation.

**Comment by drh-stanford** [comment]
Sometimes we get back an `<i>` element and other times a `<searchLink>` element, but I don't think we're guaranteed that all composed titles have markup like that.

**Comment by drh-stanford** [comment]
In your example record above, that one does have a `<searchLink>` that we could transform.

**Comment by jvine** [comment]
We were discussing in standup, and I wondered if we could fall back to "italicize up to the first . , or ]"? Would not be foolproof, but better than nothing italicized.

**Comment by drh-stanford** [comment]
I took a look at `cmedm__28357797` again and EDS is sending back both a `<searchLink>` tag and an `<i>` tag, so that's why there's two italicized sections in that composed title (there's an outstanding PR to make the `<searchLink>` tags italicized):

```json
"eds_composed_title": "<searchLink fieldCode=\"JN\" term=\"%22Environmental+science+and+pollution+research+international+[Environ+Sci+Pollut+Res+Int]+NLMUID%3A+9441769%22\">Environmental Science And Pollution Research International</searchLink> [Environ Sci Pollut Res Int] 2017 May; Vol. 24 (13), pp. 12347-12359. <i>Date of Electronic Publication: </i>2017 Mar 29."
```

**Comment by drh-stanford** [comment]
I've implemented a scheme that italicizes the first "phrase" that it finds (by looking for the first punctuation mark), but it's not smart enough to work with things like:

- In Environmental Development Jul 2016
- Agriculture, Ecosystems and Environment 1 March 2016 219:163-170

Most records I'm finding have markup in them (either `<searchLink>` and/or `<i>`) already so the first "phrase" algorithm won't kick in.
