### ISSUE TITLE
Author affiliations has EDS markup

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/SearchWorks#1543]
See an example here: https://sw-webapp-sandbox-f.stanford.edu/article/aph__118908757

![screen shot 2017-08-02 at 3 03 54 pm](https://user-images.githubusercontent.com/1861171/28897036-d3edda1a-7793-11e7-99de-195d73a85b24.png)

**Comment by camillevilla** [comment]
Merged with #1551
