### ISSUE TITLE
Author affiliations have embedded XML and aren't related to authors

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1551]
We are getting XML in the author affiliations content. But even if we strip it out, we'll get numbered affiliations that don't relate to the authors list - they're not just sequential, and one affiliation can apply to several authors in the list. Can we (easily) add the reference numbers to the author list? If not, I'm inclined to strip the relationships altogether, since they're in the article itself.

**What we're displaying**
https://sw-webapp-sandbox-f.stanford.edu/article/egh__109358308
![screen shot 2017-08-03 at 3 39 44 pm](https://user-images.githubusercontent.com/6945691/28946942-1b3c3e24-7862-11e7-9158-9ec12f6ceebb.png)

**What EDS native UI displays**
https://stanford.idm.oclc.org/login?url=http://search.ebscohost.com/login.aspx?direct=true&db=egh&AN=109358308&site=eds-live
![screen shot 2017-08-03 at 3 40 02 pm](https://user-images.githubusercontent.com/6945691/28946945-211d75e2-7862-11e7-82b8-30f9148bdf00.png)
![screen shot 2017-08-03 at 3 40 18 pm](https://user-images.githubusercontent.com/6945691/28946947-23f07670-7862-11e7-9816-247f4bc35d43.png)

**If we can add numbers to authors**
![screen shot 2017-08-03 at 4 16 28 pm](https://user-images.githubusercontent.com/6945691/28947961-9559311c-7867-11e7-9fbe-36ad7ee4d803.png)

**If we can't**
![screen shot 2017-08-03 at 4 13 37 pm](https://user-images.githubusercontent.com/6945691/28947943-7a12fc30-7867-11e7-9a57-336be800874b.png)

**Comment by camillevilla** [comment]
Adding an example provided by @drh-stanford 
https://sw-webapp-sandbox-f.stanford.edu/article/aph__118908757

![screen shot 2017-08-02 at 3 03 54 pm](https://user-images.githubusercontent.com/1861171/28897036-d3edda1a-7793-11e7-99de-195d73a85b24.png)
