### ISSUE TITLE
Clicking the target you are already in, clears the search result and goes to home page

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1556]
Do a search in articles.
Click the article/catalog dropdown.
Click articles.
Search is cleared and you go to the home page. 

Same deal from catalog.

The target you are already in should be disabled, so clicking it does nothing.

**Comment by camillevilla** [comment]
Here's the bug I'm working on. The dropdown is only affected on show pages.

## Home page and Results (working)
![working-dropdown](https://user-images.githubusercontent.com/5402927/29294359-db427fc2-8103-11e7-8800-f6e71ba10f18.gif)

## Record (bug)
![dropdown-bug](https://user-images.githubusercontent.com/5402927/29294360-dd3c242c-8103-11e7-91bb-b0bbe51aded6.gif)
