### ISSUE TITLE
In guest mode, any PDF link gives an error

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1557]
Discovered in utest - while in guest mode, any PDF link gave a "We're sorry, but something went wrong" or “The page you were looking for doesn't exist” error. 

Should the link direct to a login? 
Can the link say "Log in to view/download PDF"?

**Comment by drh-stanford** [comment]
I haven't seen any PDF links work yet (see #1427) -- EDS always returns "detail" as the URL which generates the errors you describe.

**Comment by drh-stanford** [comment]
Need to talk with EDS

**Comment by drh-stanford** [comment]
See https://github.com/ebsco/edsapi-ruby/issues/62

**Comment by drh-stanford** [comment]
See https://github.com/ebsco/edsapi-ruby/wiki/INFO:-Full-Text-PDF-Links for a detailed explaination.

>  if i understand this correctly, we cannot get the real PDF link at search time. your solution is to make the link go to a new controller method that does a Retrieve to find the link and then redirects the user there.
