### ISSUE TITLE
Modification to Hoover Aeon request link

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1564]
1. Make the link open in a new tab
2. Add text to the button, either as a visible-on-hover/focus div within the button, or as a bootstrap tooltip.

Text is:
`Aeon requires signup/login<br>Opens in new tab`

### Expando-button
- text is in a div with "height=1px"
- on focus/hover, the div height is set to auto, so the button expands
```
<a rel="nofollow" class="btn btn-default btn-xs request-button pull-right" href="https://hoover.aeon.atlas-sys.com...>Request on-site access
    <div class="aeon">Aeon requires signup/login<br>Opens in new tab</div>
</a>
```
```
div.aeon {height: 1px;}
.request-button:hover div.aeon, .request-button:focus div.aeon {height: auto;}
```
<img width="310" alt="screen shot 2017-08-09 at 10 56 47 am" src="https://user-images.githubusercontent.com/6945691/29137267-a6e3d3b0-7cf4-11e7-8cb6-2ae21c650251.png">

Pro: text is always included in the button for screenreader; visible on focus/hover for sighted users including keyboard only
Con: slightly dorky effect as the button expands in place

### Tooltip
<img width="310" alt="screen shot 2017-08-09 at 10 38 46 am" src="https://user-images.githubusercontent.com/6945691/29137275-b10515d4-7cf4-11e7-8f58-55638bd6c05c.png">

Pro: slicker visual presentation, aria accessible
Con: might be more complicated to implement?

**Comment by jkeck** [comment]
@jvine I can make the same text that shows up in the pop-up be screen-ready only text in the button if that helps us have the slicker design while retaining accessibility.

One thing though, we've updated the styling of tooltips across the site to be a slightly lighter color.

Does this look okay?

<img width="382" alt="tooltip" src="https://user-images.githubusercontent.com/96776/29229546-d97acdec-7e93-11e7-8ae4-9331ac70dbd6.png">

<img width="552" alt="button-markup" src="https://user-images.githubusercontent.com/96776/29229576-05d2541e-7e94-11e7-91b4-60f45f9a4808.png">

**Comment by jvine** [comment]
@jkeck, the bootstrap tooltip does something with "aria-labeledby" that makes it accessible. If we're not using that feature, then sr-only text in the button is fine. And yeah, the lighter colour is fine.

**Comment by jkeck** [comment]
Ah, I hadn't even noticed that, yeah I see the aria attribute now. I'll remove the sr-only text.

**Comment by jvine** [comment]
In production for Hoover and Archive.
