### ISSUE TITLE
Add visible links for HTML full text to results

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1570]
Currently articles with HTML full text don't have a visible link on the results page - you just click the title. Users are scrolling past these, assuming that full text is not available for those items. 

Can we add a link with the "Full text" label and "View on detail page" as the link text, pls?

**Comment by drh-stanford** [comment]
I will check on whether we have that information readily available from the EDS gem in the search results.

**Comment by drh-stanford** [comment]
@jvine Do you have an example of an article that has HTML full text, but not a full text link (like a PDF full text link)?

**Comment by jvine** [comment]
there are a bunch in this search result
https://sw-webapp-sandbox-f.stanford.edu/article?utf8=%E2%9C%93&f%5Beds_search_limiters_facet%5D%5B%5D=Stanford+has+it&search_field=search&q=Guzman%2C+Andrew+T.%3A+Overheated%3A+The+Human+Cost+of+Climate+Change

https://sw-webapp-sandbox-f.stanford.edu/article/edsgao__edsgcl_320590702
https://sw-webapp-sandbox-f.stanford.edu/article/aph__85286083
https://sw-webapp-sandbox-f.stanford.edu/article/edselp__S0262407913603139

**Comment by drh-stanford** [comment]
Blocked on https://github.com/ebsco/edsapi-ruby/issues/64

**Comment by jkeck** [comment]
Closed by #1607
