### ISSUE TITLE
Block all $1 from SearchWorks display (not librarian view)

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/SearchWorks#1582]
add to the "exclude fields list"
https://jirasul.stanford.edu/jira/browse/SW-1851

**Comment by ahafele** [comment]
Test record - http://searchworks-test.stanford.edu/morison/view/6994641

**Comment by ahafele** [comment]
No longer a priority right now. Details in JIRA ticket. Moved to 3.3

**Comment by jkeck** [comment]
So I was looking a bit into this.  One potential complication is that we use $1 to indicate when a piece of metadata is from Nielsen.  When processing the subfields we then translate that $1 content to something else based on the subfield value.

We'll need to re-think that approach if we're now going to consider the field that indicates Nielsen content as now being ignored.

**Comment by ahafele** [comment]
Update - this has now been implemented in OCLC and there is a new list of tags that will include these $1uri's. We will likely start to see these in records soon. https://help.oclc.org/WorldCat/Cataloging_documentation/Technical_Bulletins/268#Subfield_.E2.80.A11_(Real_World_Object_URI_(R))
ISNI is meeting this week to discuss using it and Darsi has ideas about doing a large batch of updates from our authority records with LD4P goals in mind.
