### ISSUE TITLE
Can we change articles URL?

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1584]
Is it too late in the game to change

https://sw-webapp-sandbox-f.stanford.edu/article

to 

https://sw-webapp-sandbox-f.stanford.edu/articles

(with an s)

It would match the dropdown and branding.

**Comment by drh-stanford** [comment]
This is a routing change and should be straightforward. We will need to update the Rails route and our tests. Am I correct on that @jkeck?

**Comment by jkeck** [comment]
Yeah, should be easy enough!

**Comment by jvine** [comment]
OK, let's do it, please.
