### ISSUE TITLE
Map "Series" to "Series' in catalog/article switch

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1588]
From the original ticket (#1489)  :

drh: Also shouldn't "Series" (Catalog) map to "Journal title (source)"?

jv: No. I don't think this would ever get a relevant result. The MARC Series title field is not going to contain journal titles; and EDS has eBook series that will match in SE.

These are equivalent searches:

https://sw-webapp-sandbox-f.stanford.edu/catalog?utf8=%E2%9C%93&op=AND&search=&search_title=&search_author=&subject_terms=&series_search=SpringerBriefs+in+Environmental+Science&pub_search=&isbn_search=&range%5Bpub_year_tisim%5D%5Bbegin%5D=&range%5Bpub_year_tisim%5D%5Bend%5D=&sort=relevance&search_field=advanced&button=
https://sw-webapp-sandbox-f.stanford.edu/articles?utf8=%E2%9C%93&search_field=search&q=SE+%22SpringerBriefs+in+Environmental+Science%22

This is currently implemented as Series -> Journal title - needs to be updated to Series -> Series.

**Comment by camillevilla** [comment]
@jvine is the reverse also expected? (Article / `series` -> Catalog / `search_series`)

**Comment by jvine** [comment]
@camillevilla Yes. :-)
