### ISSUE TITLE
Change text & visual display of full text links

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1595]
Goal: reduce redundant text and visually call out PDF links.

**Content provider links**
![full text content provider](https://user-images.githubusercontent.com/6945691/29378759-1affcd6e-8275-11e7-83e9-1dcdfbe2b4e0.png)
- remove "full text" from the link text.

**PDF links**
![full text pdf](https://user-images.githubusercontent.com/6945691/29378221-1f1da0da-8273-11e7-9f2f-14387c8d94f6.png)
- add PDF icon between the label and link
- height of icon is 20px
- icon has `alt="PDF"`
- remove "full text" from the link text

**HTML links**
![full text html](https://user-images.githubusercontent.com/6945691/29378226-22baa166-8273-11e7-9582-6a9b20111e45.png)

**If there is both an HTML link and a PDF**, ideally show both
![full text pdf html combined](https://user-images.githubusercontent.com/6945691/29378209-168796f6-8273-11e7-9bad-b22ff920005a.png)
Second record in this search result is an example that has both
https://sw-webapp-sandbox-f.stanford.edu/articles?utf8=%E2%9C%93&f%5Beds_search_limiters_facet%5D%5B%5D=Stanford+has+it&search_field=title&q=Can+cats+teach+us+how+to+live%3F

**PDF icon in 2 sizes** - 20px, and massive:
![pdf-icon-20](https://user-images.githubusercontent.com/6945691/29379204-894befae-8276-11e7-8385-c91e629785d3.png)
![pdf-icon](https://user-images.githubusercontent.com/6945691/29379164-5c58cd32-8276-11e7-900f-849367f09226.png)

Also have an SVG version but can't upload it here. Let me know if you want it.

**Comment by jkeck** [comment]
@jvine I believe the svg would be preferable for this sort of thing.

**Comment by jkeck** [comment]
Holding off on this for the time-being.  I think that #1570 should come before this as they may conflict, and at the very least we'll need to have the visible links to full-text HTML in order to accomplish the `If there is both an HTML link and a PDF, ideally show both` task.

**Comment by jvine** [comment]
svg icon:  https://stanfordlib.slack.com/files/jvine/F6Q40Q2HG/pdf-icon.svg
