### ISSUE TITLE
Replace Options facet with new interaction

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1596]
> ![search-settings-default](https://user-images.githubusercontent.com/6945691/29390638-7402d466-82a6-11e7-8ae2-ec41e5259f45.jpg)

- remove "Options" from the facet list
- add a section above the facets, with h2 heading "Search settings"
- add checkboxes below the heading (no panel box)
```
<input type="checkbox" id="thisCheckbox" aria-describedby="willSubmit">
<label for="thisCheckbox">text comes from admin</label>
...
<span id="willSubmit" class="sr-only">Selecting this setting will update your search results</span>
```
### interaction
To account for the delay between checking a checkbox and being able to do anything else, onClick (?) should disable both checkboxes, and show the same "processing" indicator as on the record view for "all available sources", until the results are refreshed.

> ![search-settings-updating](https://user-images.githubusercontent.com/6945691/29390600-396603e6-82a6-11e7-89b6-11f00c41da9f.jpg)

### breadcrumb
In the search breadcrumb, display the selection as "Settings > [label text]"
> ![search-settings-breadcrumb](https://user-images.githubusercontent.com/6945691/29390656-9cd2aad8-82a6-11e7-82b7-6076a923a20d.png)

### collapse
OK for now if the new section remains open above the collapsed facets.
> ![search settings collapse](https://user-images.githubusercontent.com/6945691/29390844-ec574cf2-82a7-11e7-884a-4bc235775002.png)

### future considerations
1. Search settings will appear on the home page as well - may need a different interaction, since it won't be updating the results; will definitely need different aria-describedby text.

2. Goal is to replace the text string from admin with the FT1 or PR code so saved searches will not be broken by text changes. Blocked by needed update from Ebsco.

**Comment by jkeck** [comment]
Closed by #1670
