### ISSUE TITLE
Update "No results" pages

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1598]
Affects both Catalog and Articles.

### Page layout
- layout is 2 columns below the `h2` - this is different from current, where the left sidebar happens before the right column `h2` and content.
- left column: "Try your search in" block
- right column: "Modify your search" block
- right column: chat + search tools

![no results - catalog - layout](https://user-images.githubusercontent.com/6945691/29948441-ae933e22-8e63-11e7-920d-c6d11edbab66.png)

### "Try your search in" block
- same functionality and basic layout as the target dropdown
  - (might be useful to put these target names and help texts in a shared location? I'm noticing some drift as we refine wording, and the goal is for them to match)
- pass the current search to:
   - catalog
   - articles+
   - library website
   - all 
- leave out whichever one user is currently in (e.g. don't display catalog in catalog no results)

![no results - articles - try your search](https://user-images.githubusercontent.com/6945691/29948328-145bcfae-8e63-11e7-80e6-f1afd46b80e5.png)
![no results - catalog - try your search](https://user-images.githubusercontent.com/6945691/29948329-14617e72-8e63-11e7-8653-3d9f7c6bd5d9.png)

### "Modify your search" block
- add some definition to the formatting:
  - `<dl>` overall
  - replace : with > (as in the breadcrumb)
  - replace comma between arguments with + 
  - add bold to the "found # results"
- make sure these searches happen in the **current target** (right now articles+ is sending over to catalog)

![no results - articles - modify](https://user-images.githubusercontent.com/6945691/29948060-b3f5d2aa-8e61-11e7-9734-b19ea124a969.png)
![no results - catalog - modify](https://user-images.githubusercontent.com/6945691/29948088-dc4d7ed8-8e61-11e7-8751-306658dc565f.png)

### Chat... block (same for both)
- note that there is some logic around displaying the chat or not depending on on-campus/logged-in status

![no results - both - chat](https://user-images.githubusercontent.com/6945691/29948196-603ecea4-8e62-11e7-86b3-389ee72c6272.png)

**Comment by camillevilla** [comment]
Split off "make sure these searches happen in the current target (right now articles+ is sending over to catalog)" to #1705
