### ISSUE TITLE
Update home pages

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1599]
TODO:
- [x] Implement layouts and panels
  - [x] catalog
  - [x] articles
- [x] Update text placeholders
- [x] "You are here" selection
- [x] Settings (see #1673)
- [x] Search tip rotation (see #1674)
- [ ] Update link placeholders (see #1676)

![articles home w comments.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55e7873278db271d00ed1647/125516c66e82c728ace21e0d46e9868e2a818fac9ca9b74ca958b0836945287e2401ad3f63c7af6aaf50740b0a0c0abe4b4a5a42fff08d2ef2b139748b5e0db9d1385f74cf3518adbbd30da313f871d51bdaebe5c01982fa3737e683854e3b1e06118dfa5e35a39f43c94abb.png)

![catalog home w comments.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55e7873278db271d00ed1647/125516c66e82c728ace21e0d46eb958e228e8caecfe1b04ea11de7d42a492a7e2c0ab73832c9a138ad4d71040c1b5ca6535d5947f5fd8c7fa1b33871885a5fed846d5f7dce3410afe99003ad43eb7edf10d8eff6df0ed2e22f24e0818e4a3e1d0c1c8cfc5c31a4904cda15.png)

**Comment by jvine** [comment]
Link for search tips page on the Article home page:
https://library.stanford.edu/guides/article-search-tips

**Comment by drh-stanford** [comment]
@jvine For the latter half of the home pages, it looks like the only difference is the "You are here" part, correct? Also, do you have the CSS that implements that glowy shadowed border?

**Comment by jvine** [comment]
Correct, they are the same except for the "you are here". 

CSS is:
> -webkit-box-shadow: 0px 0px 10px 0px rgba(233,131,0,1);
-moz-box-shadow: 0px 0px 10px 0px rgba(233,131,0,1);
box-shadow: 0px 0px 10px 0px rgba(233,131,0,1);

If it's useful, the hex colour is #e98300, which is "Poppy" in the new identity palette.

**Comment by jvine** [comment]
Text for catalog page:

### Featured resources

**Digital collections**
Images, maps, data, & more from the Stanford Digital Repository.

**Theses & dissertations** 
Theses & dissertations in the Stanford Libraries and Digital Repository.

**Course reserves**
Find books, media, and e-resources set aside for classes.

**Government documents**
Stanford is a depository library for state, federal, UN, and EU government documents.

**Databases (URL should now be /databases)**
A-Z list of topic-specific databases. Not sure where to start? Try these [selected databases](/selected_databases).


### Search Stanford's library resources (SHARED)

**Catalog**
Search the physical collections and digital resources of Stanford’s libraries. Find books, media, [topic-specific databases](https://searchworks.stanford.edu/databases).

**Articles+**
Search a combined index of 100s of databases, and connect directly to the article or resource. Covers ~87% of our subscribed databases.

**Library website**
Find topic specialists, blog posts, descriptions of our notable collections, as well as libraries, hours, and policies.

**Yewno**
Explore concepts and connections, and understand interdisciplinary subjects, in a graph interface.

**All the above**
Get an overview of what’s available in all these sources for your search topic.

-------

**More search tools**
Discover and access library and archival materials, journals, databases, data, and e-resources beyond SearchWorks.

**Comment by jvine** [comment]
Images are being added here:
https://stanford.box.com/s/h46zqkztwwu4u3xb1ki8tq4uzctjt8fs

**Comment by jvine** [comment]
Articles text

### Search settings

**Scholarly & peer-reviewed**
Limit your search to scholarly content. Includes University presses.

**Direct access to full text** 
Stanford subscribes to the full text, or it’s available via open access.

### How do I access articles?

**On campus**
No configuration required. Just click the links in the search results or detail page. 

**Off campus**
You’ll need to log in. You can [log in now], or when you find an article of interest.

Link text:  More about article access at Stanford Libraries
(Link TBD)

**Comment by snydman** [comment]
@jvine should there also be a homepage design for "all" search?  or will that use the "catalog" homepage design?

**Comment by drh-stanford** [comment]
@jvine Here's what I have for the upper half of the Articles+ home page:

![screen shot 2017-08-30 at 12 50 04 pm](https://user-images.githubusercontent.com/1861171/29891965-cacb9bf8-8d81-11e7-81a8-3a0018f6c822.png)

Should the settings' labels be bold? Should the hyperlinks be blue (default?) as in the mockup or underlined as they are now?

**Comment by jvine** [comment]
Ooh, if the settings can have the help text directly below each checkbox/label, that's excellent. The label values will need to come from the admin- check w @jkeck about this. I like the labels bold with the text directly below.

The "sticky" text is apparently not true :-( so should be removed.

Hyperlinks should be current default (underline), no special styling, so it can automatically be changed to blue (no underline) when we do the visual design update.

**Comment by drh-stanford** [comment]
@jvine re: the You Are Here indicator -- what is the green color? also are the corners rounded? i'm not sure how to do that in CSS. also I still need to get the image to fill the panel width

![screen shot 2017-08-30 at 1 27 51 pm](https://user-images.githubusercontent.com/1861171/29893505-266409fa-8d87-11e7-9e0e-937e2059f948.png)

**Comment by drh-stanford** [comment]
@jvine here's what I have for the shared lower half stuff. note that the heights of the panels are different in the first row. i haven't found a way to correct this yet (make them all the same height) in a way that works responsively.

![screen shot 2017-08-30 at 2 06 10 pm](https://user-images.githubusercontent.com/1861171/29895045-772ca91e-8d8c-11e7-8cc9-2cc364814175.png)

**Comment by drh-stanford** [comment]
@jvine here's the current state for the article home page. how does it look?

![screen shot 2017-08-30 at 3 04 17 pm](https://user-images.githubusercontent.com/1861171/29897215-b7393718-8d94-11e7-8d02-7cbdbefcc65a.png)

**Comment by drh-stanford** [comment]
@jvine here's the current state of the catalog home page:

![screen shot 2017-08-30 at 3 45 25 pm](https://user-images.githubusercontent.com/1861171/29898394-5fd5690a-8d9a-11e7-9d1f-0c98cb52c390.png)

**Comment by jvine** [comment]
@drh - re catalog home page 
- missing the first h1
- it looks like the facets column width is 3 instead of 4...? shouldn't change from current.

**Comment by drh-stanford** [comment]
here's the revision for the h1 and width=4:

![screen shot 2017-08-31 at 10 15 32 am](https://user-images.githubusercontent.com/1861171/29935962-5e54aa96-8e35-11e7-8626-e235e2901925.png)
