### ISSUE TITLE
Add "all" and "website" to search dropdown (when bento is ready)

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1601]

**Comment by snydman** [comment]
Does this also require homepage text?

**Comment by drh-stanford** [comment]
bento is live now

**Comment by camillevilla** [comment]
Bento was added by #1804. 
Website is missing from the search dropdown. Is this blocked until website-only search is working again?

**Comment by jkeck** [comment]
Let's wait for @jvine do weigh in.  I don't believe it was in the final mockups I saw, so I think we can live w/o for now.  FWIW the website-only search is available at `https://library.stanford.edu/search/website?search=hours` so I think we could link to that if need-be.

**Comment by cbeer** [comment]
We've added stuff to bento instead.
