### ISSUE TITLE
EBSCO::EDS::BadRequest: {... "ErrorDescription"=>"Record not found", "ErrorNumber"=>"132"}

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/SearchWorks#1603]
## Backtrace

    line 31 of [PROJECT_ROOT]/app/models/eds/repository.rb: eds_find
    line 11 of [PROJECT_ROOT]/app/models/eds/repository.rb: block in find
    line 10 of [PROJECT_ROOT]/app/models/eds/repository.rb: find

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50022/faults/34398571)

**Comment by jkeck** [comment]
It looks like the identifier `edsbl__vdc_100038239958_0x000001` is throwing a RecordNotFound error.  Might be due to the `0x000001`?  Not entirely sure.

**Comment by jkeck** [comment]
@efrierson, have any idea why we're getting that error for this identifier?  Looking this up by title (`Development of an in vitro Ovary Culture System to Evaluate Endocrine Disruption in Wood Frog Tadpoles`) in the native interface, I'm not getting an result w/ that accession number or database id.

**Comment by jkeck** [comment]
Ah, actually, I see now.  We're replacing all underscores w/ a period in the accession number, however the first underscore in this accession number is legitimate.

Do you have some guidance on how we should handle identifiers like this?

**Comment by drh-stanford** [comment]
@efrierson @bmckinney based on your sample blacklight app, we're replacing underscores with periods in the accession number, but that's not working in all cases like this one above.

See https://github.com/ebsco/eds_blacklight_search_app/blob/master/app/models/blacklight/eds/repository.rb#L10 and https://github.com/sul-dlss/SearchWorks/blob/article-search/app/models/eds/repository.rb#L29

**Comment by drh-stanford** [comment]
Ok we've isolated the problem and the resolution is to modify the rails route constraint for the id and to pass the dbid and accession number verbatim between the gem and the app.

**Comment by bmckinney** [comment]
Fix available in 0.3.8.pre gem.
