### ISSUE TITLE
Remove library chat feature from SW Feedback and no results page

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1608]
In the feedback form (articles and catalog - same form?)
<img width="174" alt="screen shot 2017-08-17 at 12 26 13 pm" src="https://user-images.githubusercontent.com/6945691/29429967-72049860-8347-11e7-84ce-f92e594ba4c0.png">

On the catalog no-results page:
<img width="392" alt="screen shot 2017-08-17 at 12 26 33 pm" src="https://user-images.githubusercontent.com/6945691/29429984-82d0bec6-8347-11e7-9e1d-b45e59bbb5b7.png">

Just remove these blocks. By request of IC.

**Comment by jkeck** [comment]
@jvine yeah, they are the same form.

Is this change request to remove the feature entirely from the application?  (I believe those are the only two places the chat JS shows up).

**Comment by jvine** [comment]
Yeah, kill it entirely pls.

**Comment by jvine** [comment]
Or, you know, put it behind webauth.

**Comment by jkeck** [comment]
We could actually only render the chat widget for authenticated users pretty easily.  Is that what you would like us to do?

**Comment by jvine** [comment]
omg, really? yeah! (i assumed it would be an effort of putting the chat itself behind webauth but if we can just suppress the link, that's cool.) what about making it the same as non-guest access?

**Comment by jkeck** [comment]
Hmm, we could do that, but is this expected to be rolled out before or with article search?

**Comment by jvine** [comment]
Before school start. Webauth alone would be fine from a policy perspective.
