### ISSUE TITLE
EDS API Defect: Source Type Facet Hit Counts

### ISSUE THREAD

**Issue by efrierson** [sul-dlss/SearchWorks#1617]
EBSCO Service Issue #163083 

See attached PPT for an illustration of the issue.  [API-Facet-Count-Issue.pptx](https://github.com/sul-dlss/SearchWorks/files/1235453/API-Facet-Count-Issue.pptx)

There is a difference EDS native user interface and the EDS API.  In the native UI, if you click on a source type like **Academic Journals**, you’ll notice the hit counts for other source types do not change.  In other words, if there were 7,000 hits for Magazines _before_ clicking **Academic Journals**, there would be 7,000 hits for **Magazines** _after_ clicking **Academic Journals**.  This is preferred, because when you select both facet values, you end up with a combined (Boolean OR) search result.
               
However, in the EDS API, the 7,000 hits for **Magazines** changes to _3_ when the **Academic Journals** facet is applied, indicating that the hit count is representing an AND of the applied **Academic Journals** facet value and the **Magazines** facet value – in other words, only 3 items in the results list are categorized as both Magazine AND Academic Journal.  However, when you click on the Magazines facet, you end up with a combined (Boolean OR) search result.  

This is a weird combination, because you expect to end up with 3 hits after clicking Magazines, but you end up with a substantially larger result set than you originally had, because it’s actually an OR’d combination of results.

**Comment by efrierson** [comment]
Current Status (Aug 18): Reported to EBSCO API Dev Team.  Diagnosed as a defect in the EDS API.  Currently in prioritization for resources.

**Comment by efrierson** [comment]
I think we might have a workaround via our Gem.  I need to consult with @bmckinney to make sure this is viable, but I think it is.  If our gem receives a request, we will cache the initial set of Source Type and Content Provider facets and hit counts.  We will return those cached sets until the user changes the query.  This way, applying new facets does not affect the availability or hit counts for those two OR-based facets.

This is only temporary while our API engineers can solve the root issue; what I think is nice about this approach is that it will provide the same behavior as our native UI.  If @bmckinney thinks this is reasonable to implement, this will be our solution for this issue, giving our API engineers more time to diagnose and fix the issue.  I do not think our back-end engineering teams will be able to resolve the core issue in time for you to test it and release it - they've targeted late September / early October as a realistic timeline to release the fix.

**Comment by bmckinney** [comment]
Just pushed a new gem for this workaround: ebsco-eds (0.3.6.pre)
