### ISSUE TITLE
EBSCO::EDS::BadRequest: {... "ErrorDescription"=>"Incorrect Number of Arguments", "ErrorNumber"=>"105"}

### ISSUE THREAD

**Issue by efrierson** [sul-dlss/SearchWorks#1619]
This is being tracked in the EBSCO Ruby Gem:
https://github.com/ebsco/edsapi-ruby/issues/65

This covers a few problems testing has hit, including:
mathematics education -> Geography facet value **Midwest (U.S.)**  (the parentheses need escaping)

Any facets with parentheses, commas, or colons need to have those characters escaped with a backslash.  This is something our Gem will handle.  I will make a note to resolve this issue when we resolve it there.

**Comment by drh-stanford** [comment]
@bmckinney it looks like using 0.3.6.pre fixes this problem, right?
