### ISSUE TITLE
Government Documents Facet Error

### ISSUE THREAD

**Issue by efrierson** [sul-dlss/SearchWorks#1620]
EBSCO Case #2836485.  I will update with a Service Issue number once I have one.

Description:
1. Search for something in SearchWorks.
2. Limit to the Government Printing Office Catalog in the Content Provider facet.
3. Limit to the Government Documents source type.
4. Remove the GPO Catalog in the Content Provider.
Error.

We've duplicated this.  

Diagnosis: 

This is expected behavior. The issue here is that the Single-db Source Type (STS) called "Government Documents" rolls up to the Multi-db Source Type (MSTS) called "Primary Source Documents." When you select the single database EDSGPR, the single-db STS "Government Documents" is displayed. When you select more than one database, then the MSTS kicks in and "Primary Source Documents" is displayed, which includes Government Documents, along with legal documents and other primary source documents.
 
What I need to find out is why we don't have a MSTS call "Government Documents" in EDS. I think there is one in the Ehost interface. And the FAQ below says that EDS is supposed to have it. This should be fixed, and it might be an easy fix in admin - will keep you posted.

https://help.ebsco.com/interfaces/EBSCO_Discovery_Service/EDS_FAQs/content_included_in_EDS_Source_Types

**Comment by jvine** [comment]
Gov Docs source type seems to have been removed from native UI; I can't reproduce this issue in SW or native UI.
