### ISSUE TITLE
Curriculum sub-location facet for Cubberley

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/SearchWorks#1635]
https://jirasul.stanford.edu/jira/browse/SW-1638

Example record: 
https://searchworks.stanford.edu/view/9725966 

999 
a| QA107 .B47 2000 V.1A w| LC c| 1 i| 36105219836918 d| 12/20/2016 e| 12/6/2016 l| CURRICULUM m| EDUCATION n| 4 r| Y s| Y t| STKS-MONO u| 10/3/2012 

library = EDUCATION 
home loc = CURRICULUM

**Comment by jvine** [comment]
Indexing complete; see #1880 for UI implementation.
