### ISSUE TITLE
Add "Report a connection problem" to the sub nav bar

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1640]
### LInk
Add "Report a connection problem" link to the right side of the dark sub nav bar. 
`font-size: 1.1em` so the text is not as large as "Library services".

![report - menu option](https://user-images.githubusercontent.com/6945691/29692155-7df7a698-88e3-11e7-9268-d4c526273989.png)

### Form
Clicking the option opens a slider below the nav bar, above the remaining page content. 
- Form is in a box that is right aligned in that space so it's associated with the link itself. 
- If the user is logged in, can we autofill their name and email? 
- Form needs to secretly capture the users OS and IP address. 
  - note that load-balancing seems to mess with the IP address. this is a problem for the support staff... 

![report - slide-down](https://user-images.githubusercontent.com/6945691/29692301-1aff1066-88e4-11e7-84b4-d70f3f1fc9ff.png)

### Completion
Slider is closed, flash message appears in it's place.
![report - success](https://user-images.githubusercontent.com/6945691/29692516-5ee7b00c-88e5-11e7-8098-c64d91e42b32.png)

**Comment by drh-stanford** [comment]
Is this for both catalog and articles+? or just articles+?

**Comment by jvine** [comment]
Just articles+

**Comment by mejackreed** [comment]
@jvine should the email being sent go to a different address or should it be the same address?

**Comment by jvine** [comment]
@mejackreed, just looked this up on the website and it's like this:

To:  sul-conprob@lists.stanford.edu
From:  user's email
Subject:  Connection problem: [Name of resource]

Can we do the same?

**Comment by mejackreed** [comment]
We can do something similar, yep!
