### ISSUE TITLE
Change "articles" to "articles+" in text

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1643]
(not in the URL!)

General feedback that "articles" is not sufficiently expressive of the contents. Several other universities have gone with "articles+" which... at least indicates there's more than articles. Several reviewers have suggested this as well. 

Affects:

- [x] dropdown toggle in nav bar
- [x] link text in dropdown
- [x] page title
- [x] h2 text on result page (#1600 - ticket already updated)
- [x] home page text
- [x] bento section title (ticket in [sul-bento-app#11](https://github.com/sul-dlss/sul-bento-app/issues/11))

**Comment by camillevilla** [comment]
hi @jvine! Do you want specific changes to "Find journal articles and other e-resources" or can that work be included in #1599?

I've opened a ticket in the [sul-bento-app repo](https://github.com/sul-dlss/sul-bento-app/issues/11) for the section title change.

**Comment by jvine** [comment]
No change to the "Find journal articles and other e-resources" heading.
