### ISSUE TITLE
SFX menu not connecting for some articles

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1647]
possibly related to foreign-language? The SFX menu (All available sources) doesn't appear for some records - immediately gives "Unable to connect to SFX" even though the "Best source" link works. (i.e. SFX is up)

Doesn't work:
- https://sw-article-preview.stanford.edu/articles/edssci__edssci_S1665_05652016000200239
- https://sw-article-preview.stanford.edu/articles/edsarl__edsarl_16712927_201401_201403270039_201403270039_1_17

Works:
- https://sw-article-preview.stanford.edu/articles/edsswe__edsswe_oai_DiVA_org_umu_134820
- https://sw-article-preview.stanford.edu/articles/edsswe__edsswe_oai_DiVA_org_lnu_32402

**Comment by jkeck** [comment]
Yeah, we're getting a `URI::InvalidURIError` when making the request.  We probably need to escape the sfx URL in some way.

**Comment by jkeck** [comment]
Also seeing the same thing w/ edscqv__edscqv.671796970
