### ISSUE TITLE
Rename webauth login path

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/SearchWorks#1649]
Since we won't be using webauth anymore.

checklist via @cbeer:

- [x] figure out what to call the route
- [x] duplicate e.g. https://github.com/sul-dlss/puppet/blob/production/hieradata/project/sw-webapp-prod.eyaml#L89-L95 with a new directory entry for the new route
- [x] update the code, change the route name, update the controller if it has webauth in there somewhere etc
- [x] deploy it
- [x] remove the old route

**Comment by mejackreed** [comment]
Per @jkeck nothing we need to modify beyond current implementation.

No issue w/ Articles+

**Comment by thatbudakguy** [comment]
affected boxes (found via [code search](https://github.com/sul-dlss/puppet/search?p=3&q=%2Fwebauth%2F)):

- sw-webapp-stage
- sw-webapp-prod
- sw-webapp-sandbox-a
- sw-webapp-sandbox-b
- sw-webapp-sandbox-c
- sw-webapp-sandbox-d
- sw-webapp-sandbox-e
- sw-webapp-sandbox-f
- sw-webapp-sandbox-g
- sw-webapp-bot-a
- sw-webapp-bot-b
- requests-folio-dev
- requests-stage
- requests-dev
- requests-prod
- library-hours-dev
- library-hours-prod
- exhibits-prod-a
- exhibits-prod-b
- exhibits-stage-a
- exhibits-stage-b
- libsys-webforms-prod
- libsys-webforms-dev
- libweb-app-stage-a
- libweb-app-test-a
- libweb-app-prod-b
- libweb-app-prod-a
- sul-h2-qa
- sul-h2-stage
- sul-h2-prod

**Comment by thatbudakguy** [comment]
any arguments against just using `/login`? if so, maybe `/sso/login`?
