### ISSUE TITLE
Facet examples still giving "something went wrong" errors

### ISSUE THREAD

**Issue by snydman** [sul-dlss/SearchWorks#1654]
DUPLICATES https://github.com/ebsco/edsapi-ruby/issues/72

https://sw-article-preview.stanford.edu/articles?f%5Beds_search_limiters_facet%5D%5B%5D=Stanford+has+it&q=%22%E5%9C%B0%E6%96%B9%E6%94%BF%E5%BA%9C%22+%E6%94%B9%E9%9D%A9&search_field=search
Click on Database > China/Asia On Demand

https://sw-article-preview.stanford.edu/articles?f%5Beds_search_limiters_facet%5D%5B%5D=Stanford+has+it&q=hearing+water+quality&search_field=search
Click on Publisher > national archives & records service, office of the federal register

https://sw-article-preview.stanford.edu/articles?f%5Beds_language_facet%5D%5B%5D=english&f%5Beds_search_limiters_facet%5D%5B%5D=Stanford+has+it&f%5Beds_subject_topic_facet%5D%5B%5D=avatar+%28film%29&q=film+review+avatar&search_field=search
Click on Topic > cameron, james, 1954-
(or any of the names with dates attached, in the Topic facet)

**Comment by drh-stanford** [comment]
The specific EDS error message is:

```
EBSCO::EDS::BadRequest: {"DetailedErrorDescription"=>"", "ErrorDescription"=>"Incorrect Number of Arguments", "ErrorNumber"=>"105"}
```

**Comment by jvine** [comment]
Added this example to the Ebsco issue as well:

Is this case related to the character escaping issue?

https://sw-article-preview.stanford.edu/articles?f%5Beds_search_limiters_facet%5D%5B%5D=Stanford+has+it&q=children%27s+literature&search_field=search

Facet Topic > children's literature shows 280,420 but when you select it you get 3 results.

**Comment by bmckinney** [comment]
Unlikely to be a character escaping issue since they typically throw errors instead of continuing.

Was unable to replicate using standard blacklight:

![screen shot 2017-08-31 at 9 21 41 am](https://user-images.githubusercontent.com/509381/29925314-f4e98d26-8e2d-11e7-9e21-9f8391c7a1c3.png)

**Comment by drh-stanford** [comment]
it's possible that the Topic > children's literature problem is related to https://github.com/sul-dlss/SearchWorks/issues/1669, but i'm not sure

**Comment by bmckinney** [comment]
Unable to replicate with latest build. Can you screencast steps to reproduce, we must be missing something?

![screen shot 2017-09-05 at 9 03 54 am](https://user-images.githubusercontent.com/509381/30062487-58eb2d2c-9219-11e7-8a6d-9da7672d5ca8.png)

**Comment by jvine** [comment]
@bmckinney I'm not able to reproduce it either.

**Comment by jvine** [comment]
Unable to reproduce any of these examples, no new reports.
