### ISSUE TITLE
Update catalog mastheads for Databases, Selected article databases

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1658]
both have references to article searching and connecting from off campus that's out of date.

**Comment by jvine** [comment]
Structure is:
1. `<h1>Masthead title</h1>`
2. `<p>one or more paragraphs of text</p>`
3. flexbox grid of links and help text that create a row on desktop; wrap on mobile
4. for Databases only:  `<h2>Filter by database title</h2>`  +  [A-Z index]

Note the grid layout will be used in other mastheads as well. 

### Selected databases

```
<h1>Selected article databases</h1>
<p>Start your research with one of our selected databases below. <a href="https://library.stanford.edu/guides/find-articles">Learn more about finding articles</a>.</p>
<div class="flexgrid">
<div><a href="/articles">Articles+</a><span>Search a combined index of 100s of databases.</span></div>
<div><a href="/databases">Databases</a><span>Find a topic-specific database for in-depth research.</span></div>
<div><a href="https://library.stanford.edu/using/connecting-e-resources">Connecting to e-resources</a>
<br>
<a href="https://library.stanford.edu/ask/email/connection-problems">Report a connection problem</a></div>
</div>
```
<img width="1185" alt="screen shot 2018-09-19 at 6 04 38 pm" src="https://user-images.githubusercontent.com/6945691/45790081-f7b72c00-bc37-11e8-8b1e-b4c75ae9e16a.png">

### Databases

```
<h1>Databases</h1>
<p>Find a topic-specific database for in-depth research.</p>
<p>Licensed resources are for the non-profit educational use of Stanford University. Use of these resources is governed by copyright law and individual license agreements. Systematic downloading, distributing, or retaining substantial portions of information is prohibited.</p>

<div class="flexgrid">
<div><a href="/articles">Articles+</a><span>Search a combined index of 100s of databases.</span></div>
<div><a href="/selected_databases">Selected article databases</a><span>Not sure where to start? Try one of these.</span></div>
<div><a href="https://library.stanford.edu/using/connecting-e-resources">Connecting to e-resources</a>
<br>
<a href="https://library.stanford.edu/ask/email/connection-problems">Report a connection problem</a></div>
</div>
```
<img width="1190" alt="screen shot 2018-09-19 at 6 25 03 pm" src="https://user-images.githubusercontent.com/6945691/45790389-7c567a00-bc39-11e8-9f19-ccc80d39a25b.png">

**Comment by camillevilla** [comment]
hiya @jvine! Can I get some clarification re: `4. for Databases only: <h2>Filter by database title</h2> + [A-Z index]`

It looks like A-Z filter was removed 2 days ago (hasn't been shipped yet):
https://github.com/sul-dlss/SearchWorks/issues/1952

**Comment by jvine** [comment]
Uh oh. Well that explains why you can't see it. That was supposed to be an open question, and a separate ticket was created for it. From analytics, it looks like the answer is no. A-Z filter should remain.

**Comment by camillevilla** [comment]
Notes: 
- Part of #1953 should be reverted so that A- Z filter still appears
- A - Z filter is currently under study. For this first phase, we are waiting to see whether users continue to use A - Z filter once results are relevance sorted by default. 
- title filters should remain title sorted
