### ISSUE TITLE
Visual design/branding for Bento home

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1660]
tbd.

**Comment by camillevilla** [comment]
@jvine can I move this over to [sul-bento-app](https://github.com/sul-dlss/sul-bento-app)?

**Comment by jvine** [comment]
Yes! sorry.

**Comment by camillevilla** [comment]
Migrated to [sul-bento-app#12](https://github.com/sul-dlss/sul-bento-app/issues/12)
