### ISSUE TITLE
Add "publication status" to article metadata on detail page

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1661]
Articles with pub status "preprint" are not indicating this in the metadata in SW. 

Example in native UI

https://stanford.idm.oclc.org/login?url=http://search.ebscohost.com/login.aspx?direct=true&db=edsstc&AN=946928&site=eds-live

https://sw-article-preview.stanford.edu/articles/edsstc__946928

Native UI shows it's a preprint.

**Comment by bmckinney** [comment]
Added to 03.8.pre gem.

**Comment by jvine** [comment]
Can we add this to the record view now?
