### ISSUE TITLE
Linked subject searches not working

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1664]
Example search:

https://sw-article-preview.stanford.edu/articles?utf8=%E2%9C%93&search_field=search&q=Helping+the+Rich+get+Richer%3A+A+Re-assessment+of+the+Income+Distributional+Trend+in+Hong+Kong

Review the subjects in the result view:
- multiple subdivisions with `--` separators
- several `&`s

On the result page;
https://sw-article-preview.stanford.edu/articles/bas__BAS899713

- the `&`s show as `&amp;` and are searched as such
- none of the linked subjects gets a search result. Should at least get the current record?
- author-provided keywords do get a result.
- removing the punctuation doesn't affect the result.

**Comment by drh-stanford** [comment]
> what is the difference between these field codes? `SU`, `SH`, and `DE`... i'm trying to debug this issue -- https://github.com/ebsco/edsapi-ruby/issues/76


From Eric:

> They represent different searchable indexes in EDS.  This is the issue where you have a <searchLink> tag that includes a fieldCode attribute that should specify which index to search if you want to click on the text of the <searchLink>.

> Where we struggled a couple of weeks ago is what to do about it in SearchWorks.  We have many different indexes to search, and they may or may not be overlapping.  For example, DE and SU have some overlap, but it looks like in this example, SH is not overlapped by DE or SU (evidenced by lack of results when trying to search for known text in those indexes).

> I think the decision earlier was to simply use the most broad subject search index possible - SU (? - maybe it was DE?) for all clickable subject headings.  This will lead to problems in this example where the subject heading is actually in the SH index, not in the others.

> Part of the reasoning (I think) for not going with the specified fieldCode included in the <searchLink> tag was that it could be any of an unknown number of field codes, meaning making a dropdown list to the left of SearchWorks include all of the possible options impossible.

> I would recommend (but this is a design decision, and only IMO) using the <searchLink> attribute fieldCode to determine what the search should be when a user clicks on a Subject Heading.  This means you won't have a dropdown to the left of the search box that is comprehensive.  Instead, when the <searchLink> suggests a fieldCode that isn't mapped to a dropdown option, it would show a search link this (screenshot coming):

<img width="796" alt="screen_shot_2017-09-05_at_9 05 29_am" src="https://user-images.githubusercontent.com/1861171/30073866-440cd4ea-9224-11e7-97a7-a7170c30a763.png">

**Comment by drh-stanford** [comment]
EDS 0.3.9.pre gem adds `searchLinks` to the `eds_subjects` field:

![screen shot 2017-09-05 at 12 32 01 pm](https://user-images.githubusercontent.com/1861171/30079814-59fca9a8-9236-11e7-9e78-6170f4012fff.png)

**Comment by drh-stanford** [comment]
For descriptions of `SU` and `DE` see https://help.ebsco.com/interfaces/EBSCOhost/EBSCOhost_FAQs/Searching_with_Default_Search_Fields

**Comment by drh-stanford** [comment]
@jvine @jkeck @efrierson @bmckinney Ok, so I've tried a few things and paired up with @mejackreed to review these attempts. The core problem, as Eric mentions above, is that the EDS API  returns different EDS fieldCode for the subjects. For example,

- SH Hong Kong
- SU Hong Kong
- DE Hong Kong
- KW Hong Kong

are all valid "subject" searches that might be returned in the the subjects data for a hit (that includes subjects, person subjects, geographic subjects, and author supplied keywords), and they yield different results. That said, I don't think the *Topic facet* is also doing what we expect for the same reason as the subject linking problem -- the lack of a union API for multiple field codes.

What I've done thus far is use the fieldCodes (in the latest EDS gem), to generate the subject links, and it looks like this:

![screen shot 2017-09-06 at 1 56 08 pm](https://user-images.githubusercontent.com/1861171/30134235-4778e87a-930b-11e7-9dea-6e3065568372.png)
 
The link will query the correct fieldCode and the result set is what you'd expect for the most part. The *problem* is that I'm using a search field to implement it and that results in a UI change, like so:

![screen shot 2017-09-06 at 2 02 31 pm](https://user-images.githubusercontent.com/1861171/30134469-12af13fc-930c-11e7-9856-81e424ab5053.png)

So, that's where I'm at. The most straightforward approach requires that we surface these different EDS indexes to the user in the UI. What do you all think?

**Comment by bmckinney** [comment]
So the only reason you need to add these to the field list is because it needs to be there after a user clicks the searchLink? Could you populate the search box itself with 'DE:Hong Kong'?

**Comment by drh-stanford** [comment]
@bmckinney in our current UI, we want our breadcrumbs to look like this:
![screen shot 2017-09-06 at 2 18 17 pm](https://user-images.githubusercontent.com/1861171/30135054-41647596-930e-11e7-8cf4-3954e8fb3a08.png)

so the field codes are hidden to the user

**Comment by jvine** [comment]
Definitely DO NOT want to add the additional search codes to the dropdown list. We do have some search fields in SW catalog that appear for some linked searches but are not in the dropdown.

I'm looking into this further because I don't understand the full picture but please don't make any UI changes around this just now.

**Comment by jkeck** [comment]
@drh-stanford I believe we can configure separate "Subject" search drop-down types (with the same label and different search_field params) and simply have the different flavors configured to not be displayed (by setting `include_in_simple_select = false` in the controller config).


We have done this for certain search types in the catalog results such as our special author+title search fields (so there is precedence for going with this approach).

**Comment by drh-stanford** [comment]
@jkeck yes, i can disable them from the select pull-down. i tried doing that and it works ok (search works, breadcrumb works), but there's UI implications for that too I think. Namely that a user cannot issue that search themselves (i.e., type it into the search box) -- it has to be from the subject link. maybe that's ok, i'm not sure.
