### ISSUE TITLE
Home page links

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/SearchWorks#1676]
Some of the links on the home page are incomplete. See #1599.

**Comment by mejackreed** [comment]
Its unclear to me what is to be done. Is it "update link placeholders"? I'm not sure what that means either.

**Comment by drh-stanford** [comment]
We need to get a full list of the links in both homepages and update the views. Some of the links just go to http://library.stanford.edu/ when they should go to specific pages. This ticket shouldn't be marked ready until we have that list...

**Comment by jvine** [comment]
Articles+ only:
- [ ] **More about article access at Stanford Libraries** goes to https://library.stanford.edu/using/connect-campus
- [ ] **More article search tips** okay as-is, I will publish later today

Both:
- [ ] **All of the above** block needs to be suppressed until bento is available
- [ ] **Library website** should go to https://library.stanford.edu - website-specific search page is broken right now.
