### ISSUE TITLE
Articles+ should be linked on Catalog home page (and not Catalog)

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1680]
In the second half of the page:
- on Catalog, the Catalog link should be unlinked, and Articles+ should be linked. 
- on Articles+ the Articles+ link should be unlinked, and Catalog should be linked. 

Currently Articles+ is never linked and Catalog always is. 

Basically, the "active" state means yellow glow + you are here + unlinked, and all the other options are linked.

**Comment by jkeck** [comment]
Closed by #1691
