### ISSUE TITLE
Adjust responsive design of home pages

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1686]
### Articles top section
 - change `col-md-4` to `col-sm-4` and `col-md-8` to `col-sm-4` so the 2 col layout remains until phone 

**Tablet and phone**
![responsive tablet](https://user-images.githubusercontent.com/6945691/29986038-9464f32a-8f16-11e7-883d-e25d73ee2f4f.png) ![responsive phone](https://user-images.githubusercontent.com/6945691/29986039-946729c4-8f16-11e7-9d13-73d8e8991332.png)

### Both second section
- change `col-md-3` to `col-sm-3 col-xs-6` - so 3 col layout remains until phone, then goes to 2 col - never 1 col.
- add `class="hidden-xs"` to the `<p>` tag in the four panels, so the descriptive text disappears at phone size.

**Tablet and phone**
![responsive tablet 2](https://user-images.githubusercontent.com/6945691/29986462-49a17596-8f18-11e7-8f57-77f3cfe73332.png) ![responsive phone 2](https://user-images.githubusercontent.com/6945691/29986463-49a65f48-8f18-11e7-9974-983704e9eacf.png)

**Comment by mejackreed** [comment]
@jvine when you say:

> change col-md-4 to col-sm-4 and col-md-8 to col-sm-4 so the 2 col layout remains until phone

Should it be:

> change col-md-4 to col-sm-4 and col-md-8 to col-sm-8 so the 2 col layout remains until phone

```diff
- change col-md-4 to col-sm-4 and col-md-8 to col-sm-4 so the 2 col layout remains until phone
+ change col-md-4 to col-sm-4 and col-md-8 to col-sm-8 so the 2 col layout remains until phone
```

Instead?

**Comment by jvine** [comment]
@mejackreed yes, i think you're right. thanks for catching.

**Comment by mejackreed** [comment]
@jvine Because of the way that our "You are here" is implemented it affects how our responsive things stack up. I'll work on also fixing that.

![screen shot 2017-09-05 at 1 07 48 pm](https://user-images.githubusercontent.com/1656824/30073309-4ddf74ca-923b-11e7-87a6-6a69ba5be16f.png)
