### ISSUE TITLE
Date panel doesn't remain open when a range is applied

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1687]
Get a search result. Open the date panel. Select a range. Apply. Panel displays as closed as if no selection has been made. Seems like it should be open with green panel header?

**Comment by mejackreed** [comment]
The article behavior mimics the catalog behavior.. both aren't open. @jvine should they both be open?

**Comment by jvine** [comment]
For me, in both the preview catalog and the production catalog, the date facet remains open after a selection has been made. Only articles+ is closed.

**Comment by mejackreed** [comment]
Yikes.. my bad! I thought it was working differently for me.
