### ISSUE TITLE
HTML fulltext panel title displays when user is not authenticated

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/SearchWorks#1698]
The article record view displays an empty panel for EDS HTML fulltext when the user is not authenticated. 

<img width="1198" alt="screen shot 2017-09-05 at 11 43 21 am" src="https://user-images.githubusercontent.com/5402927/30081276-62b5bd5a-923b-11e7-992b-f3dbdd8392d6.png">

Possible fixes @jvine?
1. Hide panel title
2. Replace 'Hide full text' with 'Login to show fulltext >'

**Comment by jvine** [comment]
2:  "Log in to show full text >" (note spaces)
