### ISSUE TITLE
Add alternate (catalog/articles) bento-ish insert in search results

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1709]
Between the 3rd and 4th search result, add a mini bento-like insert that offers results from the alternate SW target.

From articles
![catalog mini bento](https://user-images.githubusercontent.com/6945691/30141244-eed21a4c-932e-11e7-9663-639380fcf799.png)

From catalog
![articles mini bento](https://user-images.githubusercontent.com/6945691/30141442-5e3745b4-9330-11e7-8347-caf220a86270.png)

Facet values - show 5, keep each `<a>` together so it doesn't split across a line.

At some future point, when Bento exists, will add a link to the All search at the bottom of the block.

**Comment by mejackreed** [comment]
Should this only be for a search term, or should it also try and match facets?

**Comment by mejackreed** [comment]
Sorry more questions.. What should happen in brief view? What should happen in gallery?

**Comment by jvine** [comment]
Good questions.

Brief view: can we insert as-is, same location between 3 and 4? No change to content. It's big and loud, and we may scale it back later, but for now we really want people to know it's there.

Gallery: what's possible/easiest? 

1. Can we insert it between first and second row of results or will that mess things up incredibly? 
2. Or since Gallery only applies to catalog... maybe just drop it at the bottom of the page? I mean, people who are looking for articles are likely not going to be in Gallery mode, and Articles+ itself doesn't have a Gallery mode. 

And btw, can we kill the "Looking for different results" box at the bottom of the catalog results as part of this? or should I make a separate ticket? This kind of replaces that functionality/intent.

**Comment by mejackreed** [comment]
Yes I think we can do all of that. Quick question, what should happen when it doesn't find anything? Should we tell the user that? (I'm leaning towards yet)

**Comment by jvine** [comment]
Hm. Agree that telling them no results is a good idea. The whole box is designed around "We found results" - so it would need a different message. I'll work on that.
