### ISSUE TITLE
Date slider disappears

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1721]
https://sw-webapp-sandbox-f.stanford.edu/articles?f%5Beds_content_provider_facet%5D%5B%5D=Academic+Search+Premier&f%5Beds_search_limiters_facet%5D%5B%5D=Direct+access+to+full+text&q=school+reform&search_field=search&sort=relevance

**Comment by efrierson** [comment]
I can duplicate the date slider issue, but I'm getting the database facet.  Can you confirm that the database facet is still not appearing for you?

<img width="986" alt="database_facet" src="https://user-images.githubusercontent.com/2488862/30251485-ae2a9a2e-9625-11e7-8fa1-a8e0ea3f213f.png">

**Comment by jvine** [comment]
@efrierson the issue in this ticket is only that the Date facet disappears when a Database facet is selected - Database facet doesn't disappear.

(BTW, we noticed on Friday that the DB facet is ORing again - which, after some testing, we think we like - but we're a bit concerned that it "just happened".)

**Comment by bmckinney** [comment]
@jvine I'm to blame for the "just happened" part - in my notes for the source type facet count fix, it also said to do the same for database providers if possible. I'll do better to communicate those changes going forward!

**Comment by bmckinney** [comment]
Is it possible to drive the date slider using date_range in the solr response instead of pub_year_tisim? If so, that should resolve it.

**Comment by jvine** [comment]
@bmckinney - ah okay, as long as it wasn't accidental!

**Comment by ahafele** [comment]
similar - https://jirasul.stanford.edu/jira/browse/SW-1945

**Comment by jvine** [comment]
The date slider disappears 

- when you facet by Database, Publisher, Journal title
- inconsistently when you click on Subject or Author links from a show page. I can't quite figure out the pattern; typically subjects with - or -- punctuation or diacritics will show no date facet; but then when you repeat the search (by just clicking the Search button on the results page) the date slider reappears.

**Comment by bmckinney-ebsco** [comment]
A suggested fix was discussed here with Jessie: https://github.com/ebsco/edsapi-ruby/issues/83

It would require a change on your end however.
