### ISSUE TITLE
Remove some options from the "All fields" dropdown

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1722]
- Author - ok
- Article title - rename to Title
- Subject - ok
- Journal title - rename to Journal/Source
- Abstract - remove
- Series - remove
- ISSN - remove
- ISBN - remove

Result
![screen shot 2017-09-07 at 4 47 33 pm](https://user-images.githubusercontent.com/6945691/30190416-d80cbcb6-93ee-11e7-86b8-3705ce58091e.png)

**Comment by camillevilla** [comment]
Is this different from #1711?

**Comment by jvine** [comment]
Um, no. Forgot I did that. Never mind.
