### ISSUE TITLE
Add a flash message to the home page of article search for Sept 11 launch

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1723]
to be removed on final release to prod.

Yellow alert with close button. Please override the `<p>` text to be black, not the dark yellow default.

```
<h2>Welcome to articles+ beta!</h2>
<p>This is a pre-release version of the new article search feature, still in active development. Small updates will be happening frequently over the next 2 weeks while we finish up details.</p>
<p>Feel free to explore, and please send feedback!</p>
```

**Comment by jkeck** [comment]
@jvine how does this look.

<img width="1213" alt="article-alert" src="https://user-images.githubusercontent.com/96776/30194217-a67285ec-9406-11e7-8568-53a496d99220.png">


I dropped the underline applied globally to our H2s but wasn't sure if the color was 👌
