### ISSUE TITLE
Change h4 to h3 on home pages

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1729]
Catalog - Featured resources section
Articles+ - How do I access articles? section
Both - Search Stanford's library resources section

`<h4>` should be `<h3>`

solves both a formatting and most of an accessibility issue (there's still a heading gap in the lower section; I'll resolve later).

**Comment by jvine** [comment]
(Grrr. Looks like this change will actually break formatting in the Search Stanford's library resources section of the Catalog page. Why are they different?)

**Comment by jkeck** [comment]
Closed by #1743
