### ISSUE TITLE
Finish hiding document type icons

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1735]
See #1710 - PR #1715 only does part of it. Still to do:

- [ ] suppress icons from record view 
`.blacklight-articles-show #document h1 .sul-icon { display: none;}`

Example with icon still present:
https://sw-article-preview.stanford.edu/articles/edscqv__edscqv.671796970

- [ ] change the outdent of the title in results
`#documents.article-search-results .document h3.index_title {text-indent: -22px;}`

**Comment by jkeck** [comment]
Closed by #1744
