### ISSUE TITLE
Enable gzip for content files

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/SearchWorks#1746]
In smoke testing SearchWorks, I noticed that we aren't enabling (or have configured correctly) gzip compression (mod_deflate) on SearchWorks. The same is true for Exhibits and EarthWorks (I haven't checked other applications). This analysis assumes that our Apache configuration is not gzipping content (I'm pretty sure it is not), but it is definitely not sending the correct header if it is `Content-Encoding: gzip`.

Enabling this in Apache for SearchWorks would reduce downloadable content by 902 KB for a homepage load.

Uncompressed resource URL | Original | GZIP Savings
-- | -- | --
/assets/application-1d09125….js | 589 KB | 421 KB (72%)
/assets/application-7410305….css | 272 KB | 222 KB (81%)
/assets/print-8a96cbc….css | 263 KB | 213 KB (81%)
/ | 45 KB | 34 KB (76%)
/page_context.js | 11 KB | 8 KB (74%)
/style.css | 3 KB | 2 KB (71%)
data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJdmFyIG5v… | 3 KB | 2 KB (63%)

This small change could have significant impact in SearchWorks performance. I'm noticing ~500ms content download times for `application...css` and around 1.5s content download time for `application...js`.

Now the browser should be caching this after first load, but enabling this cache could save browser caches ~1MB and potentially speed up first load users.

**Comment by mjgiarlo** [comment]
Per https://github.com/sul-dlss/operations-tasks/issues/1325#issuecomment-494528569:

>...this has now been added everywhere

So, closing!
