### ISSUE TITLE
Searchbar overlaps with the menu bar in mobile view

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/SearchWorks#1751]
This screenshot was taken in Chrome on an iPhone.
![overlapping search bar and menu bar](https://user-images.githubusercontent.com/5402927/30287936-c8c8b79c-96db-11e7-9e1c-28a0d788d143.PNG)

**Comment by saseestone** [comment]
I checked Google Chrome today and can't see the overlapping....
