### ISSUE TITLE
Bento results linking

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/SearchWorks#1753]
The results for bento has links to the content. 

We may need to extend the Blacklight JSON results presenter in order to provide our pre-formatted links so that we don't have to duplicate the logic in the bento app.

If this ends up getting extremely complicated we can drop the links and just allow the user to go to the document/result to get the link.

**Comment by mejackreed** [comment]
So is the gist of this to link results to actual content? For example, an article results could link to the "actual article" instead of the show page in SearchWorks?

**Comment by drh-stanford** [comment]
Yes, this is for the full text links. There's a lot of logic in the SW code to choose and format the links (`EdsLinks::FulltextLink`), and that's not surfaced in the JSON API.
