### ISSUE TITLE
Still showing details on record view in guest mode?

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1758]
Is this intentional?

https://searchworks.stanford.edu/articles/eoh__1643501

**Comment by jvine** [comment]
Search 
> SU gender equality education

![screen shot 2017-09-11 at 3 23 29 pm](https://user-images.githubusercontent.com/6945691/30299603-4ad2b73c-9705-11e7-8f90-fd30b8bda2fa.png)
![screen shot 2017-09-11 at 3 23 15 pm](https://user-images.githubusercontent.com/6945691/30299607-4c40d40a-9705-11e7-8e42-7f338acf123c.png)

**Comment by jkeck** [comment]
@jvine It is intentional in the fact that it's default blacklight behavior.  If you can get to the record and the record had metadata, we'll display it.

That being said, if you would like us to not render this metadata under this circumstance we can definitely do that.

**Comment by drh-stanford** [comment]
I would think that the EDS API would not return the DOI or ISSN for restricted guest results. So, I think we should at least let them know it's an issue with their gem. We can omit the entire Details section for restricted articles though as Jessie mentions.

**Comment by jvine** [comment]
yeah, i think EDS should be suppressing this metadata on their side. i thought it had been discussed previously - is it still in the queue?

**Comment by drh-stanford** [comment]
i don't remember this coming up and i didn't see it listed in their queue, so i added it to the EDS gem issues here https://github.com/ebsco/edsapi-ruby/issues/77

**Comment by drh-stanford** [comment]
@jvine Bill confirmed that it's up to the database source on which fields they want to show in guest mode. i guess in this particular case, the DOI and ISSN are visible in guest mode. do you want us to suppress this information entirely, or leave as-is?

**Comment by jvine** [comment]
If we can suppress it without side effects, I'd rather do that. To me, even if it's legit/approved, it looks like an accidental security error.
