### ISSUE TITLE
[SearchWorks/production] ActionView::Template::Error: undefined method `-' for {"0"=>"md903dt5665"}:ActiveSupport::HashWithIndifferentAccess

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/SearchWorks#1776]
## Backtrace

    line 4 of [PROJECT_ROOT]/app/views/catalog/_constraints.html.erb: _app_views_catalog__constraints_html_erb___2361731575814304696_46772020
    line 3 of [PROJECT_ROOT]/app/views/catalog/_index.html.erb: _app_views_catalog__index_html_erb__4367906936148125175_46546900
    line 2 of [PROJECT_ROOT]/app/views/catalog/index.html.erb: _app_views_catalog_index_html_erb__757952423260933036_46453700

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50022/faults/33184961)

**Comment by jcoyne** [comment]
This is tracked upstream at https://github.com/projectblacklight/blacklight/issues/1784

**Comment by jcoyne** [comment]
Fix is available https://github.com/sul-dlss/SearchWorks/issues/1785 but needs to be backported.
