### ISSUE TITLE
Research Starters: Back to results link switches from articles+ to catalog

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/SearchWorks#1787]
In one of the Open Labs, we saw this behavior.

1. In Articles+, run a search
2. View the detail page of one of the results
3. Click "Back to results"
4. Arrive at the catalog results (not the Articles+ result set as expected)

**Comment by jkeck** [comment]
This is not my experience following these steps.  There is speculation that there were multiple search sessions open in tabs and the "Back to results" link was for a catalog result (which is a known issue with Blacklight's session tracking functionality).

**Comment by drh-stanford** [comment]
Ok, then it's likely due to the Blacklight behavior tracking. Closing...

**Comment by drh-stanford** [comment]
I'm actually seeing this behavior without having multiple tabs/searches open. I haven't been able to reliably reproduce it though.

**Comment by drh-stanford** [comment]
Hmm, it happens reliably on topic guides:

1. Search for "entertainment industry"
2. Click the topic guide
3. Notice it's hit 21 of 464,860
4. Click Back to results
5. Notice you're in a catalog search

**Comment by jkeck** [comment]
So while this isn't multiple tabs, it is a similar issue (that it's falling back to previous search session).

What we could do is update where we link in [this partial](https://github.com/sul-dlss/SearchWorks/blob/master/app/views/articles/_research_starters.html.erb#L12) to use the `link_to_document` helper.  We typically have to pass a count, and I'm not sure what that should be in this context (0, -1?), but I believe could at least place the user at the beginning of the search.

**Comment by drh-stanford** [comment]
We don't have a Solr document for the helper at that point. Should we query Solr to get that document (the research starter) or fake a document to pass to the helper?

**Comment by jkeck** [comment]
@drh-stanford I think a fake doc is the best bet.  I submitted a PR to do that.
