### ISSUE TITLE
Topic Facet returns 0 results when () in term

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/SearchWorks#1800]
ie gothic fiction (literary genre)

https://searchworks.stanford.edu/articles?f%5Beds_search_limiters_facet%5D%5B%5D=Direct+access+to+full+text&f%5Beds_subject_topic_facet%5D%5B%5D=gothic+fiction+%28literary+genre%29&q=marie+corelli&search_field=search

https://jirasul.stanford.edu/jira/browse/SW-1863

**Comment by ahafele** [comment]
also an issue for --

**Comment by bmckinney** [comment]
@ahafele fixed with latest gem update, please confirm

**Comment by jvine** [comment]
Appears to be working in prod.
