### ISSUE TITLE
Publisher Facet returning 0 results

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/SearchWorks#1801]
Related to 
[https://github.com/sul-dlss/SearchWorks/issues/1800](url)?

https://searchworks.stanford.edu/articles?f%5Beds_publisher_facet%5D%5B%5D=national+archives+%26+records+service%2C+office+of+the+federal+register&f%5Beds_search_limiters_facet%5D%5B%5D=Direct+access+to+full+text&q=hearing+water+quality&search_field=search

https://jirasul.stanford.edu/jira/browse/SW-1866

**Comment by bmckinney** [comment]
@ahafele fixed with latest gem update, please confirm

**Comment by jvine** [comment]
Appears fixed; also closed in JIRA
