### ISSUE TITLE
Strange Geography facets

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/SearchWorks#1813]
And none of them seem to return any results

https://searchworks.stanford.edu/articles?q=%22Derrida%2C+Jacques+%281930-2004%29.%22&search_field=author

https://jirasul.stanford.edu/jira/browse/SW-1893

**Comment by bmckinney** [comment]
This is metadata coming from a partner database (PORBASE), @efrierson and I will open a Service Issue for this.

Example (https://searchworks.stanford.edu/articles/edspor__edspor.1804268):
<Item>
        <Name>Subject</Name>
        <Label>Subject Geographic</Label>
        <Group>Su</Group>
        <Data>&lt;searchLink fieldCode="DE" term="%2219+DERRIDA%2C+por%22"&gt;19 DERRIDA, por&lt;/searchLink&gt;</Data>
      </Item>

**Comment by bmckinney** [comment]
EBSCO Case: #2890509

**Comment by jvine** [comment]
The odd values do return results now - is this just a vendor metadata issue and can be closed?
