### ISSUE TITLE
Update latest EDS gem 

### ISSUE THREAD

**Issue by snydman** [sul-dlss/SearchWorks#1819]
This should resolve https://github.com/sul-dlss/SearchWorks/issues/1800 and related, as well as current pagination issues.  

The flag to apply case tense for language and geography facets should be turned OFF - that is we want no change to the way those facets are displayed at this time.

**Comment by drh-stanford** [comment]
Need to verify that update doesn't break facets

**Comment by jkeck** [comment]
Status update: It looks like 0.3.17.pre introduced a change that broke our articles home page (e.g. only was an issue when no query params were sent in).

I have submitted ebsco/edsapi-ruby#84 to address that issue.  We'll need to wait until that is resolved and released before we can move forward with an update.

Other than that, the rest of the results/record look good and the facets are not title-ized by default.
