### ISSUE TITLE
Date facet does not show up

### ISSUE THREAD

**Issue by trapido** [sul-dlss/SearchWorks#1824]
There is no date facet for this search:

https://searchworks.stanford.edu/articles?utf8=%E2%9C%93&f%5Beds_search_limiters_facet%5D%5B%5D=Direct+access+to+full+text&search_field=search&q=translanguaging

**Comment by jvine** [comment]
Appears fixed.

<img width="728" alt="screen shot 2018-06-19 at 4 44 39 pm" src="https://user-images.githubusercontent.com/6945691/41629762-1aff7fc8-73e0-11e8-8279-f9742050c154.png">
