### ISSUE TITLE
Handle a lack of a location code translation better in FindIt links

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/SearchWorks#1871]
When a FindIt link is rendered for a location code that we don't have a translation for, the link appears to be rendered instead.  We should handle this more gracefully.

<img width="389" alt="6538332" src="https://user-images.githubusercontent.com/96776/39939057-da92e5be-5509-11e8-9920-1fe5be6e67f7.png">

**Comment by dnoneill** [comment]
Might be able to be closed due to Folio migration?
