### ISSUE TITLE
[SearchWorks/prod] Parslet::ParseFailed: Extra input after last repetition at line 1 char 15.

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/SearchWorks#1873]
## Backtrace

    line 10 of [PROJECT_ROOT]/lib/blacklight_advanced_search/parsing_nesting_parser.rb: block in process_query
    line 9 of [PROJECT_ROOT]/lib/blacklight_advanced_search/parsing_nesting_parser.rb: each
    line 9 of [PROJECT_ROOT]/lib/blacklight_advanced_search/parsing_nesting_parser.rb: process_query

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50022/faults/34768787)

**Comment by jkeck** [comment]
Duplicate of #2461
