### ISSUE TITLE
Add SFX menu to record view when "@find full text" is present

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1882]
See articles+ for previous implementation.

- When a record has an SFX link, embed the "Online full text" portion of the SFX menu directly in the record view.
  - https://searchworks.stanford.edu/view/12137603
  - https://searchworks.stanford.edu/view/3195844
- Include targets with `<service_type>getFullTxt</service_type>` and `<is_related>no</is_related>`
- For catalog records, add `<coverage_statement>` to the display (not needed in articles+). There can be more than one coverage statement - each should be on a separate line.
- No change to search results.

## Current display

<img width="369" alt="screen shot 2018-06-19 at 12 56 50 pm" src="https://user-images.githubusercontent.com/6945691/41620998-45cd3c24-73c0-11e8-9d1e-b647423742a2.png">
<img width="368" alt="screen shot 2018-06-19 at 12 08 33 pm" src="https://user-images.githubusercontent.com/6945691/41621008-4ca8c982-73c0-11e8-8bdc-d19e6f7999d8.png">

## Expected display

<img width="382" alt="screen shot 2018-06-19 at 11 41 59 am" src="https://user-images.githubusercontent.com/6945691/41621036-60fd038a-73c0-11e8-89d6-15187ae01272.png">

**Comment by jvine** [comment]
TBD:
- truncate long target lists?
- suppress Google link for journals, since it selects 1 random volume or issue?

**Comment by saseestone** [comment]
Check in on if Google preview is required if we're using Google cover images.  Sarah will check in with DO.

**Comment by jkeck** [comment]
@jvine is this a useful feature to have w/o suppressing the Google preview link, or does suppressing that link block us moving forward on implementing the SFX panel for MARC records?

**Comment by jvine** [comment]
Not blocked. SFX menu is very useful regardless of the Google link; the link itself adds noise and is not useful but can be handled separately.
