### ISSUE TITLE
Update dependencies for searchworks

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/SearchWorks#1887]
In preparation for SW Performance monitoring & analysis.

TODO:
- [ ] Update to rails 5.2.0 (or latest) (@camillevilla #1892)
- [x] Update to Blacklight 6.15.0 (or latest) [@jkeck looking into this]
  * #1894 
- [ ] Update all other dependencies (which theoretically shouldn't need action) (@camillevilla #1892)

**Comment by jkeck** [comment]
Happy to pair up w/ somebody on this.  I have gone through this process once or twice trying to do normal dependency updates and bailed (with simply updating vulnerable dependencies and moving on).
