### ISSUE TITLE
Update blacklight configuration to avoid using solr local parameters syntax for non-lucene queries

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/SearchWorks#1890]
Local parameters are certainly used as part of the search fields:

https://github.com/sul-dlss/SearchWorks/blob/master/app/controllers/catalog_controller.rb#L202-L305

(and can probably be trivially replaced with regular URL parameters?)

Also, identify anywhere else local parameter queries are produced.

**Comment by mejackreed** [comment]
Also here: 
 - https://github.com/sul-dlss/SearchWorks/blob/master/lib/blacklight_advanced_search/parsing_nesting_parser.rb#L18

**Comment by cmh2166** [comment]
Requires https://github.com/sul-dlss/sul-solr-configs/issues/151

Before that, this should be updated to use latest Solr config changes
