### ISSUE TITLE
Set up environment for SW Index review environment

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/SearchWorks#1904]
Set up environment for relevancy delta review by identified super users. Environment should include Searchworks pointing to the appropriate Solr Index (with the proposed changes).

Try to use `sw-webapp-sandbox-f.stanford.edu` (has sul-solr already). Presume dev index will be on sul-solr.

* Get different alias for this box.
* Get latest version of SW app on this
* Use config as part of deploy to point to dev index

**Comment by cbeer** [comment]
sw-webapp-sandbox-e.stanford.edu is pointing to the sw-relevancy index on sw-solr.
sw-webapp-sandbox-f.stanford.edu is pointing to the searchworks-dev index on sul-solr.

**Comment by cbeer** [comment]
Done, pending DNS refresh.
