### ISSUE TITLE
Define "Super Users Group" for relevancy delta review & feedback

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/SearchWorks#1906]
See https://github.com/sul-dlss/SearchWorks/issues/1905

This is only for the SW Performance & Indexing work cycle.

**Comment by ahafele** [comment]
- Gryphon Search 
  Vitus
  Kay
  Arcadia
  Kevin
- Irina
- Stella
- Phyllis
- EAL (Alissa checking on who)

@snydman Agreed?

**Comment by snydman** [comment]
This group seems like a good start.  I'd like to give them 5 days.  And of course we need to inform and recruit them.  When do we think we will want this testing done?

**Comment by cmh2166** [comment]
@snydman With 1 week for review sessions, I propose we need to let a few updates accumulate in dev environment before sending & ensure there is unblocked work during. Guessing it will be at least 1-2 weeks out before we try to get feedback. We should probably wait on feedback until we've acted on some Solr epics like: 
* solr config changes as needed
* possibly moving SW Index to sul-solr 
* getting SW Index on updated version of Solr if not the final version of Solr

This review week should leave index pipeline rewrites open for work in tandem. I think it could partially block Searchworks App performance tuning since what index we are working with might effect parts of this.

@cbeer thoughts?

**Comment by cmh2166** [comment]
Discussion of when / how to approach, recruiting, etc. happening offline in standups + elsewhere. List confirmed so closing.
