### ISSUE TITLE
health check for sul-sfx

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/SearchWorks#1915]
?

**Comment by camillevilla** [comment]
8/23: Alexis confirmed that we use a locally hosted instance of SFX. She put me in touch with Suzette and Sandy to figure out whether there's an existing health check endpoint.

**Comment by mejackreed** [comment]
It looks like to me that we are only checking disk with no HTTP health check. https://github.com/sul-dlss/puppet/blob/production/hieradata/node/sul-sfx.stanford.edu.eyaml#L29

Closing this issue as I don't think its further actionable.
