### ISSUE TITLE
SW Solr Users feedback: Confirm boolean etc. search behaviors in Solr 6.6.1

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/SearchWorks#1918]
Confirm AND and * etc functions same or differently in Solr 6.6.1 (indicate they are the same or document how they change). This is to address concerns around the following issues:

- Interesting that this record comes up #23  in the search for science AND relig* limiting to Topic: Philosophy, and #29 in the current application. I will  go back and compare results to see why this makes sense after I send you this feedback 
- This is the first search Ive done where the results from current Searchworks made more sense. In current searchworks result number 11 is ckey 8220230 which is one I would have expected to be one of the first results - since it is about constitution and president. I don't see this result in the first 2 pages of results (unless I'm missing it).

**Comment by mejackreed** [comment]
https://sul-solr-tester.stanford.edu/searches/961969 indicates that the first 10 results are close in relevancy with minor deviations (minor positional swapping). Change score of 3.0

https://sw-relevancy-new.stanford.edu/?f%5Btopic_facet%5D%5B%5D=Philosophy&q=science+AND+relig%2A&search_field=search shows that top results are using both the boolean `AND` operator and `*` as result explains are combining both stemmed versions of the string `science` and `relig` together.

While the user is using `AND` as an operator, it has no effect and the search `science relig*` offers the same results in both instances (as we set the default operator to `AND` already). If the user used `OR` that would have an affect on the results.

Removing `*` also has a similar effect on the search in both platforms.

**Comment by cmh2166** [comment]
Thanks for this. To confirm, boolean searching should perform the same in both our solr 4 environment and our solr 6.6.1 environment?

**Comment by cmh2166** [comment]
Seems to say so

**Comment by mejackreed** [comment]
Yes
