### ISSUE TITLE
SW Solr Users feedback: Simplified vs traditional form CJK issue

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/SearchWorks#1920]
Reported issue: This search "历史研究" retrieves 7,668 records in the old system vs. 3844 records in the new system. Also the two records that are ranked #1 and #2 in the old system (the most direct hits) are not found on the first screen of the new system's result set. When the first character is changed from simplified form (历) to the traditional form (歷), the old system still retrieves 7668 records, but the new system retrieves 1953 records. 	 https://sw-relevancy-new.stanford.edu/catalog?utf8=%E2%9C%93&search_field=search&q=%E5%8E%86%E5%8F%B2%E7%A0%94%E7%A9%B6	

Discussion: Could be same as #1923 ? Need to follow up with Vitus to piece apart the issue here, and determine if the same.

**Comment by cbeer** [comment]
Should be fixed by a custom character transform that applies Stanford's CJK normalization rules.

**Comment by cbeer** [comment]
The search for 历史研究 now retrieves 7209 results, although the relevancy is somewhat different and might be worth a follow up conversation.

**Comment by cmh2166** [comment]
Are the first two results in the old system found now in the first screen of the new systems results? If so, will close. / @cbeer
