### ISSUE TITLE
SW Solr Users feedback: Uncertain byte for byte matching & dictionaries needed, CJK

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/SearchWorks#1921]
"Search title with “中国基督教教育”( Zhongguo Jidu jiao jiao yu) and got 7 result in the testing SW system. However, I got 10 result in the current SW system. The 3 additional result not in the testing SW system are actually relevant and my comments also included.
 
1.      
https://searchworks.stanford.edu/view/4459860
Pu bian zhu yi de tiao zhan : jin dai Zhongguo Jidu jiao jiao yu yan jiu, 1877-1927 [2000]
普遍主义的挑战 : 近代中国基督敎敎育硏究, 1877-1927
Comment: My exactly search index is in the title.
 
2.       https://searchworks.stanford.edu/view/8827315
Jidu jiao yu Zhongguo jin dai zhong deng jiao yu [2007]
基督敎与中国近代中等敎育
Comment: All words in my search are in the tile but in different order.
 
3.       https://searchworks.stanford.edu/view/5817165
Kang Ri zhan zheng shi qi de Jidu jiao da xue [2003]
抗日战爭时期的基督敎大学
Comment: My search words are partially in the title. However, my search words are in the SERIES. "	 Search title with “中国基督教教育”( Zhongguo Jidu jiao jiao yu)

**Comment by cbeer** [comment]
Should be fixed by a custom character transform that applies Stanford's CJK normalization rules.

**Comment by cbeer** [comment]
The search for 中国基督教教育 now includes 26 results, including the three reported items.
