### ISSUE TITLE
SW Solr Users feedback: Repeated words matching & ranking

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/SearchWorks#1926]
Issue: See "Known item search for Tommy Orange's novel "There There". Works pretty well-- it's #2. Overall results here aren't as good as the results in current SW, which pushes the repeated phrase "there there" higher." ( https://sw-relevancy-new.stanford.edu/catalog?utf8=%E2%9C%93&search_field=search_title&q=there+there )

Work needed: Analysis on why repeated word results appear further down. Could be improved. Is minor, given desired item appeared at the top of the results.

**Comment by mejackreed** [comment]
Agreed. Are we ok to close on this?

**Comment by cmh2166** [comment]
This was only added originally because @cbeer indicated it should be reviewed. If he doesn't think that any longer, good to close.
