### ISSUE TITLE
SW Solr Users feedback: CJK Apostrophe question?

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/SearchWorks#1927]
Reported issue: This search "Kim, Tong-chun" retrieves 34 records in old system, but only 4 in new system. https://sw-relevancy-new.stanford.edu/catalog?utf8=%E2%9C%93&search_field=search&q=Kim%2C+Tong-chun. 

Discussion: May be apostrophe related.

Needed: Analysis on the source of this issue, then based on that, whether or not it is something we can solve for here or need to kick to Gryphon*.

**Comment by cbeer** [comment]
👍; I reindexed over night and now the search term retrieves the same 34 results.
