### ISSUE TITLE
Student Work Facet

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#1937]
Indexing work has been done and needs to be exposed on the app side.

**Comment by ahafele** [comment]
Needs masthead first

**Comment by jkeck** [comment]
@jvine does that masthead design exist? I think that may be the only blocker to making this actionable.

**Comment by jvine** [comment]
Show `Stanford student work` AND `Stanford school or department` facets at the top of the facet sidebar, when `Genre > Thesis/Dissertation` is selected.

### T&D masthead
```
<div id="masthead" class="dissertation-theses-masthead">
    <h1>Theses and dissertations</h1>
    <p>
      Result includes all theses and dissertations — from all sources — held in the Stanford Libraries and Digital Repository.</p>
    <p>To show Stanford work only, refine by <strong>Stanford student work</strong> or by <strong>Stanford school or department</strong>.
      </p>
  </div>
```
<img width="645" alt="screen shot 2018-09-19 at 2 29 35 pm" src="https://user-images.githubusercontent.com/6945691/45782940-3ee1f480-bc19-11e8-853a-96f580d9b0b9.png">


### Home page access point
```
<p>
All student work held in the Stanford Libraries &amp; Digital Repository. 
<br>
<a href="">Show Stanford work only</a>.</p>
```
<img width="384" alt="screen shot 2018-09-19 at 2 32 07 pm" src="https://user-images.githubusercontent.com/6945691/45782956-499c8980-bc19-11e8-9a55-4aa529aeaa55.png">

"Stanford work" link should link to a search result with `Genre > Thesis/Dissertation` AND `Stanford student work > Thesis/Dissertation` selected.
<img width="676" alt="screen shot 2018-09-19 at 2 37 39 pm" src="https://user-images.githubusercontent.com/6945691/45783062-9aac7d80-bc19-11e8-849d-985714421038.png">
