### ISSUE TITLE
MODS display duplicating certain metadata

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#1939]
mods-display is duplicating FORM 
electronicelectronic resourceElectronic data.electronic resourcemagnetic disc 
And semicolon in MAP DATA
https://searchworks.stanford.edu/view/cv275yx9215 

https://jirasul.stanford.edu/jira/browse/SW-1833

<img width="1130" alt="screen shot 2018-09-24 at 3 10 28 pm" src="https://user-images.githubusercontent.com/7749403/45982112-54399300-c00c-11e8-9163-b7838271663e.png">

**Comment by arcadiafalcone** [comment]
To clarify: the metadata that is being displayed is present in the record. This occurs with MODS records converted from MARC -- form data is derived from the 007. 008, 300, and several other fields, some of which encode essentially the same information in different terms. Preferred behavior would be for the terms to be deduplicated at indexing, removing exact duplicates (ignoring case, spacing, and punctuation) and terms contained entirely in other terms. So in the above example, the terms for display would be "electronic resource", "electronic data", and "magnetic disk".
