### ISSUE TITLE
emailed selections for items missing authors

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#1943]
https://jirasul.stanford.edu/jira/browse/SW-1821

**Comment by cbeer** [comment]
I took a quick look at this; it looks like the code for including authors in the brief email was removed last year in https://github.com/sul-dlss/SearchWorks/commit/2ea406025f8c062960b822da3a442ff66430afff as part of the article search uber-pr (https://github.com/sul-dlss/SearchWorks/pull/1745). 

That said, the searchworks 3.x app from 4 years ago is trying to pull author data from a field that doesn't exist (and never did). I'm not sure where the old SearchWorks 2.x codebase is, so I can't confirm the behavior prior to that.

With that, do you want to reframe the ticket to add authors to the brief email for both MARC + MODS? If so, I think we'll need a spec for how to figure out which authors to include (again, for both MARC + MODS). If there's only been 1 feedback ticket in the last 4 years, maybe it'd be easier to just remove "author" from the text description and call it a day?

**Comment by cbeer** [comment]
^ @ahafele

**Comment by ahafele** [comment]
Remove word author from "email this screen"

![screen shot 2018-09-25 at 11 57 03 am](https://user-images.githubusercontent.com/7749403/46036371-3165b800-c0ba-11e8-92b9-b50fd7215e32.png)
