### ISSUE TITLE
Refworks export of diacritics

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#1944]
There are several languages with complex diacritics and vernacular characters that are failing to import to RefWorks. 

(Workaround, if you are using the new ProQuest Refworks, you can install the "Save to RefWorks" tool in your browser and that method works.)

https://jirasul.stanford.edu/jira/browse/SW-1977

**Comment by mejackreed** [comment]
Relevant discussion in Blacklight slack on c4l recently:

https://code4lib.slack.com/archives/C54TB5WDQ/p1537455762000100

TLDR: RefWorks doesn't support TLS > 1.0 and no eta on support.

**Comment by mejackreed** [comment]
Looking into this a bit. It seems that this import to RefWorks is broken for several other catalogs for these languages (Princeton, Temple, etc) and likely stems from lack of UTF-8 support. I've tried a few things like using several different variations of NFKC unicode normalization to see if I can get a different result without success so far.

Looking into see if we have a support rep contact at RefWorks to go from there.
