### ISSUE TITLE
Google Books link is displayed in results view but not in record view

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#1945]
https://jirasul.stanford.edu/jira/browse/SW-1783
https://jirasul.stanford.edu/jira/browse/SW-1969

**Comment by jvine** [comment]
These examples of SDR items show Google Books links in results view but not on show page:

https://searchworks.stanford.edu/catalog?utf8=%E2%9C%93&search_field=search&q=9238380
https://searchworks.stanford.edu/catalog?utf8=%E2%9C%93&search_field=search&q=9238363
https://searchworks.stanford.edu/catalog?utf8=%E2%9C%93&search_field=search&q=9238493
https://searchworks.stanford.edu/catalog?utf8=%E2%9C%93&search_field=search&q=8714731

Not clear why these examples are different, but SDR items **should not** have GB links in results or show page - even if they have other 3rd-party links.

**Comment by mejackreed** [comment]
I'm thinking this is the case where the item is a managed purl item. Are there other SDR cases where this is shown?

**Comment by mejackreed** [comment]
gotcha no that is what I was asking. I think checking if the sirsi item has managed purls is sufficient
