### ISSUE TITLE
Change default sort for Databases to Relevance

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/SearchWorks#1952]
Long time request from IC - recent jira ticket https://jirasul.stanford.edu/jira/browse/SW-1990

Currently is by title - https://searchworks.stanford.edu/?f%5Bformat_main_ssim%5D%5B%5D=Database

_per JV - Can we also remove the A-Z filter_

<img width="420" alt="screen shot 2018-09-19 at 12 36 21 pm" src="https://user-images.githubusercontent.com/7749403/45777193-f4a54700-bc09-11e8-8999-43608813dc7d.png">

**Comment by shelleydoljack** [comment]
This breaks this test:
https://github.com/sul-dlss/sw_index_tests/blob/cecbd6986f5de924b325bf707a443806ed8b50f3/spec/sort_spec.rb#L57
