### ISSUE TITLE
Apply 'Request on-site access' behaviour to specific locations

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/SearchWorks#1965]
- [x] For the **locations** (as opposed to libraries) specified below, change the Request button text from "Request" to "Request on-site access"

- [x] Additional text changes to location translations to adjust display.

Before
<img width="370" alt="screen shot 2018-11-01 at 4 14 21 pm" src="https://user-images.githubusercontent.com/6945691/47885556-eba3ba00-ddf2-11e8-8f1b-6d75a74f1fa6.png">

After
<img width="367" alt="screen shot 2018-11-01 at 4 14 55 pm" src="https://user-images.githubusercontent.com/6945691/47885561-efcfd780-ddf2-11e8-93ef-23898243ac6c.png">

Original request:  archival Music materials at SAL3
https://jirasul.stanford.edu/jira/browse/SW-1962
Intent: put the essential info in the clickable target so it's more likely to be read.

**Comment by saseestone** [comment]
List of locations that SHOULD have the "Request on-site access" behavior:
PAGE-AR
PAGE-AS
PAGE-EA
PAGE-ED
PAGE-EN
PAGE-ES
PAGE-HP
PAGE-MD
PAGE-MU
PAGE-RM
PAGE-SP

*NOTE: the only PAGE-* locations that WON'T result in a "Request on-site access" behavior are:
PAGE-BU
PAGE-IRON
PAGE-LP

**Comment by saseestone** [comment]
We also want to modify the Location translation for the following LOCs:

'PAGE-AR' => 'For use in Art & Architecture Library or Special Collections'
'PAGE-AS' => 'For use in Archive of Recorded Sound'
'PAGE-BI' => 'Ask at circulation desk'
'PAGE-CH' => 'Ask at circulation desk'
'PAGE-CL' => 'For use in Classics Library'
'PAGE-EA' => 'For use in East Asia Library'
'PAGE-ED' => 'For use in Cubberley Library'
'PAGE-EN' => 'For use in Terman Library'
'PAGE-ES' => 'For use in Branner Library'
'PAGE-GR' => 'For use in Green Library'
'PAGE-HA' => 'For use in Hoover Archives'
'PAGE-HP' => 'For use in Miller Library or Green Library'
'PAGE-HV' => 'For use in Hoover Library'
'PAGE-LW' =>
