### ISSUE TITLE
non-Roman linked 651 not displaying

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/SearchWorks#1971]
https://searchworks.stanford.edu/view/11683280

https://jirasul.stanford.edu/jira/browse/SW-1693

**Comment by cbeer** [comment]
I just want to confirm -- this ticket is asking us to display linked subjects for subjects, genres and local subjects from any of the 6xx fields?

**Comment by ahafele** [comment]
Confirmed with Vitus - Yes any 6xx
