### ISSUE TITLE
Run a lighthouse audit/Run through static page analysis checklist (of some sort)

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/SearchWorks#1985]
Chrome Plugin: https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk

Checklist: https://github.com/thedaviddias/Front-End-Performance-Checklist
 - [x] Look into non-blocking stylesheets `Non-blocking: high CSS files need to be non-blocking to prevent the DOM from taking time to load.` #1990

Bring analysis back to this ticket for discussion / spinning off new tickets.

**Comment by mejackreed** [comment]
I think I've exhausted things that we can do at the moment. #2025 and #1990 seem to be the main things that are actionable.

**Comment by mejackreed** [comment]
With both of those issues closed I'm saying this is resolved for now.
