### ISSUE TITLE
Validate we're using our IIIF thumbnail image sizes efficiently

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/SearchWorks#1986]

**Comment by mejackreed** [comment]
It seems to me that we are requesting 100 x 100 thumbs for results views from Stacks.

```
https://stacks.stanford.edu/image/iiif/wn461xh4882%2F2542001/square/100,100/0/default.jpg
```

We are then displaying these at the same resolution.

@aeschylus are there additional things that we should be checking here?

**Comment by aeschylus** [comment]
I didn't have much in mind beyond auditing all the image uses in different views.

Here are 13 instances of "image_tag" in the codebase: https://github.com/sul-dlss/SearchWorks/search?p=1&q=image_tag&unscoped_q=image_tag

And here are maybe 7 instances of `<img>` scattered through a couple of dozen results, most of which use the document thumbnail methods: https://github.com/sul-dlss/SearchWorks/search?p=1&q=%22%3Cimg%22&unscoped_q=%22%3Cimg%22

**Comment by mejackreed** [comment]
Gotcha ok. I think we are good to go. I'm not seeing places where we are using urls constructed for IIIF resources outside of what is created in the indexing process. This seems to indicate we are using 100,100 everywhere. I'm assuming these are performant and cached.
