### ISSUE TITLE
Stop parsing MODS in search results

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/SearchWorks#1987]
The following fields are being parsed from MODS (through the `ModsDisplay` gem) in search results
- [x] First `Name`
  * https://github.com/sul-dlss/SearchWorks/blob/1ce08ec1cc6a765ed78418625836fac83e839a29/app/views/catalog/_mods_search_results_document_fields.html.erb#L7-L9
- [x] `Abstract`
  * https://github.com/sul-dlss/SearchWorks/blob/1ce08ec1cc6a765ed78418625836fac83e839a29/app/views/catalog/_accordion_section_summary_data.html.erb#L47-L50

**Comment by mejackreed** [comment]
Is the intent here to add a new indexed field where this is now unnecessary?

**Comment by jkeck** [comment]
Yes, sorry for the lack of clarity.  We want to continue to have this data in the search results, but get it from data in the index, not parsing XML in the results view.

**Comment by mejackreed** [comment]
So looking into this a bit. It seems like we may need to store some structure still for the names as we need to now also link w/ roles. I want to circle back w/ team before proceeding further.
