### ISSUE TITLE
Missing metadata from record display for multidruid objects

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/SearchWorks#2005]
Entire description section above Creators/Contributors is being dropped for multidruid objects with the sidebar. (Statement of responsibility, publication info and date, language, and physical description)

examples
https://searchworks.stanford.edu/view/8810055
https://searchworks.stanford.edu/view/11403452 
https://searchworks.stanford.edu/view/8112988 

Compare this with no digital object: https://searchworks.stanford.edu/view/7807804 
And this with a digital object without the sidebar: https://searchworks.stanford.edu/view/10366569 

https://jirasul.stanford.edu/jira/browse/SW-3740

**Comment by jvine** [comment]
This is the chunk of metadata that's missing from the managed PURL records:
- mods_upper_metadata_section
- marc_upper_metadata_items

Add the missing metadata in a `<div class="section">` at the top of the `.record-sections` column of the `.record-metadata` row. (i.e. top of the right column, above the "Contributors" section.) No heading required. 

Outcome for https://searchworks.stanford.edu/view/8112988
<img width="1196" alt="screen shot 2018-09-27 at 5 45 22 pm" src="https://user-images.githubusercontent.com/6945691/46181913-535b6800-c27d-11e8-8682-4cd8815cd9d5.png">
