### ISSUE TITLE
Margins of the Cite popup are gone

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/SearchWorks#2006]
Margins of the Cite popup - on selections and individual records - have gone missing. This seems recent.

<img width="704" alt="screen shot 2018-09-27 at 9 02 37 am" src="https://user-images.githubusercontent.com/7749403/46159023-2040b680-c234-11e8-8fc5-6bf185c04693.png">

https://jirasul.stanford.edu/jira/browse/SW-3743

**Comment by jkeck** [comment]
I have a temp fix for this in the `citations-wip` branch in case anybody is interested.  Otherwise, it'll get fixed w/ Article Citations.
