### ISSUE TITLE
Look into bound with callnumbers multiple show all / show less buttons

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/SearchWorks#2020]
While reviewing #1345 we noticed multiple buttons 

![show_less](https://user-images.githubusercontent.com/5402927/46375378-2249b180-c648-11e8-9b3d-293aaecf4c8c.gif)

**Comment by camillevilla** [comment]
@mejackreed I haven't been able to reproduce this locally since our pairing session 🤔

**Comment by mejackreed** [comment]
Maybe it was a caching fluke? Closing the issue and we can reopen if it presents again.
