### ISSUE TITLE
Digital Serials - sort 

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/SearchWorks#2037]
Desired behavior is to order the display the digital object labels in the embed viewer sidebar according to the ordinality specified in the 856, using natural sort.

Example:
856 $x label:December 2010 $x sort:2010.12
856 $x label:February 2010 $x sort:2010.2
856 $x label:January 2010 $x sort:2010.1
856 $x label:July 2015 $x sort:2015.7
 
Displays as:
January 2010
February 2010
December 2010
July 2015

When $x part appears without a number or is absent, sort by $x label. If some 856s in the record have an $x part value and some don’t, the ones with a value should appear sorted at the top of the list. If $x label is not present, default to current behavior.

Justifications 
-this is a display issue, and should be handled in display – the data is there to provide the info the display needs to interpret it properly
-not dependent on a specific backend
-generally, the order of fields in a MARC record is not semantic and should not have a major impact on display
-while data creation is manual, cataloging staff won’t have to redo the ordering every time any digital object attached to the record is versioned in Argo
(These are the same sort outcomes as described in the digital series documentation, just applied in SearchWorks instead of earlier in the pipeline.)

Sample Data on Bodoni
8923346
8810055
4258572
1071767
10551832
12687004

**Comment by jkeck** [comment]
Removing `Analysis Needed`.  Note that the example records above may have `part` instead of `sort`, but `sort` is the key that was implemented in sul-dlss/dor-services-app#156 and what we'll be using.

**Comment by cbeer** [comment]
I've confirmed the data is getting exported to Symphony, and kicked it off for the related materials for http://searchworks.stanford.edu/view/8810055.
