### ISSUE TITLE
Implement a format -> Schema type mapping

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/SearchWorks#2040]
There is an initial pass in the [Development Proposal](https://docs.google.com/document/d/10QQo7ej-Z57R_cNUsEutcdkv0cbcgl_hpMFhVNemxzg/edit), and been implemented in #2029.

There are some other mappings that are falling back to CreativeWork that we might be able to find better mappings for (e.g. Equipment).  If we can't find a clean mapping, it might be an opportunity to engage some Metadata folks to see what they believe the mapping might be.

(Note that #2029 is a pre-requisite to this work)

**Comment by mejackreed** [comment]
An approach added here: https://github.com/sul-dlss/SearchWorks/pull/2047 Not sure if we want to do this though.
