### ISSUE TITLE
Display/translate 1|AuxAmateurs

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/SearchWorks#2044]
We want to handle these in the same was we do Nielsen. 
For 905, 920 and 986 display the 1|AuxAmateurs as (source: Amalivre)

Examples 9862866 and 10670424

**Comment by ahafele** [comment]
@cbeer for Nielsen and AuxAmateurs 9xx fields we don't want the |x to display either. https://searchworks.stanford.edu/view/12795512 
Separate ticket?

**Comment by jkeck** [comment]
This is blocked until we stop parsing MARC in the results.
