### ISSUE TITLE
Do we have enough info from Ebsco to schema.org Articles

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/SearchWorks#2065]
This was asked by Greta, it seems like if we have enough information we could provide this information. Is there a problem though for non-Stanford users?

**Comment by bmckinney-ebsco** [comment]
Let me know if I can help here. We would like to support this if it's feasible.

**Comment by jkeck** [comment]
I'm not sure if we would want to do that or not.  It seems like our app being the source of EBSCO's schema.org data for crawlers feels like a potentially bad idea.

I still have outstanding questions about if we should be allowing bots to even crawl our article results in the first place.

**Comment by mejackreed** [comment]
K. I say lets punt for now and come back to this after we have some data about catalog.

**Comment by bmckinney-ebsco** [comment]
Ah, I didn't understand the use case. It could likely violate agreements with one or more of our content partners.
