### ISSUE TITLE
Analytics events check list

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/SearchWorks#2070]
We should huddle on building out a list of events to track below

- IIIF badge clicks 'n drags

**Comment by jvine** [comment]
- Outbound links
  - e.g. Yewno, eResources, SFX menu, Worldcat, Google Books, Library services menu
  - where the outbound links were clicked from: home page, results, record view, Selected databases, no results
- Cross-site use - capture not just the count of these actions, but the user's search
  - Incoming searches from Bento to Catalog, Articles+
  - Incoming searches from SFX, Yewno, Google?
  - Searches transferred from mini-bento to Catalog, Articles+
  - Searches transferred via the drop-down menu to Catalog, Articles+, Bento
- Searches that lead to no results
  - Actions taken from no results page (chat, outbound link, bento, search link)
- Featured resources on home page
- IIIF badge clicks 'n drags
- Document actions (by context: results, record view, selection list)
  - Request
  - Stackmap
  - Select / Select all
  - Check availability toggle
  - Cite
  - Send to (text, email, refworks, endnote, printer)
  - Browse nearby (click, scroll)
  - more...
- Selection lists
  - Catalog vs. Articles+
  - logged-in vs. not
- UI features
  - side-nav-minimap
  - Facet toggle
  - View / sort / per page

**Comment by camillevilla** [comment]
See #2117
