### ISSUE TITLE
SEE-OTHER availability is blank in results view

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/SearchWorks#2100]
<img width="576" alt="screen shot 2018-11-05 at 9 59 44 am" src="https://user-images.githubusercontent.com/7749403/48018772-944d6480-e0e6-11e8-814a-cf294c7c9e6e.png">

7541413
~~4082967~~ 4082969

**Comment by jvine** [comment]
These items should have a "See record for details" link in the results as well... even though there's nothing to see on the record.

**Comment by mejackreed** [comment]
@jvine @ahafele I've noticed for those two records, they now get the "bound with" behavior if include the location logic to be displayed. Should that not be the behavior here?

**Comment by mejackreed** [comment]
## Getting other location behavior
![screen shot 2018-11-16 at 10 47 14 am](https://user-images.githubusercontent.com/1656824/48638149-00548600-e98d-11e8-8802-0db394011cc9.png)

## Getting bound with
![screen shot 2018-11-16 at 10 46 54 am](https://user-images.githubusercontent.com/1656824/48638150-00548600-e98d-11e8-9016-b3f1e3733ad3.png)

**Comment by ahafele** [comment]
I believe this is correct but defer to @jvine for verification. 
(And sorry the Steinbeck ckey with this behavior should be 4082969.)

**Comment by jvine** [comment]
Is 4082967 the right ckey for this? It has requestable items. These are the related records that don't:
- 4082918
- 4082969
- 4082970

Ah, just saw @ahafele's response. I don't actually know if the behaviour is correct. Maybe we need to chat.

**Comment by mejackreed** [comment]
Gotcha.. so just to confirm. Is this the correct behavior for 4082969 ?

![screen shot 2018-11-16 at 11 08 15 am](https://user-images.githubusercontent.com/1656824/48639159-fa13d900-e98f-11e8-8f3b-2ff96a3305df.png)
