### ISSUE TITLE
SDR display - Record view - Update Context Panels

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/SearchWorks#2108]
Split out from #2024

## 'Context' panels

- [x] Group together these two sections: `panel-appears-in` and `panel-in-collection`. When either or both appears, display `<h2>Context</h2>` at the top.

### `panel-in-collection` section
- [x] Change the `<h3>` in the panel header to `Item belongs to a collection`
- [x] Remove the body/footer separation, so there's no line between the title/summary and `<dl>`. (Maybe move the  `<dl>` into the body section, and add 15px margin to the top of it.) 
- [x] Change `<dt>Digital content</dt>` to `<dt>Digital collection</dt>`
- [x] Change `<dd>N items</dd>` to `<dd>N digital items</dd>`
- [x] Change `<dt>[Resource type]</dt>` to `<dt>Physical collection</dt>`
- [x] Remove the Collection PURL `<dt>` and `<dd>` pair
<img width="372" alt="screen shot 2018-10-25 at 6 38 26 pm" src="https://user-images.githubusercontent.com/6945691/47539438-5437e780-d885-11e8-8e0e-b4ed54de22e6.png">

### `panel-appears-in` section
- [x] Change the `<h3>` in the panel header to `Item is included in another record`

The two panels together panels look like this
<img width="374" alt="screen shot 2018-10-25 at 5 01 38 pm" src="https://user-images.githubusercontent.com/6945691/47540337-8b0ffc80-d889-11e8-847e-46c1afb249c0.png">

**Comment by camillevilla** [comment]
Closed by #2178
