### ISSUE TITLE
Fix the mystery dot

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/SearchWorks#2112]
<img width="610" alt="screen shot 2018-11-06 at 2 32 31 pm" src="https://user-images.githubusercontent.com/1656824/48098906-41a1a480-e1db-11e8-94f6-9194606ee6f8.png">

**Comment by mejackreed** [comment]
@jvine do you have vector graphics for the sprite-links image?

**Comment by mejackreed** [comment]
We should just remove this sprite-links thing and switch to an svg

**Comment by jvine** [comment]
Agree. I don't have a vector graphic, but let me see what i can do
