### ISSUE TITLE
Preview and Online buttons/badges overlap in call number browse

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/SearchWorks#2121]
Reported from a Chrome browser. 

![overlap](https://user-images.githubusercontent.com/7749403/48155193-4a4bb680-e27f-11e8-9599-18b54d1bd570.png)

**Comment by jvine** [comment]
Online badge should be moved to the front of the title for gallery view. In-browser, it looks like just moving the span will work (need to add a space following the span so it doesn't hit the title). Affects Browse nearby embed & full page; and gallery view on search results.

<img width="603" alt="screen shot 2018-11-07 at 11 29 46 am" src="https://user-images.githubusercontent.com/6945691/48155698-7b78b680-e280-11e8-9cb9-5ea818696508.png">
