### ISSUE TITLE
Split off - Fix single managed PURL alignment

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/SearchWorks#2132]
There is one issue I'm noticing for normal managed PURL records (e.g. does not have multiple), which may have already existed and is just more obvious w/ the new design, is some odd right-column alignment.

<img width="268" alt="screen shot 2018-11-07 at 10 22 31 pm" src="https://user-images.githubusercontent.com/96776/48181317-da1f4e00-e2db-11e8-91e4-ff92d486725e.png">

If anybody wants to take a look at that with, that would be great.  We could also split that off into a separate issue.

Split off #2131

**Comment by mejackreed** [comment]
@jkeck do you happen to have any ckey's handy where you saw this happening? I've been trying to recreate this morning and have been unable to see the problem yet.

**Comment by mejackreed** [comment]
Ah.. nm. Had to switch to the correct branch 😢

**Comment by mejackreed** [comment]
I'm going to pause on doing anything here. I'm not exactly sure what should be done and the intent of the page layout.

**Comment by jvine** [comment]
@mejackreed can i see this live somewhere? i have an idea of the issue but need to see the html.

**Comment by mejackreed** [comment]
in `record-metadata-section.scss` add `purl-embed-viewer` to the selectors on line 7: `.record-metadata, .upper-record-metadata`. The metadata is indented from the right so the sidebar menu should never overlap content.

**Comment by mejackreed** [comment]
Resolved in feature branch.
