### ISSUE TITLE
Hoover Archives Requests should not default to "In process" 

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/SearchWorks#2136]
Hoover Archives records _with_ Finding aid should _not_ default to Red X - In process. Only those without the Red X. 

Currently on stage
<img width="393" alt="screen shot 2018-11-08 at 2 42 01 pm" src="https://user-images.githubusercontent.com/7749403/48232564-dedd1400-e366-11e8-9398-fd904334a053.png">

Should still be Orange truck - In-library use
<img width="369" alt="screen shot 2018-11-08 at 3 00 27 pm" src="https://user-images.githubusercontent.com/7749403/48232625-15b32a00-e367-11e8-92e9-d54e596fd3d0.png">

**Comment by mejackreed** [comment]
`6658571`
