### ISSUE TITLE
For SDR collection records, add Collection PURL to "tech details" footer

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#2175]
Preferably between Librarian view and Catkey. Link text:  `Collection PURL`. No more exposed URL.

<img width="422" alt="screen shot 2018-11-15 at 2 02 24 pm" src="https://user-images.githubusercontent.com/6945691/48584839-b19ce280-e8df-11e8-925a-0baf0010dd1b.png">

**Comment by camillevilla** [comment]
Appending this work to #2168
