### ISSUE TITLE
Citation send-to RefWorks gone from catalog selections list

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/SearchWorks#2238]
Still present in Articles but no longer in catalog. 

## Current behavior in catalog:
<img width="400" alt="screen shot 2018-12-14 at 10 31 34 am" src="https://user-images.githubusercontent.com/7749403/50020674-9cbd7880-ff8b-11e8-82ea-2c74d19786a0.png">

## Current Articles+ selection behavior:
![image](https://user-images.githubusercontent.com/5402927/50021003-819f3880-ff8c-11e8-8ce9-eced09b7f334.png)

**Comment by camillevilla** [comment]
https://github.com/sul-dlss/SearchWorks/blob/master/app/views/bookmarks/_tool_dropdown.html.erb#L11-L21

>but if this is new… i wonder if the bookmarks page needs some updating now that we’re not returning the MARC record on search results?
- @cbeer 

>Catalog had RefWorks and Endnote. We didn't implement RIS for catalog.
- @jvine
