### ISSUE TITLE
Author panel on record view

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/SearchWorks#2276]
- Drop down from info expander.
- Info pulled from wikidata - Picture, Occupations, _Filmography_, Notable works
- _Info from other sources - Other works by this person_
 
_Some ckey examples for Bach._ [More here](https://docs.google.com/spreadsheets/d/1MpCKhuIEvFsMrreynOsU4RDf0m06JdvynGJC9lqMVrA/edit#gid=1481774891) 

12227071
11838093
10930986
10930082

**Comment by jvine** [comment]
If an author in the Authors/Contributors section has a linked record, show an info icon next to their name.
<img width="964" alt="author panel closed record" src="https://user-images.githubusercontent.com/6945691/56974423-af43e300-6b23-11e9-9db8-d4780c32d3ba.png">

- Info icon colour `#0098db; [colour name 'sky']`
- When the user clicks the icon:
   - open the info panel below the name. (I think it should be within the same `<dd>`.)
   - change the icon colour to grey (I used `color: #737373; opacity: .5`)
- Content and layout are the same as #2278.
- Collapse behaviour is different from results view. 
   - No close icon in the panel
   - When the panel is open, the "info" icon changes to "close".
   - When user clicks the "close" icon, the panel and icon revert to their original state.

<img width="968" alt="author panel open record" src="https://user-images.githubusercontent.com/6945691/56976549-11064c00-6b28-11e9-8412-fb4c5973e08d.png">

**Comment by jkeck** [comment]
Closing for now, can review these for any future work cycles.
