### ISSUE TITLE
Title panel on record view

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/SearchWorks#2277]
- Already expanded. 
- Info from wikidata - Picture, Cast, Derivative works, Narrative location
- _Info from other sources?_ 

Is it possible to incorporate the geo work for narrative location? 

Ckeys with title uris in 130 and in wikidata. [More here](https://docs.google.com/spreadsheets/d/1MpCKhuIEvFsMrreynOsU4RDf0m06JdvynGJC9lqMVrA/edit#gid=822907897)

8715203
8538384
4809356

**Comment by jvine** [comment]
Content from Wikidata:

- Image
- Description
- Narrative locations 
- Main subject
- Cast
- Derivative works (this example doesn't have any)

<img width="962" alt="title panel record" src="https://user-images.githubusercontent.com/6945691/56977586-56c41400-6b2a-11e9-8b42-4e665c227bc4.png">

Panel is open by default
Appears above the "Description" heading in the `record-sections` column

See #2278 for layout details and collapse behaviour.

**Comment by jkeck** [comment]
Closing for now, can review these for any future work cycles.
