### ISSUE TITLE
Author panel in results

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/SearchWorks#2278]
- Same location as research starters in Articles+
- Shows up for known (linked) searches
- Would pull in same data as https://github.com/sul-dlss/SearchWorks/issues/2276

**Comment by jvine** [comment]
<img width="997" alt="author panel results" src="https://user-images.githubusercontent.com/6945691/56973819-75261180-6b22-11e9-917e-50f479ee5915.png">

**Content**

- [ ]  Name + birth/death dates 
- [ ] Show in `<dt>/<dd>` pairs:
     - Image
     - Description
     - Occupations
     - Notable works
     - Filmography
- [ ]  Each `<dd>` has the "more..." truncation behaviour. 
- [ ]  Source name is linked to the specific record in that source. 

**Layout**

See [Articles+ Topic Overview](https://searchworks.stanford.edu/articles?utf8=%E2%9C%93&f%5Beds_search_limiters_facet%5D%5B%5D=Direct+access+to+full+text&search_field=search&q=cow) for example. 

For the box:
```
    border: 1px solid #0098db;
    border-top: 15px solid #0098db;
    padding: 0 15px 15px 15px;   
    box-shadow: 0 4px 8px -2px rgba(0,0,0,0.2);
```

**Collapsed**
In Results, the panel has the same behaviour as Articles+:  When the user clicks the X, hide everything but the title, and rotate the close button 45 degrees. Clicking the + reopens the panel.

<img width="787" alt="panel closed results" src="https://user-images.githubusercontent.com/6945691/56973187-33e13200-6b21-11e9-8df9-13d2d7bad083.png">

**Comment by jvine** [comment]
Note that the mockup shows the Notable works in a `<ul>`. It's equally valid to use multiple `<dd>`s. Addition of elements like audio players may make bullets unnecessary/awkward in any case.

**Comment by jvine** [comment]
Ah, but. While multiple `<dd>`s are valid for the content, that doesn't obviate the need for truncation of long lists. Not sure how that's possible without an outer container.

**Comment by jkeck** [comment]
Closing for now, can review these for any future work cycles.
