### ISSUE TITLE
Demos of wikidata update in SearchWorks

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/SearchWorks#2279]
Find examples of demo-able updates we can make in wikidata that will reflect in our knowledge panel. 

- [ ] Add new entity
- [ ] Add metadata to existing entity. (could be tricky because small subset of data we will be showing)
- [ ] Time how long these updates take to show up in SearchWorks.

**Comment by jkeck** [comment]
We didn't get to this, but the demo happened and this wasn't included.
