### ISSUE TITLE
Geo panel on results view

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#2282]
<img width="1004" alt="geo panel results view" src="https://user-images.githubusercontent.com/6945691/56999579-94459300-6b64-11e9-803e-aadb3d9bd5bf.png">

For linked searches for place names (which we identify how?), display a panel at the top of the search results, showing:
- Map (prefer the bounding area map that Jack demonstrated over this example from wikidata)
- Description
- Location hierarchy

No additional data for now.

**Comment by jkeck** [comment]
Closing for now, can review these for any future work cycles.
