### ISSUE TITLE
Audio players in Notable works

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#2283]
Basic styling for inserting an audio player for each notable work that has an available audio file:

<img width="643" alt="audio players inline" src="https://user-images.githubusercontent.com/6945691/57000030-a58f9f00-6b66-11e9-8efe-42c61b75b66a.png">

- [x] Each work can be in a `<dd>` of its own, or in a `<ul>` within a single `<dd>`.
- [x] The work container has `border-bottom: 1px solid $cloud; padding-bottom: 8px; margin-bottom: 8px;`
- [x] If `<ul>` is used, set `padding-left: 0;`
- [x] `<audio>` has `height: 33px;`

In the screenshot I set the audio player width to 250px but that will likely not be wide enough when all the elements are present.

**Comment by jvine** [comment]
Made a change to the CSS for the container because the previous version interfered with the responsive truncator.

**Comment by jkeck** [comment]
Closing for now, can review these for any future work cycles.
