### ISSUE TITLE
[SearchWorks/prod] NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/SearchWorks#2313]
## Backtrace

    line 7 of [PROJECT_ROOT]/app/models/eds/session.rb: search
    line 26 of [PROJECT_ROOT]/app/models/eds/repository.rb: eds_search
    line 5 of [PROJECT_ROOT]/app/models/eds/repository.rb: block in search

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50022/faults/34741831)

**Comment by jkeck** [comment]
We're now getting a more specific (and useful) error that's being reported to HB in these cases.  Closing this and we can re-open a new issue if it crops up again.
