### ISSUE TITLE
Remove eReserve "At the Library" block 

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#2436]
Currently we have a eReserve block showing up when an item has a Home Location = INSTRUCTOR, Current Location = E-RESV

![image](https://user-images.githubusercontent.com/14897546/79592444-dbd37080-808e-11ea-816f-a490c09d0367.png)

Example records:
https://searchworks.stanford.edu/view/12378453
https://searchworks.stanford.edu/view/12958161
(and basically any record found in the Course Reserve catalog right now.)

999 example:
![image](https://user-images.githubusercontent.com/14897546/79595820-610d5400-8094-11ea-8613-9ee7e637ec7d.png)

The information in the "At the Library" block for the eReserves item record is really confusing to the user, and there isn't any helpful information being displayed.  The item is always available (for now - there is no digital lending where it might not be available), and the user needs to just use the information in the "Available online" block. 

Can we just remove the "At the Library" section for all items in E-RESV?

**Comment by jvine** [comment]
Should also be removed from search results availability display.
