### ISSUE TITLE
Banner text update

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#2442]
We need a slight text change to the banner message in Searchworks, Bento and Hours.  Text change is in the second sentence.  The formating and links should remain as is.

**COVID-19 update**
Stanford Libraries[ e-resources](https://library.stanford.edu/remote-resources) are available to support you during remote instruction.
At this time, physical access to materials is unavailable and locations remain closed. [read more](https://library.stanford.edu/alerts)

**Comment by saseestone** [comment]
My Account needs the same text change.

**Comment by jkeck** [comment]
All relevant PRs merged, just getting things deployed now.
