### ISSUE TITLE
Web archives collections and  thumbnail presentation in filmstrips

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/SearchWorks#2502]
In chatting with @andrewjbtw re: the potential changes in the sul-embed presentation of web archives (sul-dlss/sul-embed#1180), it sounds like there are some questions about how the SearchWorks collection display will look if the WAS Thumbnail Service is decommissioned see sul-dlss/argo#2091).

Will the "filmstrip" display on the item page for collection PURLs still show the filmstrip?

Here's an example collection: https://searchworks.stanford.edu/view/jt898xc8096 

![Screen Shot 2020-07-24 at 1 53 06 PM](https://user-images.githubusercontent.com/73732/88434520-33335c00-cdb5-11ea-9e6a-b7b6205a06ba.png)

**Comment by cbeer** [comment]
I believe the answer is.. no. The collection filmstrip uses the thumbnail from the accessioned object, not the WAS thumbnail service.
