### ISSUE TITLE
New location translation needed for LL-NEWS

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#2527]
New Home Location in Symphony: LL-NEWS
Location Translation should be: "Lower Level: Newspapers"

Context: Green is moving the entire Newspaper collection into shelving on the Lower Level. LibSystems/Vitus will start batch transferring materials to the new location when we confirm the translation is in place.

**Comment by jkeck** [comment]
Are there any considerations around availability icon or request links for this location?

**Comment by saseestone** [comment]
Excellent questions (as always).  Materials will have an Item Type = NH-INHOUSE use, so the yellow checkmark icon and "in-library use" text should appear based on those values.  Nothing else needed keying off of the Home Location value.

Here's an example record of one of the titles moving: https://searchworks.stanford.edu/view/2981120
![image](https://user-images.githubusercontent.com/14897546/90580086-dbea9680-e17c-11ea-8c47-e88a0980cbc4.png)

The goal is to replace "Information Center: Newspapers" with "Lower Level: Newspapers".
