### ISSUE TITLE
Urgent update to banners in SearchWorks, hours, bento

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#2529]
Libraries are closing today due to air quality.  We need to replace the current banner on SearchWorks, hours, and bento with this:

![image](https://user-images.githubusercontent.com/14897546/90664285-a1760d80-e1ff-11ea-833d-778020d2d531.png)

It's date specific so we'll need to update tomorrow (either by extending this alert, or by returning to the banner we have displaying today)

**Comment by jkeck** [comment]
For your copypasta goodness

AIR QUALITY ALERT
All libraries are CLOSED today, August 19th, due to poor air quality. Online services are available.
