### ISSUE TITLE
Remove Research Restart banner in SearchWorks, Hours, Bento

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#2558]
After placing the COVID-19 Libraries update in the menu (#2555 ), remove the Research Restart banner.

Also should apply to Hours and Bento.

We'll go back to using the banner for temporary statuses (AQI, earthquake, raining cats, apocalypse)

**Comment by camillevilla** [comment]
✅ cleared these out again today. For future cross-app temporary alerts, let's file issues in the shiny new sul-dlss/global_alerts.
