### ISSUE TITLE
Change label below thumbnail in digital collection film-strip preview; analyze what 'total quantity of digital items' means

### ISSUE THREAD

**Issue by cebraj** [sul-dlss/SearchWorks#2581]
Example collection record: https://searchworks.stanford.edu/view/9102342

Now that the digital serials model is being adopted more for archival collections that include serials, I've received comments about the film-strip preview on a collection record page- for example, when a thumbnail represents a serial catkey record and has, let's say 4 digital objects attached to it, the thumbnail has a small label below it that says "4 images", letting the user know there is more than one thing there. The word 'images' is misleading since it's not really 4 images (though the content is an image format), it's 4 objects/items (often multi-page objects). I think the word 'items' may better represent what is there, but then that may cause confusion in relation to the information displayed below the film-strip that tells you the total quantity of digital items/objects in the collection.

Furthermore, the serial catkey record represented by one thumbnail is only counted as 'one thing' in the total quantity of digital objects in the collection. That might be ok in the above scenario where that small label below the thumbnail indicates there are more things to see, but when a collection has mixed image and audiovisual content, the digital preview displays differently and there is no film-strip. This record may better exemplify that:
https://searchworks.stanford.edu/view/7154358

Note it says there are 8 digital items, but when you click on "Montery Jazz Festival posters" you see there are 62 objects on that catkey record. But, because it's in the digital serials model, it gets counted as one thing (with 62 parts).

Perhaps this is something that can be reviewed with the Gryphon Search team.

**Comment by saseestone** [comment]
Re: the "4 image" label that appears under the thumbnail in the preview.  I noticed that when you click into the object, the label on the top changes to "x parts".  It seems to me that these two labels should match.  Is that correct?  And does "parts" make sense to apply to the label under the preview thumbnail?

![image](https://user-images.githubusercontent.com/14897546/107298545-7c35bf80-6a2a-11eb-989d-f8cfe0c05cf2.png)

**Comment by cebraj** [comment]
Thanks @saseestone ! I think "parts" makes sense as the label under the thumbnail. I agree that the two labels should match.

**Comment by saseestone** [comment]
Closing this issue now that we have two separate issues describing what's needed.
