### ISSUE TITLE
Add call number browse for Internet Resources with 050

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#2604]
Vitus and Law library staff have requested that we add a call number browse for electronic resource records with an LC call number in the 050 field.  

Examples of records with no call number browse displaying: 
https://searchworks.stanford.edu/view/13200515
https://searchworks.stanford.edu/view/13757960

JIRA issues with the feedback:
https://jirasul.stanford.edu/jira/browse/SW-3939
https://jirasul.stanford.edu/jira/browse/SW-3834

**Comment by cbeer** [comment]
Is this only call number browse, or does it include other features enabled by call numbers (e.g. the call number facet, call number search)?

If there's data in the 050 field, should we definitely treat it as an LC or do we need to do some data validation?

**Comment by saseestone** [comment]
Excellent questions.  I suspect it should include other features enabled by call numbers.  My understanding of the 050 tag is that it's reserved for LC call numbers.  

I will confirm both answers with Gryphon Search today at 3pm and update here.

**Comment by saseestone** [comment]
Confirmed that we should include other features enabled by call numbers (facet, call number search). 

We should treat the 050 as LC. Kevin Kishimoto raised mild concerns about call numbers provided in vendor supplied records of electronic sound recordings. They have an 050 with 4 in the second indicator. The "call numbers" are constructed using the composer's name and a number (e.g. Bach A1). If possible, we'd want to NOT include these records. I couldn't find an example record.  He's looking for one to provide.

**Comment by cbeer** [comment]
I remember discussing this, but I can't remember the resolution.. what should we display where it says `eResource`?

![Screen Shot 2021-03-17 at 08 49 23](https://user-images.githubusercontent.com/111218/111496599-ae0f0580-86fd-11eb-908f-866312a0f515.png)

![Screen Shot 2021-03-17 at 08 47 52](https://user-images.githubusercontent.com/111218/111496334-76a05900-86fd-11eb-9fe2-7fd4e5879664.png)

**Comment by jkeck** [comment]
I _think_ the concern that I recall was that somebody might think that they can get the item from the shelf somewhere if they can see the call number (even through Stanford Libraries isn't a specific physical location).  To (most) end users the call number is a shelf locator and if it can't be used to locate the item on the shelf then we shouldn't show it.

This is just my recollection.  If we did display the call number I think we would need to indicate that it is an internet only resource some other way.
