### ISSUE TITLE
Counts in search result previews don't match actual query results

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/SearchWorks#2662]
From sharing links in Slack,  I see that the link preview counts of results don't match what SW shows to the user. For example: https://searchworks.stanford.edu/?f%5Baccess_facet%5D%5B%5D=Online&f%5Baccess_facet%5D%5B%5D=At+the+Library

Screenshot of SearchWorks, showing 2,148,050 results:
![Screenshot of SearchWorks, showing 2,148,050 results](https://user-images.githubusercontent.com/73732/118020005-7d6ad700-b30e-11eb-941d-fb7e09f444f3.png)

Screenshot of Slack preview, showing 905,413 results:
![Screenshot of Slack preview, showing 905,413 results](https://user-images.githubusercontent.com/73732/118020152-9ecbc300-b30e-11eb-8782-a59cf67c0ff2.png)

**Comment by cbeer** [comment]
It looks like we didn't throw the feature flag on the bot boxes to show Hathitrust ETAS messaging, or to count ETAS material as available online. I'm not sure if that was intentional (or made sense when we thought temporary meant less than a year?)

**Comment by anarchivist** [comment]
We're turning off ETAS in the fall, probably, so I don't think we need to make this change.
