### ISSUE TITLE
mhld display of 867 note has a line break making it difficult to interpret

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#2694]
Example record: https://searchworks.stanford.edu/view/12688386

The 867 note "Library keeps latest only" applies to the Supplement, but the way the line breaks its hard to determine if the statement applies to the main volume, the supplement or both.

Somewhat related to https://jirasul.stanford.edu/jira/browse/SW-3824

JIRA issue: https://jirasul.stanford.edu/jira/browse/SW-2000

**Comment by cbeer** [comment]
Is this related to or a duplicate of #1974?

**Comment by saseestone** [comment]
I think of them as related, but not duplicative.  #1974 is about organizing the "library has"  info into div and holdings data into ul in such a way that the "library has" statement doesn't duplicate AND the holdings info is easier to interpret.

And this one is also related to displaying information so it's easier to interpret, but seems to be more about the line break that occurs.  In the example record you can't tell which holding the " Library keeps latest only" statement is referring to.
![image](https://user-images.githubusercontent.com/14897546/123136645-06922500-d408-11eb-9e7c-85393fe4e4a4.png)

**Comment by cbeer** [comment]
I guess I was thinking JV's "Improve the layout" bullet over in #1974 would address this?

**Comment by saseestone** [comment]
Closing after adding this example to 1974.
