### ISSUE TITLE
Modify Education Library label

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#2699]
The Education Library building will be closed for earthquake retrofitting (for approx. 3-4 years).  The collection will be moved to SAL1&2, but retain Library = EDUCATION in Symphony.  

**Physical move is scheduled for July 19th**, so would be good to time the label change with the physical move.  (Though the library is closed, and will remain that way - so we don't have to be perfect.) Request links should continue to appear on the collection through the move, and through the construction period.

Staff have asked that we update the library label in SearchWorks to indicate the collection has been moved.  Gary and the Education staff like the label "Education (at SAL1&2)"

Changes need to be made in:
- [x] library facet
- [x] At the Library block in the record view

Maybe elsewhere?

It is just a label change. Hours node should stay the same for now.  
No items will be placed on EDU-RESV, so we don't need to worry about it.

Related to https://github.com/sul-dlss/sul-requests/issues/1186

**Comment by cbeer** [comment]
Are we disabling the location-specific facet for Education (I'm guessing yes, because it's... not useful at the moment)?
https://searchworks.stanford.edu/?f%5Bbuilding_facet%5D%5B%5D=Education+%28Cubberley%29

**Comment by cbeer** [comment]
Reindexed all but 8 of the EDUCATION items with in the nightly dump.
