### ISSUE TITLE
Table of contents label not displaying on PURL or SW record

### ISSUE THREAD

**Issue by cebraj** [sul-dlss/SearchWorks#2710]
The MODS for this item has a value for element tableOfContents but there is no label displaying, so the value text looks like it's part of the Abstract/Summary.

The default label should be "Table of contents" unless someone adds an attribute to the element for a custom displayLabel.

Example item: https://purl.stanford.edu/mn521kw5258

As a temporary workaround, I typed in "Table of contents:" as part of the data, so it is clear to the user what all that text means. But it should display separately from the Abstract/Summary and have its own header label.

**Comment by cbeer** [comment]
I'm not seeing anything in Searchworks v2.4.10 (4 Sep 2014) that suggests we were doing anything different with abstracts.

**Comment by cbeer** [comment]
I guess https://github.com/sul-dlss/SearchWorks/issues/142 kinda suggested no labels, and that was changed for subjects in https://github.com/sul-dlss/SearchWorks/issues/241#issuecomment-50833827.
