### ISSUE TITLE
Articles+ sessions for authenticated users don't work properly in Chrome/Edge

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/SearchWorks#2761]
Patrons and staff are reporting issues accessing restricted records and full text available through Articles+ even when logged in, or after login. This seems to impact users only using Chrome or Edge. On my machine, this is on Chrome 95.0.4638.69, Chrome (Canary) 98.0.4697.0, and Edge 95.0.1020.44 on Mac OS 10.15.7. Firefox (93.0) and Safari (15.0) work fine. 

Given the large number of reports, this is something that should probably triaged soon; however, @cbeer notes that this may require several days of investigation given the complexity of SearchWorks session handling.

**Examples:**

* [SW-4033](https://jirasul.stanford.edu/jira/browse/SW-4033): [Restricted record](https://searchworks.stanford.edu/articles/agr__IND607306217) - when logged in, users see `This title is not available for guests. Log in to see the title and access the article.`
* [SW-4063](https://jirasul.stanford.edu/jira/browse/SW-4033): [Restricted full text](https://searchworks.stanford.edu/articles/edsbl__vdc.100092542464.0x000001) - when logged in, users see `Sorry, the PDF download was not successful because you are currently in guest mode. Log in to try the download again.`

**Comment by camillevilla** [comment]
Related: sul-dlss/operations-tasks#2811

**Comment by cbeer** [comment]
Fixed by https://github.com/sul-dlss/puppet/pull/7244
