### ISSUE TITLE
Translate new Symphony location

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#2775]
A new Symphony Home Location is being created this week.  Location = SCIFI

We should translate the location to "Science Fiction Collection".  It will be a circulating collection, so should display the green checkmark as the available status icon, and should be requestable when checkedout.

**Comment by saseestone** [comment]
Ok - that last sentence could be confusing.... Basically, I've lost track of when we need to enable locations.  This particular one should be enabled for HoldRecall only, using the logic that is used for most campus locations that aren't eligible for paging or scanning.

That might be even muddier, so I'd appreciate any feedback on how you want me to indicate this in future tickets. :)

**Comment by cbeer** [comment]
What item types are in the collection? And.. what library is the collection physically in? I suspect the default rules will apply and give the right behavior, but 🤷‍♂️

**Comment by saseestone** [comment]
Item type = STKS
Lib= ENG
