### ISSUE TITLE
Update subjects display on the record view

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/SearchWorks#2776]
- [ ] Include MARC 647 fields in the subjects list on the record view
- [ ] Remove MARC 654 (somewhat screwy AAT hierarchical thesaurus data affecting 787 records)

See SW-4043 and SW-4023

**Comment by corylown** [comment]
Related PR: https://github.com/sul-dlss/searchworks_traject_indexer/pull/579 adds field 647 to subject fields for indexing (search).
