### ISSUE TITLE
Translate new location for Hohbach Hall magazines

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#2781]
The new location was created yesterday in Symphony = MAGAZINE.

It looks generic, but is meant to be used only for the newly created Hohbach Hall Magazine Collection. The location translation in SW should be "Hohbach Hall: Magazine Collection"

Materials will start to go into that new location next week (12/13/21).  All will be unbound periodicals with holdings statements. No items will circulate, nor should they be enabled for requests.

**Comment by cbeer** [comment]
Which item type codes are used in that location?

**Comment by saseestone** [comment]
Confirmed that the Item Types will be PERIUNBND and/or NONCIRC.
