### ISSUE TITLE
New display label for MARC 520 with 1st indicator 4

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#2839]
The anti-racist description group has determined that they will place content warnings in the MARC 520 field with a first indicator 4.  Records with a 520 4 should display the label "Content advice". 

Records with a 520 and any other indicators should continue to display under the label "Summary"

Example record: https://searchworks.stanford.edu/view/12725921
In this example, the 520 2 should display under "Summary" and the 520 4 should display under "Content advice".

Also note that if a record has a 520 4 AND a 920, both fields should display.  We're currently suppressing the 520 if a 920 is present, and that will need to change.
Example record: https://searchworks.stanford.edu/view/11474436

**Comment by corylown** [comment]
@saseestone before I get too far along on this, wanted to check if the following display of this info is what you have in mind:

## Record 12725921
<img width="747" alt="Screen Shot 2022-06-30 at 1 46 48 PM" src="https://user-images.githubusercontent.com/458247/176743846-e811db38-8042-4f3d-ba7e-a58765fd883b.png">

## Record 11474436
<img width="723" alt="Screen Shot 2022-06-30 at 1 46 59 PM" src="https://user-images.githubusercontent.com/458247/176743820-a65aeaab-cafe-4e5c-9856-640ea49d3b4b.png">

**Comment by saseestone** [comment]
This looks right to me! Many thanks for prioritizing this!
