### ISSUE TITLE
Add icon to "Request" buttons

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/SearchWorks#2902]
Selecting a "Request" button in Searchworks triggers an action that opens a page in a new tab. Although we do include a `title` attribute on the button that says "Opens in new tab", users don't always see this and aren't necessarily aware that a new tab has been opened when they select the action, which can create confusion (e.g., expecting a "Back to previous page" link to be available on the newly opened page). 

To increase user awareness, we can add an icon to the Request button to more strongly indicate that selecting the button will result in a new window being open:

<img width="382" alt="FA-icon" src="https://user-images.githubusercontent.com/101482/178811753-dae93022-1f11-49cb-b293-25d0fe5dc42f.png">

## Icon to add
It looks like we primary use FontAwesome for icons in Searchworks. The one I used in the mockup above is https://fontawesome.com/icons/arrow-up-right-from-square?s=solid (I'd prefer the regular or light version but those require a FontAwesome Pro subscription, which I don't think we have?). 

Alternatively, if there are any concerns about that icon, we could use this Bootstrap icon: https://icons.getbootstrap.com/icons/arrow-up-right/, which would look like this (visually okay but maybe doesn't send the message as strongly):

<img width="382" alt="BS-icon" src="https://user-images.githubusercontent.com/101482/178811784-2d38609d-e5c4-418c-9b51-ffef4677db74.png">

---

Not sure how directly relevant this is, but in my mockup I used `4px/0.25rem` of space between the icon and the button label, and icon size should be the same as the button label font size (`12px`) to avoid making the button height taller than it currently is.

## Relevant buttons 
We currently display "Request" buttons (with some variation in their labels) in several Searchworks contexts:
- On a search results page, when the user selects the "Check availability" button to expand the view to display a box showing the item holdings
- On a item record page, in the At the library sidebar box

I believe the relevant button label variations are:
- `Request`
- `Request on-site access`
- `Request via Finding Aid`

**Comment by cbeer** [comment]
How about https://icons.getbootstrap.com/icons/box-arrow-up-right/?

**Comment by ggeisler** [comment]
Sure, looks good to me.

**Comment by cbeer** [comment]
👍 . I'm trying to get us away from font-awesome (v4, at least) to avoid things like #2629 .

**Comment by ggeisler** [comment]
Right, okay, thanks for the reminder!
