### ISSUE TITLE
Line breaks are not displaying in SW (or PURL, or Exhibits)

### ISSUE THREAD

**Issue by caaster** [sul-dlss/SearchWorks#2910]
Line breaks are not displaying in SearchWorks for Martin Wong objects in the Exhibition history facet. See https://github.com/sul-dlss/mods_display/issues/78 for more detailed discussion.

List of Wong fixture objects to test this functionality:
druid:pd464yj1635
druid:vh115kc5665
druid:ns768mm2958
druid:qr959jx6172
druid:mg552nh0170

In addition, line breaks were displaying a few days ago on the PURL page for the above objects, and also in the unpublished [Wong exhibit](https://exhibits.stanford.edu/martin-wong) on the "More details" view -- but the line breaks have now disappeared in both of these places.

We have a hard deadline for the resolution of this issue of NLT 30 August 2022. Thank you.

**Comment by cbeer** [comment]
We're not seeing any line breaks in those objects. The other example objects Arcadia provided seem fine:

https://purl.stanford.edu/bb782yf9388
https://purl.stanford.edu/bb490zh2544

is it possible the metadata was updated recently?

**Comment by caaster** [comment]
I am checking in with @arcadiafalcone to see what I may have missed or misunderstood. The 2 example objects above are not Martin Wong objects.

**Comment by caaster** [comment]
Found out that the MD for the 5 Wong druids listed above, that had the line breaks - was inadvertently overwritten. This will be fixed later today and I will note that here in the comments. Then we can see what is happening with accurate fixtures.

**Comment by cbeer** [comment]
searchworks-preview looks fine to me now. I saw a significant indexing backlog due to a massive amount of Catalhoyuk content being republished (or remediated?). The metadata changes from today were only just reindexed
