### ISSUE TITLE
prototype RTAC API for availability lookups

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/SearchWorks#2964]
created from #2905, see that ticket for investigation details.

**Comment by corylown** [comment]
A rough sketch: https://github.com/sul-dlss/SearchWorks/compare/okapi

Still missing:
- Wire up barcode/item uuid for JS status updates
- Maybe we want to extract the `FolioClient` class to a gem so we can use it in all the apps?
- Refactor/tests

**Comment by thatbudakguy** [comment]
depends on https://github.com/sul-dlss/searchworks_traject_indexer/issues/696

**Comment by corylown** [comment]
depends on https://github.com/sul-dlss/SearchWorks/issues/2995

**Comment by thatbudakguy** [comment]
closing since prototype work  is done — still open whether we will use the approach but the code is there for reference.
