### ISSUE TITLE
Move EZproxy url transformations to SearchWorks

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/SearchWorks#2979]
currently, ExportSearchWorks transforms URLs in the MARC 856|u field to add EZProxy prefixes for records from several libraries, so the URLs are already changed before they get to traject.

the configuration that drives this is several files (one for each library) stored on an AFS mount that are lists of domains that should get an EZProxy prefix added. personnel from each library are able to access the files and edit them directly on a regular basis to add new domains.

we want to shift this configuration out of the indexing step entirely and do the transformations in SearchWorks. to do this, we want to convert the current file-based configuration into configuration directly in SearchWorks. we think that the people who edit the files on the AFS mount now should be comfortable editing the config directly on GitHub (i.e. "clicking the pencil" and using the web UI to make changes).

**Comment by thatbudakguy** [comment]
@shelleydoljack is this https://github.com/sul-dlss/ExportSearchWorks/blob/22bfd6be1cb39bfc54724c355d72bce0b9ee516e/uni_dump_sworks.pl#L993-L1131 ?

**Comment by shelleydoljack** [comment]
That's part of it. We determine which hash (Lane, Law, or SUL) to lookup the domain name in https://github.com/sul-dlss/ExportSearchWorks/blob/22bfd6be1cb39bfc54724c355d72bce0b9ee516e/uni_dump_sworks.pl#L944-L960 .

**Comment by ahafele** [comment]
Moving a slack message to here - I spoke with the team managing this in Acquisitions and they are OK with the change. However, it is not Irina Trapido who is currently making the changes to the documents on AFS, but her team (1-2 people). So there will need to be some github training at some point.

**Comment by thatbudakguy** [comment]
what's involved in getting access to this AFS mount for development purposes?
