### ISSUE TITLE
[SearchWorks/prod] NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/SearchWorks#2982]
## Backtrace

    line 61 of [PROJECT_ROOT]/app/helpers/xml_api_helper.rb: block in get_authors_for_mobile
    line 60 of [PROJECT_ROOT]/app/helpers/xml_api_helper.rb: each
    line 60 of [PROJECT_ROOT]/app/helpers/xml_api_helper.rb: get_authors_for_mobile

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50022/faults/87414612)

**Comment by dnoneill** [comment]
Full backtrace link doesn't work because outside retention of honeybadger account.
