### ISSUE TITLE
Add more metadata to the availability.json response

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/SearchWorks#3008]
these responses, e.g. https://searchworks.stanford.edu/view/11835941/availability.json, get consumed by sul-requests and used to populate data when making a request. that data can then be used to send the relevant metadata out to external systems like Aeon (see https://github.com/sul-dlss/sul-requests/issues/1322) so that the request form there is pre-populated.

the assumption behind this ticket is that the more metadata we can send out to Aeon, the better — it will help staff disambiguate items and find the relevant item for the request more quickly. if this isn't true (or it's not helpful to have anything more than title, call number, barcode) then this ticket can be discarded.

the available fields we can populate on the Aeon request form, and thus the things we _could_ send if we have data, are:

- title (we have this data already)
- author/creator
- place of publication
- publisher
- date
- edition
- volume/box
- issue/copy
- call number (we have this data already)
- collection name/location

**Comment by thatbudakguy** [comment]
some ideas:
* use `author_1xx_search` for author
* use `pub_date` for date
* use `pub_country` for place of publication

less clear:
* edition, volume, box, issue, copy...do we have this? is it effectively captured by the call number?
* collection name/location — use stuff in the `collection_facet`?
* add the finding aid URL to this so that we can make sending people out to OAC easy in sul-requests?

**Comment by thatbudakguy** [comment]
there's no dedicated place on the Aeon form to store the barcode, but we could put it in a different field (or maybe the notes field) if we want.

**Comment by cbeer** [comment]
I'd just map title, author (from `author_person_display`, or a [combination of multiple fields](https://github.com/sul-dlss/SearchWorks/blob/1e03ee62765fb3cd06d7235ccc2c4f878a15db05/app/models/concerns/schema_dot_org.rb#L16-L31)?), and date. We can let the magic symphony<->Aeon integration fill in the rest.

edition, volume, box, issue, copy are be item or holdings-level, and the call number should be sufficient. 

> add the finding aid URL to this so that we can make sending people out to OAC easy in sul-requests?

I think we should do that. We have it, and will make things both easier and more consistent.

**Comment by saseestone** [comment]
So the magic Symphony<->Aeon thing isn't a true integration. It has to be initiated by staff within the staff client.

So if we can get barcode of the copy into Aeon field "Item Number" that would be better.

**Comment by thatbudakguy** [comment]
@saseestone Aeon doesn't have a field called "Item Number" — should we put the barcode into "Issue / Copy"?
