### ISSUE TITLE
Migrate Universal Analytics (UA) to Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by corylown** [sul-dlss/SearchWorks#3036]
Universal Analytics (UA) properties will [stop collecting data as of July 1, 2023](https://support.google.com/analytics/answer/11583528?hl=en). The data in the existing UA property will remain available for an unspecified period of time. In order to collect data after July 1, 2023 we will need to create a new GA4 property and add the newer `gtag.js` snippet to the application in order to collect data into the new GA4 property.

Spreadsheet that tracks properties and whether each property is tracking events: https://docs.google.com/spreadsheets/d/1WWt3l-RFqfb_L2j01Y7JBUWJ2OnX0Hi4xLmIW8abNLw/edit?usp=sharing

- [x] [Add a Google Analytics 4 property](https://support.google.com/analytics/answer/9744165#zippy=%2Cin-this-article)
- [x] [Add the Google tag to the application](https://support.google.com/analytics/answer/9304153#zippy=%2Cadd-your-tag-using-google-tag-manager%2Cadd-the-google-tag-directly-to-your-web-pages)
- [x] [Set up event tracking as desired](https://support.google.com/analytics/answer/11091025#zippy=%2Cin-this-article). NOTE: _everything_ is an event in GA4 and it automatically collects some events.
- [x]  Set up debug_mode filter (https://support.google.com/analytics/answer/13296662?hl=en)
- [ ] Optionally, download and archive the historical UA data.

NOTE: There is currently a [setting available](https://support.google.com/analytics/answer/11150547) that will send events from `analytics.js` (UA) to GA4 properties. However, Google does not guarantee this will continue to work after July 1, 2023. This is not recommended as a migration path for event tracking.

**Comment by marlo-longley** [comment]
Update from Sarah: Kay Teel uses the existing GA.

**Comment by marlo-longley** [comment]
Copied from the Draft PR:

As of 2/2/2023, Sarah and Kay Teel are analyzing how this transition will impact their reports. They plan to be back in touch with me in about 1 month.

we may need to set up a staging property after all, so that KT can test out reporting (which can't happen with the ephemeral analytics coming in from debug_mode)
we will need to make shared_configs PRs to each SW branch before this can go live.

**Comment by marlo-longley** [comment]
Don't switch over until after 4/21
Otherwise Kay and Sarah say OK

**Comment by saseestone** [comment]
Fine to move ahead without a staging environment.  We'll set up new reports after the move to UA.

**Comment by thatbudakguy** [comment]
@marlo-longley can we close this?
