### ISSUE TITLE
For 12/19/22: Update Bento block to include EarthWorks (and remove Yewno)

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#3041]
For deploys on 12/19/22 we need to remove Yewno from all our properties, including the SearchWorks & Articles+ homepages. We also need to add EarthWorks.

Here's the Bento block now:
![image](https://user-images.githubusercontent.com/14897546/205405140-ceeb76aa-f200-4365-9ac9-eee65c56766b.png)

For the EarthWorks block:
- [ ] We need an image added to the image library. Astrid will provide.
- [ ] Description. How about: ~~"Geospatial (GIS) data discovery tool for collections at Stanford and beyond."~~  "Geospatial content, including GIS datasets, digitized maps, and census data."

**Comment by saseestone** [comment]
New description text. Please use: "Geospatial content, including GIS datasets, digitized maps, and census data."

Why? because the SearchWorks & Bento blocks show a list of what you will find when you search in the tool - rather than a statement about what the tool is.

**Comment by astridu** [comment]
![earthworks_tile](https://user-images.githubusercontent.com/42216982/207762966-d4be5524-3ef4-4f7f-8ecf-c0e945b4f195.png)
