### ISSUE TITLE
New EarthWorks image

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#3048]
Lots of feedback about the EarthWorks image being too dark.  Can we use this instead?
![earthworks_tile_light](https://user-images.githubusercontent.com/14897546/208160517-271e6ada-cb4f-4377-9b9c-4a3df1414a0c.png)

**Comment by saseestone** [comment]
Should be updated for Bento too

**Comment by corylown** [comment]
https://github.com/sul-dlss/sul-bento-app/issues/549
