### ISSUE TITLE
Results display "show all" buttons confusing when library has two locations with "show all"

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#3087]
Reported via feedback: https://jirasul.stanford.edu/jira/browse/SW-4152

Example search: https://searchworks.stanford.edu/?search_field=search&q=398732+AND+estuaries

If you click on "Check availability", the SAL3 record includes two locations (PAGE-GR and PAGE-HP) with multiple volumes.  The "show all" links for both locations are stacked one after another instead of relating to each individual location.

![image](https://user-images.githubusercontent.com/14897546/225402420-ecfa921d-0718-4c3b-bf95-629b5db119dd.png)

**Comment by cbeer** [comment]
I think I added the `<tfoot>` in https://github.com/sul-dlss/SearchWorks/pull/3067. It doesn't have to be a `tfoot`, maybe it should be just another `tbody`?

**Comment by hudajkhan** [comment]
The alternative would be to always make them different tables entirely, which seems to be the case on the main item view page.  For now, I'm changing the <tfoot> to <tbody>.

**Comment by hudajkhan** [comment]
Linked to https://github.com/sul-dlss/SearchWorks/pull/3096 . Thanks for the merge @jcoyne !

**Comment by hudajkhan** [comment]
Appears to be fixed in production now.
