### ISSUE TITLE
Move EZproxy url transformations to Searchworks

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/SearchWorks#3093]
This work was done in Searchworks with https://github.com/sul-dlss/SearchWorks/pull/3013.

Still outstanding:

- [x] turn off ezproxy url transformation from the symphony export
- [x] work with stakeholders to clarify and document ezproxy url update process
- [ ] ~~only add ezproxy prefixes if the field contains e.g. `856 |z Available to Stanford-affiliated users` (Q: does this apply to coordinate libraries too?)~~ Moved to separate issue: https://github.com/sul-dlss/SearchWorks/issues/3112

**Comment by corylown** [comment]
Note from Shelley on 3/22 on this issue: https://jirasul.stanford.edu/jira/browse/SW-4154

> Regarding: turn off the ezproxy routing that is happening in LibSys land (some part of the exporting adds ezproxy urls to the marc) this is turned off already; no records are getting ezproxy prefixes during SW export. a full reindex from this month should have fixed all records. the only thing getting ezproxy now are being added by the eloader preprocessing scripts. 

For the question on part 3 of this issue, "does this apply to coordinate libraries too?" -- it sounds like Irina was going to follow up with Lane. We might just need to ask Irina.

**Comment by corylown** [comment]
Closing this issue:

- According to Shelley's comment on https://jirasul.stanford.edu/jira/browse/SW-4154 Symphony is no longer adding the prefix.
- The EZProzy update process is documented here: https://docs.google.com/document/d/1IMWgP6i1gIJ8WlY-XOWMv-g1JaCeEnYfTzdh-ppRUdk/edit?usp=sharing
- I've created a new issue for selectively adding the prefix based on the 856$z value: #3112
