### ISSUE TITLE
Use the label "Partial contents" for partial tables of contents

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/SearchWorks#3103]
MARC 505 fields with a 1st indicator 2 should have the display label "partial contents".

E.g. http://searchworks.stanford.edu/view/9082633

See also:

SW-3964
SW-1356
SW-4016

**Comment by saseestone** [comment]
Confirmed.  Please use "Partial contents" label for records with MARC 505 fields with a 1st indicator of "1" and "2". 


Example record with a 1st indicator of "1" (note that this example also has an 880 for the 505 field.): https://searchworks.stanford.edu/view/14654904
