### ISSUE TITLE
[SearchWorks/prod] NoMethodError: undefined method `excluding' for #<ActionController::Parameters {"0"=>"5990462"} permitted: false>

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/SearchWorks#3107]
## Backtrace

    line 63 of [PROJECT_ROOT]/lib/page_location.rb: collection_parameters?
    line 15 of [PROJECT_ROOT]/lib/page_location.rb: access_point
    line 41 of [PROJECT_ROOT]/lib/page_location.rb: databases?

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50022/faults/87790220)

**Comment by jcoyne** [comment]
It looks like this is a robot ("facebookexternalhit").  Do we want to support this UA?

**Comment by cbeer** [comment]
It'd be nice if it didn't go to honeybadger, at least. Blacklight has code to fix up Facebook's params that might help 🤷‍♂️
