### ISSUE TITLE
Change source of LANE-MED's proxy prefix hosts lists

### ISSUE THREAD

**Issue by corylown** [sul-dlss/SearchWorks#3114]
Lane maintains its proxy prefix hosts list here: https://lane.stanford.edu/eresources/ezproxy-servers.txt

The values at lines beginning with `T ` contain the hosts that should have the prefix applied. They would like it if we could have SearchWorks apply the values from this file automatically instead of having to maintain a separate file in SearchWorks.

See: https://docs.google.com/document/d/1IMWgP6i1gIJ8WlY-XOWMv-g1JaCeEnYfTzdh-ppRUdk/edit#

**Comment by jcoyne** [comment]
@corylown 

> apply the values from this file automatically

Applied to what?

**Comment by corylown** [comment]
@jcoyne yes, the hosts from https://lane.stanford.edu/eresources/ezproxy-servers.txt should be applied to the [lane_proxy_file.txt](https://github.com/sul-dlss/SearchWorks/blob/62b7573978dd0ac5646bf01e47c62f26552c48f2/config/ezproxy/lane_proxy_file.txt) file (or otherwise loaded in such a way that it can be added to [this hash](https://github.com/sul-dlss/SearchWorks/blob/62b7573978dd0ac5646bf01e47c62f26552c48f2/lib/search_works/links.rb#L8)).

I think we want to trigger this on a schedule -- once daily?

**Comment by jcoyne** [comment]
@corylown would the intention be to have this done on the CI server and it can make PRs to SearchWorks with the changes applied?
