### ISSUE TITLE
Provide real-time availability lookups in Searchworks with FOLIO

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/SearchWorks#3135]
We have two obvious choices:
- continue to implement an asynchronous, AJAX driven availability lookup (replacing vufind.pl with... something that queries FOLIO APIs) for real-time lookups
- (measure & tweak to) determine that FOLIO indexing latency is small enough that we can index the current item status quickly enough that the index is as reliable as any real-world race condition (e.g. a patron browsing stacks for an item that someone already took to go check out)

The second option is kinda appealing architecturally (and sets us up for a "and I can check it out today" facet), if we can get away with it. 

- [ ] figure out what information the vufind.pl script returns (and that we're using in searchworks)
- [ ] make sure we're indexing the right information (or figure out which FOLIO APIs return it for option 1)
- [ ] display (near)-real time current location(/availability) information for parity with Symphony-driven displays

Some work on this was possibility done (or considered) in the MVP work cycle.

**Comment by jcoyne** [comment]
Our current latency is something like 1 hour (cron runs hourly) + 30 min (for querying) + 15 min (for solr commit). This latency seems pretty large to me. Who can say whether this is small enough?

**Comment by cbeer** [comment]
If we don't think there's a way to get the latency under 10-15 minutes, I think we'll need to make requests to the FOLIO APIs. Perhaps we should figure out the async pattern first (for parity) and then figure out how to improve our indexing latency.
