### ISSUE TITLE
Phase 1 to display the MARC 795

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#3150]
This is the first phase of an effort to display the MARC 795 tag, containing Collection Name for physical collections. More information about the effort can be found in: https://github.com/sul-dlss/SearchWorks/issues/3027

Steps identified include:

- [x] 1. Add the 795 ($a and $p) to the Subject index (since public services staff are accustomed to the collection name being there)
- [x] 2. Add the 795 ($a and $p) to the display in search results. Use label "Collection". If the record also has a Finding add or link to a digital collection, place the 795 below the Finding Aid link or the digital collection link.
- [x] 3. IF there are multiple 795 on the same record, display up to two on the results page. Use "more" if there are more than two. Show all the 795s on the record page.
- [x] 4. Change label used for digital collections in search results to "Digital collection" (currently just "Collection")
- [x] 5. In the record view, move the display of the 795 to the top of the record - near Title, Responsibility, Imprint, and Series.
- [x] 6. Hyperlink the 795 ($a and $p) collection name in both the search results and record view, continuing to use the Subject term index.

**Example records** 
Example record: [Poetry](https://searchworks.stanford.edu/view/374067)
Example record with multiple 795 tags: [Asian American review](https://searchworks.stanford.edu/view/5528103)
Example record with 795$p: [Gedanken zu Führungen durch das Goetheanum in Dornach ; Das Ruhrgebiet im Erlebnisfeld der Geschichte](https://searchworks.stanford.edu/view/3441645)
Example records with both physical and digital collections on the same record: [City of San Diego](https://searchworks.stanford.edu/view/11878116) and [Jesús Lara [sound recording] : poesía y prosa](https://searchworks.stanford.edu/view/4416852) and [Robert Creeley Papers](https://searchworks.stanford.edu/view/4084039)

Metadata documentation on use of the 795 field: https://consul.stanford.edu/display/MD/Collection+name+in+SUL+catalog+records

**Comment by saseestone** [comment]
I need to check one detail with Ben Albritton this week. I'll remove "Draft" when it's ready

**Comment by saseestone** [comment]
Just noticed in the metadata documentation that $6 could be used for linking to a 880 field for non-Latin script.

**Comment by cbeer** [comment]
Previous indexing work (#749):
https://github.com/sul-dlss/searchworks_traject_indexer/blob/899e7a88748336cb92c6346714ca688c4283704b/lib/traject/config/sirsi_config.rb#L2552-L2601
