### ISSUE TITLE
Add/change LANE location labels

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/SearchWorks#3207]
![Screenshot 2023-06-07 at 15 27 13](https://github.com/sul-dlss/SearchWorks/assets/111218/313bca1b-75a6-4ed7-a050-16b94e58e8dd)

**Comment by thatbudakguy** [comment]
waiting on lane data to be fully loaded.

**Comment by thatbudakguy** [comment]
@saseestone to give us these location name mappings

**Comment by saseestone** [comment]
Waiting for confirmation from Lane that I should use what is currently in the FOLIO Location "Discovery display name".

**Comment by cbeer** [comment]
No Lane-specific work; discovery display labels will fix this generally.
