### ISSUE TITLE
Add law hosts to law_proxy_file

### ISSUE THREAD

**Issue by huang559** [sul-dlss/SearchWorks#3245]
Hello Cory,

Could you replace the current law_proxy_file with the attached list of law hosts? Please let me know if you have questions or need other information.

Thanks, 
Qi

[GitHub Law host list_ticket.xlsx](https://github.com/sul-dlss/SearchWorks/files/11936980/GitHub.Law.host.list_ticket.xlsx)

**Comment by corylown** [comment]
Completed via https://github.com/sul-dlss/SearchWorks/pull/3241
