### ISSUE TITLE
Disable real-time availability lookups during Symphony shutoff

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/SearchWorks#3248]
We're planning to turn off symphony web services during the FOLIO cutover to prevent changes to the underlying ILS data. During that time, real-time availability lookups won't work.

In order to prevent patrons from seeing lots of "unknown" statuses for items in SearchWorks, we want to just use the existing MARC 999 status data and not overlay it with our real-time lookup.

For some items, the status will still show as "unknown" — this is expected for items in locations like "ask at X", "see other", etc.

**Comment by corylown** [comment]
One approach would be to add a feature flag that changes the return value of else condition in [Holdings::Status.availability_class](https://github.com/sul-dlss/SearchWorks/blob/master/lib/holdings/status.rb#L34) from 'unknown' to 'available'. And also disable the [livelookup](https://github.com/sul-dlss/SearchWorks/blob/master/app/services/live_lookup.rb).

**Comment by cbeer** [comment]
Another option (using a seam we already have) would be to change the Sirsi::LiveLookup implementation (or add a different LiveLookup) that uses the data in Solr (from current_location, etc) to generate the expected availability response 🤷‍♂️
