### ISSUE TITLE
Use discoveryDisplayLabels from FOLIO

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/SearchWorks#3271]
FOLIO locations have a `discoveryDisplayLabel` that is/should be appropriate for us to use instead of `Constants::LOCS`.

Before making this change, we should do some due diligence to make sure the FOLIO labels are generally appropriate and substantially similar to the existing constants (CB: I wouldn't be surprised if we end up taking the FOLIO labels for 90% of the locations, and still having to override some in Searchworks. If we assemble a list of the questionable differences, Sarah et al can review.)

**Comment by jcoyne** [comment]
I'm not sure we can just swap these out as direct replacement.  The `discoveryDisplayLabel` describes a library and a location within it (e.g. "Green Library Stacks"), where as `Constants::LOCS` just has "Stacks".
