### ISSUE TITLE
D9 website: update links in sul-footer 

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#3346]
I don't know exactly what repo this should go in, but we need to update links in the sul-footer 

![image](https://github.com/sul-dlss/SearchWorks/assets/14897546/c23be49e-b60c-4a05-9522-70fba6c58e60)

- [ ] "Hours & locations" => https://library-hours.stanford.edu/
- [ ] "Ask us" => https://library.stanford.edu/contact-us
- [ ] **Remove** "Opt out of analytics" (If this is problematic to remove, I can create a libguide on this.)

**Comment by saseestone** [comment]
Related to https://github.com/sul-dlss/SearchWorks/issues/3344 and https://github.com/sul-dlss/mylibrary/issues/891

**Comment by jcoyne** [comment]
@saseestone we don't have a single sul-footer. Do you mean for this ticket to go into all of our repositories?

**Comment by saseestone** [comment]
yes, we need to update in all those repos. (Hence my comment above above about not knowing which repo to put the issue in. But I should have been more explicit that the change needs to happen everywhere.)
