### ISSUE TITLE
Hours api link is wrong for biology & chemestry

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/SearchWorks#3369]
Please confirm this is actually a bug before working on this.  

It looks to me like https://github.com/sul-dlss/SearchWorks/blob/98bde95e6b1318f005c3ddc3e875399e941c1b90/config/settings.yml#L121C20-L121C52 is wrong because https://library-hours.stanford.edu/biology/location/biology_library doesn't resolve.  I believe the slug is `falconer` in the Library-hours database.

Similar with `chemestry` and `swain` 
Also `education` and `clubberly`
Also `hoover_archives` and `hoover`
`engineering` and `englib`
`medical` and `lane`
`special_collections` and `spc`

also `earth_sciences` doesn't resolve in library hours.

It looks like searchworks is using https://searchworks.stanford.edu/hours/EARTH-SCI when on a view page like https://searchworks.stanford.edu/view/14818464.  It appears that uses the hours_api_url here: https://github.com/sul-dlss/SearchWorks/blob/master/lib/hours_request.rb#L11

```
HoursRequest.new('EARTH-SCI').full_url
 => "https://library-hours.stanford.edu/api/v1/library/earth_sciences/location/earth_sciences_library/hours/for/today"
 ```

When you curl that API it appears to get a generic response. See the "location_slug":
```
$ curl https://library-hours.stanford.edu/api/v1/library/earth_sciences/location/earth_sciences_library/hours/for/today
[{"id":387605,"day":"2023-08-01","weekday":"Tuesday","opens_at":"2023-08-01T09:00:00.000-07:00","closes_at":"2023-08-01T17:00:00.000-07:00","type":"","notes":"","location_slug":"library-circulation","location_id":48,"closed":false}]
```

**Comment by dnoneill** [comment]
From what I can tell, when the api url is something like biology/location/biology_location locations_hours finds the primary location for that library and displays that in the API.

https://github.com/sul-dlss/library_hours_rails/blob/77302c50483dd705f4386ac69f647d01ec1fbfa5/app/views/libraries/_library.json.jbuilder#L6
