### ISSUE TITLE
Extract locations with location details to a CSV for easier review

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/SearchWorks#3409]
Reviewing location details data entry in FOLIO (or our JSON dumps) isn't very friendly. Just as we're extracting a human-readable CSV for circulation rules, we should transform the FOLIO locations data into a simple CSV with columns for location  attributes and separate columns for each location details key (e.g. `pageAeonSite`, `pageMediationGroupKey`, etc), e.g.:

<google-sheets-html-origin style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">

  | campus.code | library.code | code | discoveryDisplayName | details.availabilityClass | details.holdingsTypeName | details.pageAeonSite | details.pageServicePointCodes | details.pageMediationGroupKey | details.pagingSchedule | details.scanServicePointCode | isActive | name | primaryServicePointObject.name | primaryServicePointObject.code | details |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
0 | GSB | BUSINESS | BUS-SAL3-STACKS | Stacks | - | - | - | - | - | SAL3 | - | TRUE | Business SAL3 Stacks | Sal3 | SAL3 | - |   |   |   |   |   |   |   |   |  
1 | SUL | ARS | ARS-LOCKED | Locked stacks: Ask at desk | - | - | - | - | - | - | - | TRUE | ARS Locked Stacks | ARS Service Desk | ARS | - |   |   |   |   |   |   |   |   |  
2 | SUL | ARS | ARS-REF | Reference | - | - | - | - | - | - | - | TRUE | ARS Reference | ARS Service Desk | ARS | - |   |   |   |   |   |   |  

</google-sheets-html-origin>

**Comment by thatbudakguy** [comment]
See https://github.com/sul-dlss/SearchWorks/blob/master/config/folio/circulation_rules.csv for our nice circrules CSV. we want the same kind of display for `locations.json` in that same directory.

**Comment by thatbudakguy** [comment]
I can't remember how we got FOLIO to expand nested objects in queries in the past, but the `/locations` query doesn't include the data for the primary service point that's show in the above example. How do we feel about additionally pulling down service point info in `Folio::Types` so that we can populate it in the locations CSV? Not worth it?

**Comment by cbeer** [comment]
I think it's useful information to have. I don't see any problem pulling it down, but we could also do this in sul-requests which already has that data 🤷‍♂️
