### ISSUE TITLE
Remove request links for SPEC-COLL items that are status = In process

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#3420]
Items in a Special Collections Location (SPEC-***) with item status = in process should not display request links.  We're seeing them currently in folio-test.

Examples:

- https://searchworks-folio-dev.stanford.edu/view/14640912 (has a copy in location = GRE-STACKS and SPEC-RARE-BOOKS. We should see a request link on the GRE-STACKS copy, but not on the SPEC-RARE-BOOKS.)
- https://searchworks-folio-dev.stanford.edu/view/14540602
- https://searchworks-folio-dev.stanford.edu/view/14540600

SPEC-COLL locations can be found in: https://github.com/sul-dlss/folio_migration/blob/main/mapping_files/locations.tsv

**Comment by cbeer** [comment]
Fixed by https://github.com/sul-dlss/SearchWorks/pull/3425
