### ISSUE TITLE
Remove Subject Specialist link in Help menu

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#3465]
The Help menu needs some design tweaking, as it's been constructed with the old Drupal website (with it's many many service and policy pages) in mind.

That's work that Alan and I can do, but in the short-term we need to remove "Find a subject specialist" and the broken link.

![image](https://github.com/sul-dlss/SearchWorks/assets/14897546/9a93e447-8149-47c0-acbc-f69c3c7be09c)

**Comment by cbeer** [comment]
We should also remove this link from bento?
