### ISSUE TITLE
Replace/update Searchworks fixture data with FOLIO-flavored data

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/SearchWorks#3467]
- [x] uuid_ssi
- [x] item_display_struct

**Comment by hudajkhan** [comment]
Fields in checkboxes are new fields in FOLIO.

**Comment by hudajkhan** [comment]
To begin: review what needs to be cleaned up still, and if there is fixture data (like uuid) that is being generated in the tests that we could just put in the fixture data directly.

**Comment by hudajkhan** [comment]
Even if the values in fixture data are not real, we want the structure of the fixture data to mirror the structure coming back from FOLIO.  This ticket is about ensuring we take the time to review this area.
