### ISSUE TITLE
Revisit item_display entries for electronic resources

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/SearchWorks#3469]
- [x] figure out what searchworks does when you have an eresource with no item_display?
- [x] figure out anywhere else the lack of item_display has an impact
- [ ] we want to stop creating fake item_display in the indexer, if SW can handle it.

**Comment by jcoyne** [comment]
@cbeer I haven't been able to find an eresource without item display (first bullet). I've been doing something like:

```
 curl -s 'http://sul-solr-prod-a.stanford.edu/solr/searchworks-folio-prod/select?fl=id%2Citem_display_struct&indent=true&q.op=OR&q=access_facet%3AOnline%20-building_facet%3A%22Stanford%20Digital%20Repository%22&rows=10000&facet=false' | jq '.response.docs[] | .item_display_struct | select(length == 0)'
```

**Comment by cbeer** [comment]
I don't think there should be any. Nick's first bullet was asking someone to find out what Searchworks does if there isn't an `item_display`, but you'll have to fabricate one.

**Comment by jcoyne** [comment]
I've removed the item_display struct from the fixture 14136548.yml, and reloaded it.  Going to http://localhost:3000/view/14136548 looks just the same as it does without the item_display_struct.
<img width="1189" alt="Screenshot 2024-02-23 at 10 24 11 AM" src="https://github.com/sul-dlss/SearchWorks/assets/92044/23533db8-172e-4af9-a2da-b115f1962d9a">

**Comment by jcoyne** [comment]
Sorry, I was confused by what Sarah said.  I'm looking at several in that result set and I don't see callnumber in `item_display_struct`. However, the field we need to look for is actually `shelfkey` (and `reverse_shelfkey`)
<img width="604" alt="Screenshot 2024-02-23 at 11 42 10 AM" src="https://github.com/sul-dlss/SearchWorks/assets/92044/382d2cd9-507a-45fd-a1d3-91cc46d2ec59">

**Comment by hudajkhan** [comment]
Two different places shelfkeys used: at document level and on item. 
In e-resource case, fabricated shelfkey in item_display. 
Q: Is it possible to not fabricate this information at the item level (we will still need shelfkey info at the document level) and have the code handle e-resources?

https://github.com/sul-dlss/SearchWorks/blob/main/app/models/nearby_on_shelf.rb#L5
https://github.com/sul-dlss/SearchWorks/blob/main/app/models/nearby_on_shelf.rb#L42
