### ISSUE TITLE
Use location/details to link to stackmaps

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/SearchWorks#3470]
see e.g. in the config: https://github.com/sul-dlss/SearchWorks/blob/55c521d5dba09b1e1a19e44b59603f26748dd6f4/config/settings.yml#L121

instead of keeping this around, we can just define on the library/location where you go to get its stackmap.

note that LAW is soon to remove stackmaps entirely (2weeks?)

See https://github.com/sul-dlss/folio-graphql/pull/128

**Comment by marlo-longley** [comment]
Most of the code is written in #3528 but this is blocked until we can get the location details for `stackmapBaseUrl` out of Folio; requires communication on the product side.

**Comment by thatbudakguy** [comment]
potentially unblocked now since data has been added to location details per @saseestone ?
