### ISSUE TITLE
Zero results button is styled oddly with hover and doesn't go anywhere useful;

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/SearchWorks#3541]
<img width="804" alt="Screenshot 2023-09-25 at 12 16 36 PM" src="https://github.com/sul-dlss/SearchWorks/assets/92044/d14570ee-78ba-43ad-a650-40c3938247ac">

When you click the link it goes to https://searchworks.stanford.edu/catalog?q=abawevasf&search_field=search&view=gallery

**Comment by marlo-longley** [comment]
see https://github.com/sul-dlss/SearchWorks/issues/1101

**Comment by marlo-longley** [comment]
@dbranchini @alundgard here is a start to what we discussed. If you are able to ignore the 2nd/lower red "Catalog Start" button for now (I need to link with the team to learn how to override Blacklight here and remove that) -- this is how it's looking and I welcome feedback! Also happy to hop on a call soon to discuss.

<img width="1250" alt="Screen Shot 2023-10-19 at 4 52 02 PM" src="https://github.com/sul-dlss/SearchWorks/assets/1328900/3c64419c-a08b-428e-bb90-7620385d0a05">

**Comment by cbeer** [comment]
> I need to link with the team to learn how to override Blacklight here and remove that

Could you just hide it with CSS? 🤷‍♂️

**Comment by dbranchini** [comment]
Looks good to me and represents exactly what we discussed. It's a much better than the current solution. 

Perhaps for discussion at a later time (and maybe what @alundgard) is getting at above. I wonder if this following works a little better:

- Check spelling, use fewer words to start, **_or remove limits_**:
SHOW the buttons with X option to remove a limit (what's there now minus the "catalog start")
- For example, if you remove limits:
SHOW Call number > "amber" ... finds x results (what's there now)
- If you search all fields:
SHOW "amber" ... finds x results (what's there now)

**Comment by marlo-longley** [comment]
Hi @alundgard @dbranchini -- here's what I got now, including some non-zero possible outcomes ("finds 2 results") as requested by Alan, and incorporating Darcy's language above:

<img width="1223" alt="Screen Shot 2023-10-24 at 3 50 47 PM" src="https://github.com/sul-dlss/SearchWorks/assets/1328900/cd2bfe9e-68d1-4d69-9acb-a92f65b1e8c4">

**Comment by dnoneill** [comment]
okay to close?

**Comment by marlo-longley** [comment]
I think so ~ thanks.
