### ISSUE TITLE
Relationship between digital collections and child objects is broken

### ISSUE THREAD

**Issue by corylown** [sul-dlss/SearchWorks#3544]
For record [6976115](https://searchworks.stanford.edu/view/6976115) we should see a digital collection preview:

<img width="1238" alt="Screenshot 2023-09-25 at 5 24 14 PM" src="https://github.com/sul-dlss/SearchWorks/assets/458247/a906ed1c-46b4-47df-bc88-a45e73a2220a">

For record [bv852pc2545](https://searchworks.stanford.edu/view/bv852pc2545) we should see a context sidebar linking to the digital collection:

<img width="419" alt="Screenshot 2023-09-25 at 5 25 03 PM" src="https://github.com/sul-dlss/SearchWorks/assets/458247/c9f81e1c-7c01-48d0-bab9-192c170e96cb">

It looks like we're retaining the `a` prefix in the identifiers stored in the `collection`, `collection_search`, and `collection_with_title` fields. The fix is likely to be in searchwork_traject_indexer, but opening the issue here because the impact is in SearchWorks.

https://jirasul.stanford.edu/jira/browse/SW-4212

**Comment by thatbudakguy** [comment]
Sounds like the ideal solution is to just have SW ignore the `a` prefix.

**Comment by corylown** [comment]
This is not fixed completely.

The "[Explore this collection (160 digital items)](https://searchworks.stanford.edu/catalog?f%5Bcollection%5D%5B%5D=a11672504)" is broken on record https://searchworks.stanford.edu/view/11672504 because we're query for collection members with an a-prefixed catkey, but these collection members have a catkey without the a indexed in their `collection` field.
<img width="786" alt="Screenshot 2023-09-29 at 3 33 06 PM" src="https://github.com/sul-dlss/SearchWorks/assets/458247/b727a3dc-c2b0-4f6e-8798-10cff16f02ef">

We have some records indexed with the collection id prefixed with a and others without. This is because of different data published for different collections.

For example, compare:

```
irb(main):013> require './lib/public_xml_record.rb'
irb(main):017> PublicXmlRecord.new('sf251zg2010').searchworks_id
=> "11672504"
irb(main):018> PublicXmlRecord.new('bj250ww9882').searchworks_id
=> "a6976115"
```

Underlying logic for getting the catkey is here: https://github.com/sul-dlss/searchworks_traject_indexer/blob/main/lib/public_xml_record.rb#L27

I think we can be a little smarter about selecting the right id to link to because we have the collection member documents in the context where we're generating these links. These documents will have the correct for the id in their collection field.
