### ISSUE TITLE
BS4 branch: caret spacing

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/SearchWorks#3557]
The spacing seems too wide and the caret is not vertically centered. The caret is also larger but that could be acceptable.

production
<img width="1245" alt="Screen Shot 2023-09-28 at 9 24 33 AM" src="https://github.com/sul-dlss/SearchWorks/assets/1328900/82fa6a08-fe4f-4d62-86ae-67e19589a583">

BS4/stage
<img width="1190" alt="Screen Shot 2023-09-28 at 9 24 41 AM" src="https://github.com/sul-dlss/SearchWorks/assets/1328900/f1034903-96b5-472d-b6b7-333085493568">

**Comment by jcoyne** [comment]
I don't think this is something that we can change. This is a difference in Bootstrap.

**Comment by alundgard** [comment]
In prod, the caret has `margin-left: 2px; vertical-align: middle;` whereas bs4/stage has `margin-left: 0.255em; vertical-align: 0.255em;`. If it's possible to override / revert to the prod style, I think that'd be an aesthetic and UX improvement. But not super consequential.

**Comment by jcoyne** [comment]
<img width="247" alt="Screenshot 2023-09-28 at 3 26 50 PM" src="https://github.com/sul-dlss/SearchWorks/assets/92044/c9201f5e-8c73-412c-9a48-8de729b29feb">

@alundgard are we happy if this change also affects these ☝️

**Comment by jcoyne** [comment]
@alundgard Before we change the style, take another look.  There was some blank space between the anchor text and the `::after` element, which made it look odd.

**Comment by alundgard** [comment]
> are we happy if this change also affects these ☝️

Thanks for pointing this out. The changes look okay here too. Maybe slightly better if we add an extra pixel to the left margin: `margin-left: 3px; vertical-align: middle;` as applied to `.dropdown-toggle::after`.

> Before we change the style, take another look. There was some blank space between the anchor text and the `::after` element, which made it look odd.

I'm not sure that I notice any difference on stage? The caret vertical-alignment still looks higher than the link text. Setting `vertical-align: middle;` should address that. The changes to `margin-left` are less important.
