### ISSUE TITLE
BS4 branch: "Books, media & more" spacing

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/SearchWorks#3558]
The spacing has been collapsed 

production
<img width="444" alt="Screen Shot 2023-09-28 at 9 27 06 AM" src="https://github.com/sul-dlss/SearchWorks/assets/1328900/d9be02a2-7f50-46e3-9fab-2af2bf3d707d">

BS4/staging
<img width="423" alt="Screen Shot 2023-09-28 at 9 27 13 AM" src="https://github.com/sul-dlss/SearchWorks/assets/1328900/76af22e4-6084-46b0-b017-ce80cdc88647">

**Comment by jcoyne** [comment]
I think this is already fixed. Please confirm @marlo-longley
