### ISSUE TITLE
BS4 branch: header layout

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/SearchWorks#3561]
In production, the width of the search bar does not extend horizontally all the way above the "Selections (0)" area in the gray sub-header. Also, in production "Selections (0)" lies further to the right edge on the page. In the BS4 branch the search bar extends further horizontally. Not sure if this is an issue but it is a difference.

production
<img width="1265" alt="Screen Shot 2023-09-28 at 9 37 38 AM" src="https://github.com/sul-dlss/SearchWorks/assets/1328900/14a588e0-8589-41bc-9476-aacd49a61bb9">

BS4/staging
<img width="1270" alt="Screen Shot 2023-09-28 at 9 37 51 AM" src="https://github.com/sul-dlss/SearchWorks/assets/1328900/631c1461-07be-46b3-8ed9-dd9e2e795c8a">

**Comment by alundgard** [comment]
I agree with @jcoyne . Looks like an improvement to me: padding is now equal on both sides of the Search banner.
