### ISSUE TITLE
BS4 branch: index view metadata field alignment

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/SearchWorks#3570]
they're left-aligned in prod and right-aligned in bs4. I honestly don't know which is better, but presumably we did that for a reason?

## prod:
![Screenshot 2023-09-28 at 10 39 29](https://github.com/sul-dlss/SearchWorks/assets/4924494/263bdccb-6686-4684-97b9-00c61db22ae0)

## bs4:
![Screenshot 2023-09-28 at 10 39 34](https://github.com/sul-dlss/SearchWorks/assets/4924494/7c904300-1db2-4d9a-846e-a79c3d10715e)

**Comment by alundgard** [comment]
The bs4/stage right-alignment appears to text-wrap poorly when the field name is too long (see "Database topics" below). There's also indentation on the `Online` button. Simple is usually better imo, so I'd prefer the prod left-alignment.
### prod:
<img width="774" alt="alignment-prod" src="https://github.com/sul-dlss/SearchWorks/assets/2343316/fb231697-704f-44ce-8677-2016f924a0bd">

### bs4/stage:
<img width="774" alt="alignment-stage" src="https://github.com/sul-dlss/SearchWorks/assets/2343316/82c70eea-e05b-4e8e-81e9-ddb40d343d15">

That said, I can understand the motivation for right-aligning the field name. It's slightly easier to associate the field with its content when the visual gap is consistent across multiple fields (as in Nick's examples above). But the right-alignment looks a little odd when there's only one field (usually there's just a Description).

### prod:
<img width="773" alt="description-prod" src="https://github.com/sul-dlss/SearchWorks/assets/2343316/aefd1498-ebfb-4e13-9ccd-cd1517311f19">

### bs4/stage:
<img width="775" alt="description-stage" src="https://github.com/sul-dlss/SearchWorks/assets/2343316/43f7aebf-b9c5-46f2-82d9-850224c547b6">
