### ISSUE TITLE
BS4 branch: shortened metadata field with "more" link not visible on index page

### ISSUE THREAD

**Issue by hudajkhan** [sul-dlss/SearchWorks#3572]
In production, one of the items in the index view has a rather long summary section which is collapsed on page load and can be viewed using "more".  In the BS4 branch, the full summary is visible and there are no "more" or "less" links.

**Production**
![Screenshot 2023-09-28 at 12 42 28 PM](https://github.com/sul-dlss/SearchWorks/assets/2677207/80e973cc-102d-4672-bc56-f4cfd01f84a7)

![Screenshot 2023-09-28 at 12 42 28 PM](https://github.com/sul-dlss/SearchWorks/assets/2677207/703876bd-e8e1-46ff-bd2f-e819318da3f6)

**BS4 branch**
![Screenshot 2023-09-28 at 12 44 12 PM](https://github.com/sul-dlss/SearchWorks/assets/2677207/c1e0ef6a-f900-4a49-a643-fcdcd39aa685)

**Comment by jcoyne** [comment]
@hudajkhan I believe this is resolved. It was originally caused by a bug introduced when fixing the layout for course reserves.

**Comment by hudajkhan** [comment]
Looks great, thank you! I will go ahead and close.
