### ISSUE TITLE
BS4 branch: Availability text is not shortened and wraps around to under "Check availability" button

### ISSUE THREAD

**Issue by hudajkhan** [sul-dlss/SearchWorks#3573]
In production, when the text next to the "Check availability" button is too long, it is shortened and has ellipses.  In the BS4 branch, the full label is visible which then wraps around to under the availability button.

**Production** 
![Screenshot 2023-09-28 at 12 47 39 PM](https://github.com/sul-dlss/SearchWorks/assets/2677207/5b46fa6d-d5f9-42ba-a1b7-b3cc96b8e0f4)

**BS4 Branch**
![Screenshot 2023-09-28 at 12 48 01 PM](https://github.com/sul-dlss/SearchWorks/assets/2677207/bd20838d-7bba-4ccd-959b-0652a667d3e6)

**Comment by jcoyne** [comment]
I believe this is fixed, can you recheck?

**Comment by hudajkhan** [comment]
Looks good! Will close! Thanks!
