### ISSUE TITLE
[SearchWorks/prod] NoMethodError: undefined method `hours_api_url' for nil:NilClass

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/SearchWorks#3613]
## Backtrace

    line 11 of [PROJECT_ROOT]/lib/hours_request.rb: find_library
    line 15 of [PROJECT_ROOT]/lib/hours_request.rb: get
    line 3 of [PROJECT_ROOT]/app/controllers/hours_controller.rb: show

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50022/faults/96773507)

**Comment by marlo-longley** [comment]
Closed by #3615
