### ISSUE TITLE
test BS4 PR on mobile browsers

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/SearchWorks#3617]
judging from analytics data, our mobile browser breakdown is:

- 65% Chrome
- 25% Safari

...and all other browsers have less than 2% user share.

I think we need to test:

- [x] Safari on iOS
- [x] Chrome on Android

**Comment by thatbudakguy** [comment]
# Safari on iOS

I think you could replicate these results using the safari device emulator; not sure though.

(left is production, right is BS4)

<img width="250px" src="https://github.com/sul-dlss/SearchWorks/assets/4924494/1bc53ef9-25a1-45e3-8ab1-55c9bb51fb78">
<img width="250px" src="https://github.com/sul-dlss/SearchWorks/assets/4924494/b47170a3-ac24-4e4c-90df-e553fd80b4e1">
<br>
<img width="250px" src="https://github.com/sul-dlss/SearchWorks/assets/4924494/ba51a582-f730-4612-ac24-777edb41c199">
<img width="250px" src="https://github.com/sul-dlss/SearchWorks/assets/4924494/c58cfea1-de00-4692-864b-0f7da8a0007a">
<br>
<img width="250px" src="https://github.com/sul-dlss/SearchWorks/assets/4924494/b2139722-e52a-4143-9890-fb2a3b77d18c">
<img width="250px" src="https://github.com/sul-dlss/SearchWorks/assets/4924494/4e746ecc-2bc5-4e19-af65-4f3ad4e0f0cd">
<br>
<img width="250px" src="https://github.com/sul-dlss/SearchWorks/assets/4924494/533a9f21-08d5-4083-9836-bc030aeb9f5c">
<img width="250px" src="https://github.com/sul-dlss/SearchWorks/assets/4924494/63883cd4-1957-41f8-85cb-b713d95fa77c">

**Comment by thatbudakguy** [comment]
## Chrome on Android

No unique problems. The blue link issues ("all" dropdown in advanced search, up/down jump links) weren't present, but the spacing issues were the same as on iOS.

**Comment by jcoyne** [comment]
I fixed the layout on the advanced search. I'm not sure why you see the blue links.
