### ISSUE TITLE
By January, for SearchWorks display: ignore items in *-ERESV locations, added to electronic holdings records for Course Reserves 

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#3689]
Needs to be in production by Monday, January 8, 2024.

**Goal:** we need to _not_ display items (or the "At the library panel") on electronic holdings records that get a temporary item record added for the purposes of placing that title on Course Reserves.

**Context:** SUL Technical Services & LibSys decided not to add item records in FOLIO to Instances that have electronic holdings. That decision was fine until Course Reserves staff got requests from instructors to place electronic holdings on reserve. In FOLIO, the Courses app requires an item barcode. 

A large group convened to determine how to go forward. It was decided that item records would be added to Instances with electronic holdings records _only for the purposes of Course Reserves_. Course Reserve staff will be adding the items, and Technical Services/LibSys will remove the items periodically (TBD: at the end of the quarter or in the summer at the end of the Academic Year.)

In SearchWorks, we do not want this "fake" item record to trigger SearchWorks to display an "At the library" panel. We do want the Online & Course panels/widgets to display.

**Details:**
 The plan is to add new FOLIO locations for these items. New locations will be:
- SUL-ERESV
- LAW-ERESV
- BUS-ERESV
- (hopefully) LANE-ERESV

Should we use a new Locations Detail value to drive this?

**Comment by saseestone** [comment]
There is a question from Course Reserves staff if items should be using the new locations in the permanent or temporary location field in the item record. 

I asked Cory about this via slack. He wrote:

> I’d feel better if Chris verified this. But for the Course reserve display itself we only care about info that’s coming from the course reserves module in Folio that we look up as part of the indexing process. Location isn’t used at all. But we will need to filter out these new locations so we don’t display the at the library widget in SearchWorks for electronic items on reserve. I think it makes sense to handle this the same as other item on reserve and apply the *-ERSV location to the item’s temporary location.

I plan to instruct staff to place the new locations in the temporary location field in the Courses app.

**Comment by saseestone** [comment]
Location `SUL-ERESV` has been created on folio-test

**Comment by corylown** [comment]
In my quoted comment from Slack above I mentioned applying `*-ERSV` locations to the item's temporary location. I'm not sure it matters? I think we would just need a predictable place to look for this location code.

**Comment by saseestone** [comment]
Test set up in folio-test.

Item record: [Minerals : a very short introduction](https://searchworks-stage.stanford.edu/view/11372929). 
Item record in FOLIO: https://folio-test.stanford.edu/inventory/view/c7d62cd4-1f68-576f-8a95-b873bc170dcc/eef573fd-59a7-54af-9084-fecf8bd46f87/9c03ae01-32b7-4fea-a5e5-d42a7b2e0d47. 

- Note that it's currently suppressed from discovery, and using a new Location specific to these item records (SUL-ERESV)

Course record: PHYSICS-13N-01

**Comment by saseestone** [comment]
And two more tests:

Item: [The Story of the three little pigs](https://searchworks-stage.stanford.edu/view/15034046) 
Course: MATH-115-01

Item: [Eventful history of three little mice and how they became blind](https://searchworks-stage.stanford.edu/view/15037455)
Course: STATS-256-01
