### ISSUE TITLE
Add privilege group to auth check when determining access to articles+

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#3690]
Reported by James Harris in Technical Services, E-Resources division.

Two users with sponsored SUNet IDs reported that they can't access articles+, stanford-only resources even though the sponsoring faculty member indicated during sponsorship that they should be eligible to access online library resources. Looking at their Regadmin accounts, the users were showing a suAffiliation =`stanford:student:recent` despite the active sponsorship.  Based on the ranking in the [UIT Registry Affiliation table](https://uit.stanford.edu/service/registry/data-affiliation-types-qualifiers), we would have expected `stanford:affilate:sponsored` to outrank the `stanford:student:recent` affliation. 

Helen Clark provided the following explanation, via email, when asked specifically about one of the users - You Jia Zhu (SUNet ID = youjia):

> 
> - You are correct that the affiliate:sponsored affiliation ranks higher than the student:recent affiliation.
> - For a person to have the affiliate:sponsored affiliation, their SUNet ID sponsorship must be in 'active' status. 
> - If a recent student is sponsored for a SUNet ID but is still eligible for that level of SUNet ID services due to the recent student affiliation, the SUNet ID sponsorship will stay in 'created' status.   Once that level of SUNet ID services is not provided by the student recent affiliation,  the sponsorship status will change from 'created' to 'active', and the affiliation will become affiliate:sponsored.     
> - A recent student with a sponsorship in 'created' status though will be added to the  stanford:administrative and stanford:affiliate-sponsored privilege groups on the start date of the sponsorship.    (Please recall our 'created status' work in 2016.)   
> If the recent student is sponsored for Library e-resources, the student is added to the stanford:library-eresources-eligible privilege group.   
> 
> In the case of You Jia Zhu. SUNet ID: youjia: 
> 
> - The SUNet ID is currently active at the base service level due to the student:recent affiliation.
> - The base service level SUNet ID sponsorship is in 'created' status so the affiliation continues to be student:recent.
> - The library e-resources sponsorship is in 'active' status. 
> - You Jia's privilege groups include: stanford:administrative, stanford:affiliate-sponsored, stanford:library-eresources-eligible and stanford:student-recent.    
> - If You Jia needs the affiliate:sponsored affiliation, the department could sponsor You Jia at the full-service level.  Since You Jia has base SUNet ID services currently , a SUNet ID sponsorship at the full-service level would provide additional services and therefore the sponsorship would activate ('active' status).   The affiliation would then become affiliate:sponsored.   
> 

In my reading of Helen's response, the `stanford:student:recent` will outweigh the `stanford:affilate:sponsored` always.

We need to add a check for an active privgroup = `stanford:library-eresources-eligible` to our affiliation check, and we may need to include 'created' as an eligible status (in addition to 'active')

**Comment by hudajkhan** [comment]
Notes: 

- Settings file contains "SU_AFFILIATIONS" list. 
- Shared config production settings includes the list of affiliations for the system. 
- app/models/user.rb checks affiliations

**Comment by hudajkhan** [comment]
I started looking to see if I could get the **eduPersonEntitlement** shibboleth value (since that would tell us the privgroup and if someone has "stanford:library-eresources-eligible" as their privgroup).  We currently don't get this field back and we would have to make a request to UIT for it. 

Then I saw https://github.com/sul-dlss/operations-tasks/issues/2326 which makes it appear that I could use **eduPersonAffiliation**. I checked and I do see that field is available to the SearchWorks app.

It seems like **eduPersonAffiliation** will say "member" if the user has any of the following privgroups: stanford:library-eresources-eligible, gsb-apps:library-proxy-access, lane:proxy-access, and sulair:proxy-access . (based on https://uit.stanford.edu/service/saml/arp/edupa) 

_Question:_ Would it work to just check for "member" (which would include additional privgroups and not just "stanford:library-eresources-eligible") in **eduPersonAffiliation** or should I specifically request for **eduPersonEntitlement** and check that that equals "stanford:library-eresources-eligible"?

**Comment by saseestone** [comment]
My memory is that these different priv groups actually provide slightly different access to electronic resources. For example, there is a class of resources that Lane purchases, that are available only to Lane affiliates (based on the negotiated access permissions). My guess is that is achieved by using the lane:proxy-access priv group.  I'll check with Irina Trapido to make sure. (Or @cbeer maybe able to confirm.) 

My best guess right now is that using **eduPersonAffiliation** will be too broad, and we'll need to stay focused on using only stanford:library-eresources-eligible. More soon. 

I'll also checkin with Tom. He's on UIT SAML groups that we're not on, and sometimes has additional information/context. He's also the one that has done all the advocacy for UIT to add these additional **eduPersonAffiliation** fields.

**Comment by trapido** [comment]
EduPersonAffiliation::member and eduPersonEntitlement::stanford:library-eresources-eligible are identical, so it is okay to use eduPersonAffiliation::member.

**Comment by hudajkhan** [comment]
Closed by [#3832](https://github.com/sul-dlss/SearchWorks/pull/3832)
