### ISSUE TITLE
Emailing Selections not working for guest users

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#3700]
We've had a few reports that guest users of SearchWorks (i.e. not logged in) can't currently email selections. 

Using an incognito window, I could confirm. Chris/Cory suspect this might be an issue with reCaptcha. The form does have text that refers to reCaptcha, but the reCaptcha check is not displaying:
![image](https://github.com/sul-dlss/SearchWorks/assets/14897546/1c3841de-1b21-4108-9c9f-cfeb1b8d4b85)

Jira issues from SearchWorks feedback: [SW-4255](https://jirasul.stanford.edu/jira/browse/SW-4255), [SW-4254](https://jirasul.stanford.edu/jira/browse/SW-4254), [SW-4251](https://jirasul.stanford.edu/jira/browse/SW-4251)

**Comment by saseestone** [comment]
Cory reported that he can see the recaptcha when using firefox. 😢 

I'm using Chrome Version 119.0.6045.199 (Official Build) (arm64)

**Comment by taylor-steve** [comment]
This was last working in SearchWorks v3.20.0. In Blacklight, there was a shift from a "ajax-modal" system to a "blacklight-modal" system. For a time there appeared to be a mismatch between the container and the selector used to do the ajax replace for the modal content. Once this was fixed, the modal content was passed through a slightly different code path that filtered out scripts, breaking recaptcha. Justin patched this for SearchWorks in https://github.com/sul-dlss/SearchWorks/pull/3762
