### ISSUE TITLE
Use `courses_json_struct` instead of `crez_course_info`

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/SearchWorks#3736]
See https://github.com/sul-dlss/searchworks_traject_indexer/blob/main/lib/traject/config/folio_config.rb#L2517

1) document the shape of `courses_json_struct` in the traject config
2) confirm it has all the necessary data as `crez_course_info` (and add anything that's missing)
3) update `CourseReserves` concern to pull data from `courses_json_struct`
4) figure out what, if anything, to do with the `CourseReservesController` course info faceting

**Comment by hudajkhan** [comment]
[Also see: ](https://github.com/sul-dlss/searchworks_traject_indexer/blob/e0491c887170813888862756b2aa291304fc728c/lib/traject/config/folio_config.rb#L2599)

**Comment by hudajkhan** [comment]
This may require more clarification from Chris, especially regarding the first bullet.

**Comment by hudajkhan** [comment]
Chris says (1) means we should understand what is actually there in the FOLIO data that is coming back.

**Comment by jcoyne** [comment]
There are three locations in the code where this is being used:

1. In the CourseReservesController, where it's using it as a facet.  https://github.com/sul-dlss/SearchWorks/blob/main/app/controllers/course_reserves_controller.rb#L8
1. In `CourseReserveAccessPointHelper#create_course` https://github.com/sul-dlss/SearchWorks/blob/eceef766c1db35c6f1898cfe94fa3607c5e9cc0a/app/helpers/course_reserve_access_point_helper.rb#L2
1. In `CourseReserves::Processor` (https://github.com/sul-dlss/SearchWorks/blob/eceef766c1db35c6f1898cfe94fa3607c5e9cc0a/app/models/concerns/course_reserves.rb#L12)

**Comment by jcoyne** [comment]
because we do not index `*_struct` fields. I don't believe we are able to replace the usage in `CourseReservesController`.

**Comment by cbeer** [comment]
I don't think it makes sense to index all of `courses_json_struct` for faceting (and I don't think it'd do what we want either?). I wouldn't be surprised if we add a new field to support `CourseReservesController` or do something without solr to pull the course information.

**Comment by jcoyne** [comment]
I believe we can proceed on this when the `response.numFound` for the first query has an identical number as the latter query (currently 1101)
http://sul-solr-prod-b.stanford.edu/solr/#/searchworks-folio-dev/query?q=courses_folio_id_ssim:*&q.op=OR&indent=true
http://sul-solr-prod-b.stanford.edu/solr/#/searchworks-folio-dev/query?q=crez_course_id_search:*&q.op=OR&indent=true
