### ISSUE TITLE
page becomes unresponsive after following "Explore this collection" links

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#3741]
Reported by staff to PURL feedback ([PURL-1279](https://jirasul.stanford.edu/jira/browse/PURL-1279)) and SW feedback ([SW-427](https://jirasul.stanford.edu/jira/browse/SW-4272))

The following list of actions crashes the view pages in both Firefox and Chrome for this example record: https://searchworks.stanford.edu/view/12142651 
2. I click on the "Explore this collection" link in the digital collection preview pane, OR one of the digital objects that appear in the digital collection preview pane.
3. I click on the link back to the "Amos Gitai film collection" record from one of the search result listings, or from the "Item belongs to a collection" pane.
4. Once back on the collection record page, I can no longer click any links. The page eventually slows down enough that my browser tells me the page is unresponsive and I should close it.

This happens with digital collection previews on other pages as well. I cleared my cache and the issue persisted.

**Comment by saseestone** [comment]
Andrew reported the following in the PURL ticket:

Hi Jeanette,

I took a look at this with Annie earlier and suggested she submit the SearchWorks feedback. I don’t think this is related to SDR viewer work, though I could be wrong.

I see it happening on the Stanford Syllabi Collection, for example, which has no images in the preview: https://searchworks.stanford.edu/view/12832734

That’s a rather large collection, but this GIS data collection is smaller and also has the problem with no images in the preview: https://searchworks.stanford.edu/view/13329690

Looking further, I don’t see it happening on the Nuremberg Trial Archives collection: https://searchworks.stanford.edu/view/mt839rq8746

The difference I see in that comparison is that collections that are linked to FOLIO records have a problem and collections that are not linked to FOLIO seem to be ok.

**Comment by saseestone** [comment]
I could also recreate it, though I had a slightly different experience:

1. Using https://searchworks.stanford.edu/view/12142651, I clicked on the "Explore this collection" link in the digital preview
2. Scrolled through the search results, but didn't click on anything
3. Tried to use the browser back button to get to the collection record and couldn't get back. As I scrolled back down through the results list, the top of the page was completely blank. Then the entire page was unresponsive and blank.  
4. Eventually I got a "page unresponsive" error message, but the page had been completely blank for quite awhile before the error displayed.

**Comment by corylown** [comment]
This may be impacting other records as well, not just ones with an "Explore this collection" link.

Using our favorite bound-with example, _[Heart damage in baled jute](https://searchworks.stanford.edu/view/2279186)_, if I click on the bound-with link "Copy 1 bound with v. 5, no. 1. 36105026515499 (item id)" and then click the browser's back button the browser becomes unresponsive.

**Comment by jcoyne** [comment]
I'm pretty sure this is a bug in turbolinks.  We might want to upgrade to turbo in order to fix this.

**Comment by cbeer** [comment]
I'm not sure about turbolinks, but this looks like #1863 / #3597 to me.

My suggestion in https://github.com/sul-dlss/SearchWorks/pull/3597/files#r1344164391 should fix it.
