### ISSUE TITLE
Revise librarian view on an item detail page

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/SearchWorks#3761]
Public services support staff have long used the MARC 999, visible in Librarian view, to quickly view item level information needed for a variety of tasks. This view was especially useful to volunteers & temporary staff in special collections units, who do not have access to the ILS. When we moved to FOLIO, the Symphony-constructed 999 field ceased. This has negatively impacted staff, who now struggle to interpret the FOLIO json. Additionally, the FOLIO UI makes it difficult to quickly see item information if the Instance record has more than 50 items. 

Most desired is a “Quick look” that would contain Call number, Item ID (barcode), FOLIO permanent and effective location. If that’s not possible, having the FOLIO json structured in a tree format may help staff inexperienced with reading json - particularly when viewing records with large numbers of items.

UX Doc - https://docs.google.com/document/d/1NSgaHmcatoo8oH-dcB0e5cpNE9888I--v24sN-JGPMM/edit?usp=sharing

**Comment by dbranchini** [comment]
We decided to add an item detail view to satisfy this use case. Please [see prototype](https://www.figma.com/proto/W3GIkPyGLeO5xMojmkZuTX/SearchWorks?page-id=0%3A1&type=design&node-id=168-1124&viewport=-2827%2C2224%2C0.5&t=rLRVVXE7bkpty3iG-1&scaling=min-zoom&starting-point-node-id=168%3A1124&show-proto-sidebar=1&mode=design) - first example shows an item with a single copy and/or volume, and the second example shows an item with multiple copies and/or volumes. For a real example of an item with several copies/volumes, please see the [Buckminster fuller papers](https://searchworks.stanford.edu/view/4332640). 

There is a screenshot from the prototype below to get a basic idea of the formatting/layout. 

![Image](https://github.com/sul-dlss/SearchWorks/assets/6816624/522ea93d-6813-4a5a-b290-943d3c7cb052)

These ideas need to be reviewed with devs and stakeholders.

**Comment by dbranchini** [comment]
Sections: 
- Five sections:
-- Metadata
-- Librarian View **_(new section)_**
-- Holdings JSON
-- FOLIO JSON
-- Circulation Rules 
- All sections are collapsed by default.
- Section headings are the same as they are now in production.

Librarian View:
- Four fields are displayed:
-- Permanent location
-- Effective call number
-- Barcode
-- Effective location
- Field names are the same in FOLIO
- Values are grouped by permanent location
--  Permanent location is a sub-heading (40 pixels in height) and the same background-color that's used in Holdings and FOLIO JSON.
- Table values
-- Effective call number, Barcode and Effective Location are column headings and bolded.
-- Rows have a bottom border (or line in between rows)
-- As displayed:
--- Indented by 40px
--- Field values are 175 px wide with 48 px in between. If field values exceed this, they should wrap. 
--- Mobile view - let's chat about this, but I'd recommend a stacked view.
- Effective location value is ONLY shown when it's different than permanent location

**Comment by saseestone** [comment]
@dbranchini I think we talked about pulling the indexing information out of the collapsed "Metadata" section, and having it appear on the top of the page. Correct?

**Comment by saseestone** [comment]
Also in your write up from this morning, you've got the header text "Librarian View", when I think you mean "Item Details". 

The entire modal will be "Librarian View" and the second collapsed section would be called "Item Details". 

(and I just noticed we're not using sentence case. Should we?)

**Comment by dbranchini** [comment]
@saseestone . yes, we did! Thank you for the reminder. I'll fix the summary above Librarian View -> Item Details.

**Comment by dbranchini** [comment]
NOTE: Last updated on... has been moved out of the Metadata section to the top of the modal next to the header, "Librarian View"

<img width="816" alt="Screenshot 2024-02-05 at 1 56 55 PM" src="https://github.com/sul-dlss/SearchWorks/assets/6816624/050bddad-f030-4965-8e4a-7b218e82196d">

**Comment by jcoyne** [comment]
@dbranchini It looks like you've removed the "close" button from the modal. Is that right?

**Comment by dbranchini** [comment]
@jcoyne , not intentional, the close X button should remain.

**Comment by jcoyne** [comment]
@dbranchini Can you explain what you want to show here?  Do you have some idea about where this data should come from?

![Image](https://github.com/sul-dlss/SearchWorks/assets/92044/7688527c-32f8-4a09-915a-8cda723b119b)

**Comment by cbeer** [comment]
I think the existing content is fine. This design is only adding the new "Item Details" and collapsing all the sections by default.

**Comment by jcoyne** [comment]
@dbranchini is there a reason for "Effective Call Number" vs "Call Number"?

**Comment by cbeer** [comment]
Effective call number is the FOLIO term of art.

**Comment by jcoyne** [comment]
@dbranchini what do we want to show for bound-with items (e.g. https://searchworks.stanford.edu/view/2279186) .  These typically don't have items in Folio.  Do we want to show no items in this case, or should we do something with the holding records?

How about E-resources (https://searchworks.stanford.edu/view/14136548) these also have no items in Folio.

**Comment by cbeer** [comment]
At least in this first pass, I think we can + should omit the whole section for records without FOLIO items.

**Comment by dbranchini** [comment]
Good question, @jcoyne, and thanks for answering this @cbeer, that makes sense to me since the whole area is titled, "Item details." I'll have to understand better how users use this to answer these questions.
