### ISSUE TITLE
Handle new FOLIO location SAL3-SCAN-PAGE-SP

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#3765]
A new FOLIO location was created to handle a group of materials that will be:

- Physically held at SAL3, and records will be given a FOLIO library = SAL3. Location has location detail "availabilityClass = Offsite"
- Should be pageable only to Special Collections (but will not be mediated in requests by Aeon). Location has location detail "pageServicePointCodes = SPEC"
- Should be scannable, with the scanning being performed at SAL3. Location has location detail "scanServicePointCode = SAL3"

~~As of right now (1/19/24 at 4:48) the circulation rule needed to handle this location has not been created. I've reached out to Circ Administrators to create it so that all request types are allowed.~~Circ rules created.

One record, visible in SearchWorks, has been given this location: https://searchworks.stanford.edu/view/in00000039909. 😿 
Right now, we aren't displaying the "At the library" panel correctly.  It should be "SAL3".

**Comment by hudajkhan** [comment]
This issue addresses components that already exist, but we have never handled this particular configuration before.  There may be pairing required.

**Comment by saseestone** [comment]
Circrules were added to FOLIO around 10am this morning.

**Comment by jcoyne** [comment]
It looks to me like the problem is in the Solr document `item_display` field.  You can see that `'library' => 'SUL'`:

```
search_service_class = CatalogController.new.search_service_class
blacklight_config = CatalogController.blacklight_config
search_state = Blacklight::SearchState.new({}, blacklight_config)
search_service =  search_service_class.new(config: blacklight_config, search_state: search_state, user_params: search_state.to_h)
id = 'in00000039909'
_, solr_doc = search_service.fetch(id)
holdings = solr_doc.holdings

holdings.items.first.item_display
 =>
{"id"=>"a292c4af-3a7a-4adc-9397-a3791494eb0f",
 "barcode"=>"36105236438201",
 "library"=>"SUL",
 "home_location"=>"SUL-TS-PROCESSING",
 "current_location"=>"INTRANSIT",
 "type"=>"archival",
 "note"=>nil,
 "instance_id"=>"ebf39216-2f9a-41b5-b024-af38df7043c0",
 "instance_hrid"=>"in00000039909",
 "temporary_location_code"=>nil,
 "permanent_location_code"=>"SUL-TS-PROCESSING",
 "status"=>"In transit",
 "effective_location_id"=>"e99ac505-53ee-4db8-bf82-d9efcae6f5c9",
 "material_type_id"=>"69edaa1b-e40b-4f1c-8cb5-4b615ac6a664",
 "loan_type_id"=>"52d7b849-b6d8-4fb3-b2ab-a9b0eb41b6fd",
 "lopped_callnumber"=>"SE0001 ...",
 "shelfkey"=>"other se000001 ...",
 "reverse_shelfkey"=>"b6il8~7lzzzzzy~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
 "callnumber"=>"SE0001 BOX 1",
 "full_shelfkey"=>"other se000001 box 000001",
 "scheme"=>"ALPHANUM"}
```

**Comment by corylown** [comment]
@jcoyne @saseestone I think we're not expecting the temporary location of `SUL-TS-PROCESSING` to be set on the holding. If `SUL-TS-PROCESSING` were set as a temporary location for the item I think this would display the way we're expecting it to:
<img width="377" alt="Screenshot 2024-01-22 at 3 56 14 PM" src="https://github.com/sul-dlss/SearchWorks/assets/458247/f51ae0db-3277-4f35-a6db-63dda6905db5">

**Comment by saseestone** [comment]
I'm checking with Metadata to see if this is as expected (i.e. we need to plan for temp locs on holdings records) or a data mistake.

**Comment by saseestone** [comment]
Metadata says we should not need to handle holdings records with temporary locations. They removed the SUL-TS-PROCESSING temporary location from the holdings record, and applied it to the appropriate items. 

The At the library and item list are now displaying correctly, but we're not showing a request button. I'm looking into why.

**Comment by saseestone** [comment]
Chris pointed out that the Loan Type assigned to all the items is "non-circulating". We expect the loan type to be "can circulate" and the circulation rules to govern the actual circulation-ness.
