### ISSUE TITLE
bug: not able to log in as user in development

### ISSUE THREAD

**Issue by dnoneill** [sul-dlss/SearchWorks#3774]
When trying to run the application under the ["logging in" as a user in development](https://github.com/sul-dlss/SearchWorks#logging-in-as-a-user-in-development) there is an `Validation failed: User can't be blank` error. See attached screenshot for entire error in browser.

Also this functionality worked one release back: https://github.com/sul-dlss/SearchWorks/releases/tag/v3.21.13

<img width="994" alt="Screenshot 2024-01-22 at 5 15 26 PM" src="https://github.com/sul-dlss/SearchWorks/assets/19173991/df3c0ad8-85bc-45fa-ad44-0bf4e0ab0891">

**Comment by jcoyne** [comment]
@dnoneill I'm unable to duplicate. What command are you running?

**Comment by taylor-steve** [comment]
I was getting this as well, but I believe @dnoneill and I both have this working now after trying again in a completely fresh environment.

@corylown I know you saw this error too. Closing this assuming we all had the same stale environment issue.
