### ISSUE TITLE
Digital bookplate display broken in Chrome 

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#3776]
Our digital book plate display was broken for me tonight on Chrome v120.0.6099.234: 
<img width="534" alt="image" src="https://github.com/sul-dlss/SearchWorks/assets/14897546/99912d8d-296b-43f4-8eb3-30f335ebdd87">

When I looked at the record on Firefox v115.6.0esr it was fine:
<img width="457" alt="image" src="https://github.com/sul-dlss/SearchWorks/assets/14897546/f95dfe26-1997-4c2f-896a-4bff45790bf6">

Record I was viewing: https://searchworks.stanford.edu/view/14653940

**Comment by jcoyne** [comment]
It seems to work fine for me in Chrome:
<img width="703" alt="Screenshot 2024-01-23 at 6 46 29 AM" src="https://github.com/sul-dlss/SearchWorks/assets/92044/7372b955-055b-463c-9dea-76e3c90eb8a3"> I've "Version 120.0.6099.234", how about you?

**Comment by saseestone** [comment]
Can't duplicate again.
