### ISSUE TITLE
When emailing selections as a guest, email doesn't send 

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#3808]
Maybe related to work done on #3700 

User can now see (and go through the very long reCaptcha check) but selecting "Send" doesn't seem to do anything except reload the form. The user does not receive the emailed selections.

**Comment by jcoyne** [comment]
It seems to work on stage, but not on production.  This may help us debug: https://github.com/sul-dlss/SearchWorks/pull/3809

**Comment by taylor-steve** [comment]
Thanks @jcoyne. Right now, it appears to work adding `noscript: false` to the recaptcha_tags options. Checking to see if I missed anything else (and why this is suddenly a problem) but this one might be straightforward.
