### ISSUE TITLE
Request button displaying when circrule indicating "no requests allowed"

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#3810]
Staff reported today that we have a hold/recall request button displaying in SW on items currently checked out, but using a FOLIO circrule that should restrict requesting.

Example records currently checked out: 
https://searchworks.stanford.edu/view/9700486 (uses circrule line 195)
https://searchworks.stanford.edu/view/13634849 (uses circrule line 234)

Both circrule lines have "no-requests-allowed" in FOLIO. 
<img width="793" alt="image" src="https://github.com/sul-dlss/SearchWorks/assets/14897546/9416d399-ec30-4bb8-9b30-dcbd120e5495">

<img width="805" alt="image" src="https://github.com/sul-dlss/SearchWorks/assets/14897546/3a3285dc-2a00-447c-ba70-17b8f6483fb3">

I confirmed with the circrule administrators that they have not changed either circrule recently (no changes since September 2023). I can't figure out what might be going on here.  We should be honoring the circrule w/regard to the request button. 

More context about the items:
These are accessories (a whiteboard kit and a sewing kit). They should be able to be checked out in FOLIO, but staff have elected NOT to use requests to help manage access. Sometimes that's because the items check out for only a few hours.

Because staff have not wanted to place request buttons on these short term loans, we're able to send all our hold/recall requests to ILLiad.  The staff member who reported the issue was an ILL staffer. They got a request for a sewing kit 🙃

**Comment by corylown** [comment]
The request policy seems right. And SearchWorks is interpreting the policy correctly.

However, think we're injecting a request link from the availability lookup script without checking the request policy: https://github.com/sul-dlss/SearchWorks/blob/10bc0c1a57f27c5804e4070a1e3328547b603a40/app/javascript/jquery.live-lookup.js#L42

**Comment by saseestone** [comment]
Hoping this doesn't add complexity, but because "Course Reserves" always tends to add complexity, I wanted to point-out that we're having this issue (Item level request buttons displaying on items governed by circrules that should make them not requestable) on items that are associated with a Course in FOLIO.

Example (right now..this is a 2 hour loan): https://searchworks.stanford.edu/view/11526874

**Comment by corylown** [comment]
Closed by #3814
