### ISSUE TITLE
IIIF drag+drop badge thing disappeared from search results

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/SearchWorks#3863]
IIIF images in search results used to have a IIIF drag+drop icon:
<img width="827" alt="Screenshot 2024-02-05 at 08 16 28" src="https://github.com/sul-dlss/SearchWorks/assets/111218/977f0b0b-d727-4ad9-9d01-55540579430b">

The image (and all of its markup) is now missing:
<img width="929" alt="Screenshot 2024-02-05 at 08 15 31" src="https://github.com/sul-dlss/SearchWorks/assets/111218/112b078a-66de-4283-ac52-fe994cfee95b">

Presumably this is a regression introduced in https://github.com/sul-dlss/SearchWorks/pull/3799

**Comment by jcoyne** [comment]
I can confirm this worked in b669d3ec5ee48d87c6fb56a7dd5948ad3bf57a6e
