### ISSUE TITLE
Link styling is wrong for managed purls

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/SearchWorks#3899]
See https://searchworks.stanford.edu/view/8112988

The underline is at the bottom when hovering.
<img width="385" alt="Screenshot 2024-02-07 at 9 18 18 AM" src="https://github.com/sul-dlss/SearchWorks/assets/92044/9a0c1b91-5a36-4943-9fe4-b32a20839ecb">

**Comment by dnoneill** [comment]
@jcoyne .managed-purl li button:hover needs to be changed to text-decoration: underline instead of border-bottom
