### ISSUE TITLE
Ctrl + clicking on title no longer opens record in new tab

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#3902]
Staff reported that this issue started very recently. Cory mentioned he's also experienced it very recently.  You can see this easily by doing any search and trying to use Control + click on any title in the search results.

https://searchworks.stanford.edu/?f%5Bbuilding_facet%5D%5B%5D=Philosophy+%28Tanner%29&sort=year-asc

Jira issue where it was reported:https://jirasul.stanford.edu/jira/browse/SW-4292

**Comment by jcoyne** [comment]
This seems like a bug in `turbo`, because if I add `data-turbo="false"` to the link it restores the desired behavior.

**Comment by dnoneill** [comment]
I also found that in the application.js under Map2 there is a ```
_onKeyDown: function(e) {
            if (e.altKey || e.ctrlKey || e.metaKey) {
              return;
}}
``` If it is commented out it works as well.

**Comment by jcoyne** [comment]
This seems to be caused by `ActionController::InvalidAuthenticityToken` on the Blacklight tracking route.

**Comment by jcoyne** [comment]
@taylor-steve yes, it's known to be https://github.com/sul-dlss/SearchWorks/pull/3740

**Comment by jcoyne** [comment]
I suspect https://github.com/projectblacklight/blacklight/pull/3142 will help fix this.

**Comment by jcoyne** [comment]
https://github.com/projectblacklight/blacklight/pull/3147 is the backport to 7.x

**Comment by jcoyne** [comment]
Fixed by #4009
