### ISSUE TITLE
Remove duplicate "In process" on access (availability) card

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/SearchWorks#3912]
Examples where this is happening: 

<img src="https://github.com/sul-dlss/SearchWorks/assets/6816624/5d80dae6-f097-4569-943b-0dea04ba8226" width="300">

SAL3 - location-level request button
- https://searchworks.stanford.edu/view/in00000034827 
- https://searchworks.stanford.edu/view/13968683 
- https://searchworks.stanford.edu/view/6781597

Special Collections - no request option
- https://searchworks.stanford.edu/view/14389025

In process refers to an item in an internal library process such as cataloging or binding. 

Per @cbeer (and I'm sure he can explain this better than me), this is showing up twice because some staff workflows use the item status "In process" _and_ they use a temporary location (effective location) with a description of "In process". We could consider changing this description, but I understand that some libraries use only the location to represent when an item is in this state instead of the item status or both item status and location. @saseestone and I plan to have discussions with library staff to understand better why they are doing this as we continue to do more analysis regarding request processing, so our proposed short-term solution is to detect when there's a duplicate and only display it once. 

There are also records where it's displaying correctly and only once. Presumably, this is because these locations only use location or item status. 

Education - location-level request button
- https://searchworks.stanford.edu/view/13309126

**Desired layout/pattern:**

- The pattern for displaying "In process" should follow other unavailable statuses, such as "In transit". An X icon and status is displayed in red. 
- If it's a location-level request button, then the call number and status are in one row - the call number is aligned left, and the status (In process) is aligned right.
- If it's an item-level request button, then there are two rows - the call number is on one and aligned left, and the status (In process) with the request button is on the next row and aligned left, too. 

**Desired layout/pattern screenshots:**

Item-level request example:
<img src="https://github.com/sul-dlss/SearchWorks/assets/6816624/57b74afd-e053-4210-97df-700ebbe2503d" width="300">

Location-level request examples:
<img src="https://github.com/sul-dlss/SearchWorks/assets/6816624/56c7c0ea-7063-49b8-b8f7-6ea0c32f55c9" width="300">

<img src="https://github.com/sul-dlss/SearchWorks/assets/6816624/497e9073-2d0a-4d50-a2a5-e7f100ca4078" width="300">

<img src="https://github.com/sul-dlss/SearchWorks/assets/6816624/8a04e620-c2d2-450f-8f91-52538a4f82ee" width="300">

**Comment by dnoneill** [comment]
This should be held off on. A lot of this gets fixed with https://github.com/sul-dlss/SearchWorks/pull/3892

**Comment by dbranchini** [comment]
Don't have a resolution yet for this, but didn't want to lose this. We need to consider a related issue where the display is "In process/In transit" - https://searchworks.stanford.edu/view/446185.

**Comment by cbeer** [comment]
I think #3892 fixed the example records, at least. Thanks @dnoneill
