### ISSUE TITLE
Library hours inaccurate on record detail view

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/SearchWorks#3940]
**Environment:** Production

**Steps to reproduce:**

1. Go to any of the following record views:
-- https://searchworks.stanford.edu/view/in00000039980 (Green Library)
-- https://searchworks.stanford.edu/view/3305821 (Law Library)
-- https://searchworks.stanford.edu/view/L354432 (Lane Medical Library)
-- https://searchworks.stanford.edu/view/in00000011584 (Business Library)
2. Scroll to At the library
3. Note the library and hours listed
4. Click on the library link (above the hours)
5. Note the library hours on the library website and/or "branch" page on the SUL website

**Expected result:** Library hours **are the same in SearchWorks** as the library's hours listed on their respective websites/pages. It should be verified that the website hours are correct for each of these.

**Actual result:** Library hours **are different in SearchWorks** from the library's hours listed on their respective websites/pages. 

**Screenshots/visuals:**

From the Business Library example - link listed above: 
![Image](https://github.com/sul-dlss/SearchWorks/assets/6816624/e3580f5b-a57b-4d5e-872f-362468cc3b7a)
![Image](https://github.com/sul-dlss/SearchWorks/assets/6816624/fc097943-7ed1-49d0-a903-25e41a58ae76)

**Comment by jcoyne** [comment]
In https://github.com/sul-dlss/SearchWorks/blob/main/app/javascript/location-hours.js#L70 we need to use Pacific time zone for parsing, otherwise it will be in the browser locale rather than the user locale:
```
new Intl.DateTimeFormat('en', {timeZone: 'America/Los_Angeles', timeStyle: 'short'}).format(utc_date)
"8:00 AM" 
```
