### ISSUE TITLE
Remove “At the library” section for coordinate online records; Add coordinate library to Available online card

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/SearchWorks#3944]
## Problem Statement:
We have an inconsistent display for eResource records without a physical volume associated with the record. 

- If the eResource-only record is “owned” by SUL, we do NOT display the “At the Library” section. 
- If the eResource-only record is “owned” by Business, Lane Medical & Law, we DO display the “At the Library” section as well as the "Online" section. It displays correctly in the "Available online" card, but it displays a vague eResource with an item status of "Unknown" in the "At the Library" section which is confusing to users. The record is also added to the Library facet. 

### SUL - **_At the Library is not displayed_**:

Screenshot follows:
<img src="https://github.com/sul-dlss/SearchWorks/assets/6816624/0c21c821-2161-4840-8d6d-e7a66a01863f" width="200">

---

### Coordinate libraries - **_At the Library is displayed_**:
Libraries/records are: [Business: The emotional brain…](https://searchworks.stanford.edu/view/in00000011584); [Lane Medical: Brain communications](https://searchworks.stanford.edu/view/L354432); [Law: Breakthroughs in brain research… ](https://searchworks.stanford.edu/view/3305821) 

Screenshots from above records follow:
<img src="https://github.com/sul-dlss/SearchWorks/assets/6816624/94792a39-bae6-4a9b-a659-952df83b5440" width="200"> <img src="https://github.com/sul-dlss/SearchWorks/assets/6816624/403a058c-c97d-4ac2-bdc4-6149c6b4999f" width="200">  <img src="https://github.com/sul-dlss/SearchWorks/assets/6816624/689d95f2-ee71-4515-92ff-90b8397c48ae" width="200"> 

## Proposed Solution:
- Remove "At the library" heading and card from eResource-only records "owned" by a coordinate library.
- Maintain the relationship and facet (desired behavior by stakeholders).
- Add the "owning" coordinate library to the "Available online" card above the eResource link as shown on the comp.
- Specific styles:
-- Font size is the same as font used elsewhere - 14 px.
-- Spacing b/n lines - 4 px.
-- Coordinate library is a heavier font-weight - 600 or bold.

**NOTE: This is for eResource-only records. For example, it would not apply this record - https://searchworks.stanford.edu/view/15095727.**

See the screenshot and comp:

At the library/Unknown "Flow" on the Figma sidebar**
https://www.figma.com/proto/W3GIkPyGLeO5xMojmkZuTX/SearchWorks?page-id=0%3A1&type=design&node-id=308-1254&viewport=-62%2C-2146%2C0.25&t=iNqOsgsz6STHXHkf-1&scaling=min-zoom&starting-point-node-id=308%3A1254&show-proto-sidebar=1&mode=design

<img src="https://github.com/sul-dlss/SearchWorks/assets/6816624/e6f63c84-f2fe-4dc7-827a-3737ff049120" width="300">

**Comment by cbeer** [comment]
> If the eResource-only record is “owned” by Business, Lane Medical & Law

In FOLIO, I think this boils down to "show the library name if the holdings location campus isn't SUL". It also includes Hoover, but we don't think Hoover has any e-resource only records.

**Comment by saseestone** [comment]
Darcy sent this to stakeholders for feedback today. Due date for feedback is EOD Friday, Feb. 16.

**Comment by dnoneill** [comment]
I have the first part done. The second part (adding the location is a little tricky and I am not sure we want to do it. The big problem is we don't have a good way (that I can figure) to know if the link is a external link or internal so we could have the location showing for things we don't have any power over like hathitrust. While I could write some conditionals to check I am not sure how many sites we link to externally and I am not sure that the library who holds it is especially useful to the user. 

![Image](https://github.com/sul-dlss/SearchWorks/assets/19173991/10688486-ca85-4dba-abc0-c4aac1e26074)
![Image](https://github.com/sul-dlss/SearchWorks/assets/19173991/f58cc5cc-26dc-476b-a300-e1ec0a0eba9f)

**Comment by dbranchini** [comment]
Also, this needs to be addressed on search results. 

<img src="https://github.com/sul-dlss/SearchWorks/assets/6816624/a162d123-ceea-4131-9fdb-10f642fab8c1" width="400">

**Comment by dnoneill** [comment]
@dbranchini @saseestone I updated as discussed. I built in some logic that makes sure that the library does not show up in the online section if there are physical copies. i.e. https://searchworks.stanford.edu/view/14640037. Also are we considering Green a branch library? Is this something we need to worry about displaying?

**Comment by dbranchini** [comment]
No, Green is not a coordinate library, so it shouldn't be included. It should be Lane, Law, Hoover, and Business only (those are all considered coordinate libraries) that have these types of associations with electronic resources. It's my understanding the rest should always be SUL electronic holdings (not associated with a particular library). BUT the record you refer to above is confusing to me. I looked it up in FOLIO, and it's showing no SUL electronic holdings or items and only an aged-to-lost book, so I'm not sure where the online items are coming from in SearchWorks. @cbeer or @saseestone, maybe you have insight on this?

**Comment by cbeer** [comment]
Instead of special cases for those 4, I think my comment last week still applies:
>  In FOLIO, I think this boils down to "show the library name if the holdings location campus isn't SUL". It also includes Hoover, but we don't think Hoover has any e-resource only records.

https://github.com/sul-dlss/SearchWorks/issues/3944#issuecomment-1944365950

The online item comes from the MARC 856 field, doesn't it? I believe FOLIO item records were only created for electronic resources  if there was no physical item

**Comment by dnoneill** [comment]
@dbranchini @saseestone If there is only a google preview of the online item (no other links) I don't have it including the library name. Do you want this behavior or do you want it to show up if there is a google preview only?

**Comment by cbeer** [comment]
I don't /think/ that case (should) exist. If we don't have a link from the MARC or a physical item, I think we wouldn't index the record in the first place.

**Comment by dnoneill** [comment]
@cbeer I am guessing this is only for when there is a physical location as well then? https://github.com/sul-dlss/SearchWorks/blob/bf6f332831111056e113df9f97352fb1e8655866/app/components/access_panels/online_component.html.erb#L46-L48
