### ISSUE TITLE
call number browse preview with multiple call numbers.

### ISSUE THREAD

**Issue by dnoneill** [sul-dlss/SearchWorks#4035]
If you go to [https://searchworks.stanford.edu/view/3998525](https://searchworks.stanford.edu/view/3998525) click on the second call number then click on preview. Switch to the first call number, click on preview. Preview won't display.

![Screenshot 2024-02-26 at 2 47 27 PM](https://github.com/sul-dlss/SearchWorks/assets/19173991/29920355-3270-46c1-97b0-d48744f9aad3)

**Comment by cbeer** [comment]
With #4073 (etc), we're only showing one call number now 😌
