### ISSUE TITLE
Support for type = Book

### ISSUE THREAD

**Issue by snydman** [sul-dlss/SearchWorks#407]
This is a feature ticket for SearchWorks to handle GryphonDOR content with type=Book. On the record view page this would include embedding the existing embeddable FlipBook viewer  that is also embedded on PURL pages (see: http://purl.stanford.edu/bb085ws2114).

What would be needed to display type=book in the results view, film-strip and gallery views?  Tagged as design needed in case any design review or input is necessary.  

Another consideration is how "Stanford Only" flipbooks will behave.

**Comment by jvine** [comment]
SW-1546 also related

Example in both preview and prod: 

http://searchworks-test.stanford.edu/preview/view/cj445qq4021 
http://searchworks.stanford.edu/view/cj445qq4021 

Members are books and individual items show correctly in embed. But the collection does not show a filmstrip of the thumb images, treating it instead as a table of contents listing. The display type of the collection is "book" reflecting the membership, but that does not seem to be treated as "image" as expected?

**Comment by jkeck** [comment]
Will be completed in PR that completes #1146
