### ISSUE TITLE
Hoover library name missing in Safari

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/SearchWorks#4093]
At some point (#3823 ?) we've introduced a regression in the At the library library name header. Hoover used to be truncated with ellipses (because it's library name is so long). Now, it doesn't appear at all (in Safari): 
Safari:
![Screenshot 2024-03-06 at 09 36 19](https://github.com/sul-dlss/SearchWorks/assets/111218/897283e7-bb14-4d1d-b829-afff80a57a37)

And isn't truncated (but very nearby overflows) the area in other browsers, e.g. Firefox:
![Screenshot 2024-03-06 at 09 36 33](https://github.com/sul-dlss/SearchWorks/assets/111218/2f58b310-6c90-4ecc-b303-209521d91e71)

See https://searchworks.stanford.edu/view/in00000063652 (or any other Hoover record)

**Comment by jcoyne** [comment]
It displays in safari for me ( Version 17.3.1)

![Image](https://github.com/sul-dlss/SearchWorks/assets/92044/dc6b5a01-8617-486f-acd9-8e50dad004e8)

**Comment by cbeer** [comment]
After the FOLIO launch (and in recent memory), it looked like this:
![Screenshot 2024-03-06 at 12 11 56](https://github.com/sul-dlss/SearchWorks/assets/111218/bf43f7bd-500c-4143-9b7c-ea2fb5b21e52)

**Comment by dbranchini** [comment]
Related to #4095
