### ISSUE TITLE
Restore request links to Aged to Lost

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#4197]
In prod, we've suppressed request links for items with a FOLIO status = Aged to lost. 

After we move our new forms to production, we should restore the request links on items with this FOLIO item status and allow SUNet ID users to place requests. The request should always be directed to ILLiad. (In fact, FOLIO will struggle because FOLIO requests are not allowed for this item status per https://lotus.docs.folio.org/docs/platform-essentials/item-status/itemstatus/#currently-implemented-item-statuses.

**Comment by thatbudakguy** [comment]
We need to make changes to the `SubmitPatronRequestJob` so that this is explicitly allowed – otherwise we will check if the item can be hold/recalled and find out that it can't (because FOLIO prohibits this item status from being recalled) and decide that it's not requestable.

**Comment by dnoneill** [comment]
Changes to `SubmitPatronRequestJob` has been split into a different ticket.
