### ISSUE TITLE
Law’s proxy logic issue in SearchWorks

### ISSUE THREAD

**Issue by huang559** [sul-dlss/SearchWorks#4219]
Hello,
 
I submitted a ticket regarding the Law’s proxy logic issue in SearchWorks last Friday. The issue may lead to off-campus access problems for law school users. Could you provide an update on it? 
 
Thanks,
Qi
--
Qi Huang
Electronic Resources Librarian
Stanford Law School Library
qi.huang@law.stanford.edu

Examples:
Fastcase
https://searchworks.stanford.edu/view/8236110
without law proxy:
https://apps.fastcase.com/PartnerBenefits/?IPKEY=nmThbmeNOXlx22lmjd4KbmrKxafPH8Ey5Zk3%2bdh52f3q1MtItMkY%2bZ0I5wih%2bfpn49SX3blmF%2bAwdAkfhTPEZS8RD5sgcV27QXVz2pSEoAKG4IGvdTyjaK9XAMGL93vq&LogoutUrl=http%3a%2f%2flaw.stanford.edu%2flibrary

Almanac of the federal judiciary
https://searchworks.stanford.edu/view/12864848
without law proxy:
https://almanacofthefederaljudiciary.com/
 
Immigration law & policy in the U.S.
https://searchworks.stanford.edu/view/11925296
with SUL proxy instead of Law’s:
https://stanford.idm.oclc.org/login?qurl=https://heinonline.org/HOL/Index?index=immigration&collection=immigration
 
LLMC digital
https://searchworks.stanford.edu/view/8336445
with SUL proxy instead of Law’s:
https://stanford.idm.oclc.org/login?qurl=https://www.llmc.com

**Comment by corylown** [comment]
@huang559 this has been fixed.

https://github.com/sul-dlss/SearchWorks/issues/4217

**Comment by huang559** [comment]
Thanks so much, Cory!
