### ISSUE TITLE
For Fall 2024: Display only active/pending Courses in Browse course reserves

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#4289]
For Fall 2024 (Best to release on/before September 16, 2024) 

For this list: https://searchworks.stanford.edu/reserves

We should display only Course records that:

-  Have a Course status of "Active" or "Pending"
OR
-  Have an "end date" in the future

We could use the Term date set for this.

**Comment by hudajkhan** [comment]
Some background info:

- The API call to get the course information is here: 
https://s3.amazonaws.com/foliodocs/api/mod-courses/r/courses.html#coursereserves_courses_get
- This API is called here in FOLIO client: https://github.com/sul-dlss/SearchWorks/blob/def694f0d52adf0785f3cf2b4176179333bf68b1/app/services/folio_client.rb#L55C5-L55C97
- Information is stored in the database. Currently the only fields are name of course, course number, instructors, and id. See https://github.com/sul-dlss/SearchWorks/blob/main/db/migrate/20240613182000_create_course_reserves.rb 
- This is the ActiveRecord class related to course reserves: https://github.com/sul-dlss/SearchWorks/blob/main/app/models/course_reserve.rb.  We will probably need to add more fields to the database. 
- This writes the info from FOLIO to the database, so if we want to track more info in the database, after we have created the database fields, we would change this to save that info: https://github.com/sul-dlss/SearchWorks/blob/main/app/services/folio/courses.rb 
- To display under /reserves, here is the controller: https://github.com/sul-dlss/SearchWorks/blob/main/app/controllers/course_reserves_controller.rb 
- Related view: https://github.com/sul-dlss/SearchWorks/blob/main/app/views/course_reserves/index.html.erb
