### ISSUE TITLE
Should items with shelving/sort key but no callnumber come up in the browse nearby?

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/SearchWorks#483]
See discussion at #475 
@ndushay 
The items that are coming up in your browse DO have a shelving/sort key which is why it comes up in the browse nearby, however the callnumber is blank.

    <arr name="item_display">
      <str>9634618-1001 -|- SUL -|- INTERNET -|- -|- SUL -|- -|- lc qa 0076.893000 r0.650000 002012 -|- en~9p~~zzst}rqwzzz~8z}tuzzzz~zzxzyx~~~~~~~~~~~~~~~ -|- -|-
      </str>
    </arr>

**Comment by jvine** [comment]
Superseded by later decisions.
