### ISSUE TITLE
Resource type icon visibility

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#615]
Assess whether the icons will be more visible/readable with some of the font options - colour, filled in, line thickness, etc.

**Comment by jvine** [comment]
sul_styles ...?

**Comment by jvine** [comment]
Will this be handled by #1079 ?

**Comment by jkeck** [comment]
As long as the icons in SUL Styles satisfies your concerns about this icon, then yes, and we should probably close this and use that as the work ticket.

**Comment by jvine** [comment]
Okay.
