### ISSUE TITLE
Keep date punctuation together in titles

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#693]
Open-ended date ranges allow the closing paren to wrap on its own to a new line. Can we make this a bit more graceful? Maybe keep the whole date segment together always?

![keep date punctuation together](https://cloud.githubusercontent.com/assets/6945691/3882753/357fa626-219a-11e4-8d19-0b7f00e8963e.png)

**Comment by cbeer** [comment]
Fixes by #2180
