### ISSUE TITLE
Sidebar nav display issue on IE 8 and 9

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#843]
Nav icons stack weirdly in older versions of IE.

![ie sw 3 0 display issue](https://cloud.githubusercontent.com/assets/6945691/4153930/6a525260-345d-11e4-9d5c-16f9e6ea5e4c.png)

(reported by Laszlo, verified in cross-browser testing)

**Comment by jkeck** [comment]
May want to address while dealing with #908

**Comment by jvine** [comment]
Distribution of browser usage...

![screen shot 2015-10-23 at 12 06 22 pm](https://cloud.githubusercontent.com/assets/6945691/10702422/868d0512-797e-11e5-9297-b868e653b805.png)

**Comment by jvine** [comment]
Browsers in the affected versions account for less than 0.1% of our users. Closing.
