### ISSUE TITLE
Searching "SearchWorks" in google on a mobile phone yields "Remove constraint" 

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/SearchWorks#984]
Possibly the `:` in the title.

May be solved by adding appropriate meta tags.

**Comment by mejackreed** [comment]
Here is another search with those results: https://www.google.com/search?q=Friederike+Alschner&oq=Friederike+Alschner&q=Friederike+Alschner+stanford

**Comment by jvine** [comment]
Fixed
